// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jaco/v1/commands.proto

package jacov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestartCounterUpdate_Action int32

const (
	RestartCounterUpdate_ACTION_UNSPECIFIED RestartCounterUpdate_Action = 0
	RestartCounterUpdate_ACTION_INCREMENT   RestartCounterUpdate_Action = 1
	RestartCounterUpdate_ACTION_RESET       RestartCounterUpdate_Action = 2
)

// Enum value maps for RestartCounterUpdate_Action.
var (
	RestartCounterUpdate_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_INCREMENT",
		2: "ACTION_RESET",
	}
	RestartCounterUpdate_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_INCREMENT":   1,
		"ACTION_RESET":       2,
	}
)

func (x RestartCounterUpdate_Action) Enum() *RestartCounterUpdate_Action {
	p := new(RestartCounterUpdate_Action)
	*p = x
	return p
}

func (x RestartCounterUpdate_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RestartCounterUpdate_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_jaco_v1_commands_proto_enumTypes[0].Descriptor()
}

func (RestartCounterUpdate_Action) Type() protoreflect.EnumType {
	return &file_jaco_v1_commands_proto_enumTypes[0]
}

func (x RestartCounterUpdate_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RestartCounterUpdate_Action.Descriptor instead.
func (RestartCounterUpdate_Action) EnumDescriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{16, 0}
}

// Command is the FSM apply envelope. One oneof variant per state mutation.
type Command struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ClusterId string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	RaftIndex uint64                 `protobuf:"varint,2,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	Ts        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Identity  string                 `protobuf:"bytes,4,opt,name=identity,proto3" json:"identity,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Command_ClusterInit
	//	*Command_NodeJoin
	//	*Command_NodeRemove
	//	*Command_NodeStatusUpdate
	//	*Command_DeploymentApply
	//	*Command_DeploymentRollback
	//	*Command_DeploymentDelete
	//	*Command_DeploymentStatusUpdate
	//	*Command_ReplicaDesiredUpsert
	//	*Command_ReplicaDesiredRemove
	//	*Command_ReplicaObservedUpdate
	//	*Command_ReplicaCommandIssue
	//	*Command_RolloutPlanUpdate
	//	*Command_ReplicaCounterIncrement
	//	*Command_RestartCounterUpdate
	//	*Command_RouteUpsert
	//	*Command_RouteRemove
	//	*Command_CertStore
	//	*Command_CertLock
	//	*Command_CertUnlock
	//	*Command_ChallengeTokenStore
	//	*Command_SubnetAllocate
	//	*Command_SubnetFree
	//	*Command_TokenIssue
	//	*Command_TokenRevoke
	//	*Command_JoinTokenIssue
	//	*Command_JoinTokenConsume
	//	*Command_AuditAppend
	//	*Command_Batch
	Payload       isCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_jaco_v1_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *Command) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

func (x *Command) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Command) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *Command) GetPayload() isCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Command) GetClusterInit() *ClusterInit {
	if x != nil {
		if x, ok := x.Payload.(*Command_ClusterInit); ok {
			return x.ClusterInit
		}
	}
	return nil
}

func (x *Command) GetNodeJoin() *NodeJoin {
	if x != nil {
		if x, ok := x.Payload.(*Command_NodeJoin); ok {
			return x.NodeJoin
		}
	}
	return nil
}

func (x *Command) GetNodeRemove() *NodeRemove {
	if x != nil {
		if x, ok := x.Payload.(*Command_NodeRemove); ok {
			return x.NodeRemove
		}
	}
	return nil
}

func (x *Command) GetNodeStatusUpdate() *NodeStatusUpdate {
	if x != nil {
		if x, ok := x.Payload.(*Command_NodeStatusUpdate); ok {
			return x.NodeStatusUpdate
		}
	}
	return nil
}

func (x *Command) GetDeploymentApply() *DeploymentApply {
	if x != nil {
		if x, ok := x.Payload.(*Command_DeploymentApply); ok {
			return x.DeploymentApply
		}
	}
	return nil
}

func (x *Command) GetDeploymentRollback() *DeploymentRollback {
	if x != nil {
		if x, ok := x.Payload.(*Command_DeploymentRollback); ok {
			return x.DeploymentRollback
		}
	}
	return nil
}

func (x *Command) GetDeploymentDelete() *DeploymentDelete {
	if x != nil {
		if x, ok := x.Payload.(*Command_DeploymentDelete); ok {
			return x.DeploymentDelete
		}
	}
	return nil
}

func (x *Command) GetDeploymentStatusUpdate() *DeploymentStatusUpdate {
	if x != nil {
		if x, ok := x.Payload.(*Command_DeploymentStatusUpdate); ok {
			return x.DeploymentStatusUpdate
		}
	}
	return nil
}

func (x *Command) GetReplicaDesiredUpsert() *ReplicaDesiredUpsert {
	if x != nil {
		if x, ok := x.Payload.(*Command_ReplicaDesiredUpsert); ok {
			return x.ReplicaDesiredUpsert
		}
	}
	return nil
}

func (x *Command) GetReplicaDesiredRemove() *ReplicaDesiredRemove {
	if x != nil {
		if x, ok := x.Payload.(*Command_ReplicaDesiredRemove); ok {
			return x.ReplicaDesiredRemove
		}
	}
	return nil
}

func (x *Command) GetReplicaObservedUpdate() *ReplicaObservedUpdate {
	if x != nil {
		if x, ok := x.Payload.(*Command_ReplicaObservedUpdate); ok {
			return x.ReplicaObservedUpdate
		}
	}
	return nil
}

func (x *Command) GetReplicaCommandIssue() *ReplicaCommandIssue {
	if x != nil {
		if x, ok := x.Payload.(*Command_ReplicaCommandIssue); ok {
			return x.ReplicaCommandIssue
		}
	}
	return nil
}

func (x *Command) GetRolloutPlanUpdate() *RolloutPlanUpdate {
	if x != nil {
		if x, ok := x.Payload.(*Command_RolloutPlanUpdate); ok {
			return x.RolloutPlanUpdate
		}
	}
	return nil
}

func (x *Command) GetReplicaCounterIncrement() *ReplicaCounterIncrement {
	if x != nil {
		if x, ok := x.Payload.(*Command_ReplicaCounterIncrement); ok {
			return x.ReplicaCounterIncrement
		}
	}
	return nil
}

func (x *Command) GetRestartCounterUpdate() *RestartCounterUpdate {
	if x != nil {
		if x, ok := x.Payload.(*Command_RestartCounterUpdate); ok {
			return x.RestartCounterUpdate
		}
	}
	return nil
}

func (x *Command) GetRouteUpsert() *RouteUpsert {
	if x != nil {
		if x, ok := x.Payload.(*Command_RouteUpsert); ok {
			return x.RouteUpsert
		}
	}
	return nil
}

func (x *Command) GetRouteRemove() *RouteRemove {
	if x != nil {
		if x, ok := x.Payload.(*Command_RouteRemove); ok {
			return x.RouteRemove
		}
	}
	return nil
}

func (x *Command) GetCertStore() *CertStore {
	if x != nil {
		if x, ok := x.Payload.(*Command_CertStore); ok {
			return x.CertStore
		}
	}
	return nil
}

func (x *Command) GetCertLock() *CertLock {
	if x != nil {
		if x, ok := x.Payload.(*Command_CertLock); ok {
			return x.CertLock
		}
	}
	return nil
}

func (x *Command) GetCertUnlock() *CertUnlock {
	if x != nil {
		if x, ok := x.Payload.(*Command_CertUnlock); ok {
			return x.CertUnlock
		}
	}
	return nil
}

func (x *Command) GetChallengeTokenStore() *ChallengeTokenStore {
	if x != nil {
		if x, ok := x.Payload.(*Command_ChallengeTokenStore); ok {
			return x.ChallengeTokenStore
		}
	}
	return nil
}

func (x *Command) GetSubnetAllocate() *SubnetAllocate {
	if x != nil {
		if x, ok := x.Payload.(*Command_SubnetAllocate); ok {
			return x.SubnetAllocate
		}
	}
	return nil
}

func (x *Command) GetSubnetFree() *SubnetFree {
	if x != nil {
		if x, ok := x.Payload.(*Command_SubnetFree); ok {
			return x.SubnetFree
		}
	}
	return nil
}

func (x *Command) GetTokenIssue() *TokenIssue {
	if x != nil {
		if x, ok := x.Payload.(*Command_TokenIssue); ok {
			return x.TokenIssue
		}
	}
	return nil
}

func (x *Command) GetTokenRevoke() *TokenRevoke {
	if x != nil {
		if x, ok := x.Payload.(*Command_TokenRevoke); ok {
			return x.TokenRevoke
		}
	}
	return nil
}

func (x *Command) GetJoinTokenIssue() *JoinTokenIssue {
	if x != nil {
		if x, ok := x.Payload.(*Command_JoinTokenIssue); ok {
			return x.JoinTokenIssue
		}
	}
	return nil
}

func (x *Command) GetJoinTokenConsume() *JoinTokenConsume {
	if x != nil {
		if x, ok := x.Payload.(*Command_JoinTokenConsume); ok {
			return x.JoinTokenConsume
		}
	}
	return nil
}

func (x *Command) GetAuditAppend() *AuditAppend {
	if x != nil {
		if x, ok := x.Payload.(*Command_AuditAppend); ok {
			return x.AuditAppend
		}
	}
	return nil
}

func (x *Command) GetBatch() *Batch {
	if x != nil {
		if x, ok := x.Payload.(*Command_Batch); ok {
			return x.Batch
		}
	}
	return nil
}

type isCommand_Payload interface {
	isCommand_Payload()
}

type Command_ClusterInit struct {
	ClusterInit *ClusterInit `protobuf:"bytes,10,opt,name=cluster_init,json=clusterInit,proto3,oneof"`
}

type Command_NodeJoin struct {
	NodeJoin *NodeJoin `protobuf:"bytes,11,opt,name=node_join,json=nodeJoin,proto3,oneof"`
}

type Command_NodeRemove struct {
	NodeRemove *NodeRemove `protobuf:"bytes,12,opt,name=node_remove,json=nodeRemove,proto3,oneof"`
}

type Command_NodeStatusUpdate struct {
	NodeStatusUpdate *NodeStatusUpdate `protobuf:"bytes,13,opt,name=node_status_update,json=nodeStatusUpdate,proto3,oneof"`
}

type Command_DeploymentApply struct {
	DeploymentApply *DeploymentApply `protobuf:"bytes,20,opt,name=deployment_apply,json=deploymentApply,proto3,oneof"`
}

type Command_DeploymentRollback struct {
	DeploymentRollback *DeploymentRollback `protobuf:"bytes,21,opt,name=deployment_rollback,json=deploymentRollback,proto3,oneof"`
}

type Command_DeploymentDelete struct {
	DeploymentDelete *DeploymentDelete `protobuf:"bytes,22,opt,name=deployment_delete,json=deploymentDelete,proto3,oneof"`
}

type Command_DeploymentStatusUpdate struct {
	DeploymentStatusUpdate *DeploymentStatusUpdate `protobuf:"bytes,23,opt,name=deployment_status_update,json=deploymentStatusUpdate,proto3,oneof"`
}

type Command_ReplicaDesiredUpsert struct {
	ReplicaDesiredUpsert *ReplicaDesiredUpsert `protobuf:"bytes,30,opt,name=replica_desired_upsert,json=replicaDesiredUpsert,proto3,oneof"`
}

type Command_ReplicaDesiredRemove struct {
	ReplicaDesiredRemove *ReplicaDesiredRemove `protobuf:"bytes,31,opt,name=replica_desired_remove,json=replicaDesiredRemove,proto3,oneof"`
}

type Command_ReplicaObservedUpdate struct {
	ReplicaObservedUpdate *ReplicaObservedUpdate `protobuf:"bytes,32,opt,name=replica_observed_update,json=replicaObservedUpdate,proto3,oneof"`
}

type Command_ReplicaCommandIssue struct {
	ReplicaCommandIssue *ReplicaCommandIssue `protobuf:"bytes,33,opt,name=replica_command_issue,json=replicaCommandIssue,proto3,oneof"`
}

type Command_RolloutPlanUpdate struct {
	RolloutPlanUpdate *RolloutPlanUpdate `protobuf:"bytes,34,opt,name=rollout_plan_update,json=rolloutPlanUpdate,proto3,oneof"`
}

type Command_ReplicaCounterIncrement struct {
	ReplicaCounterIncrement *ReplicaCounterIncrement `protobuf:"bytes,35,opt,name=replica_counter_increment,json=replicaCounterIncrement,proto3,oneof"`
}

type Command_RestartCounterUpdate struct {
	RestartCounterUpdate *RestartCounterUpdate `protobuf:"bytes,36,opt,name=restart_counter_update,json=restartCounterUpdate,proto3,oneof"`
}

type Command_RouteUpsert struct {
	RouteUpsert *RouteUpsert `protobuf:"bytes,40,opt,name=route_upsert,json=routeUpsert,proto3,oneof"`
}

type Command_RouteRemove struct {
	RouteRemove *RouteRemove `protobuf:"bytes,41,opt,name=route_remove,json=routeRemove,proto3,oneof"`
}

type Command_CertStore struct {
	CertStore *CertStore `protobuf:"bytes,50,opt,name=cert_store,json=certStore,proto3,oneof"`
}

type Command_CertLock struct {
	CertLock *CertLock `protobuf:"bytes,51,opt,name=cert_lock,json=certLock,proto3,oneof"`
}

type Command_CertUnlock struct {
	CertUnlock *CertUnlock `protobuf:"bytes,52,opt,name=cert_unlock,json=certUnlock,proto3,oneof"`
}

type Command_ChallengeTokenStore struct {
	ChallengeTokenStore *ChallengeTokenStore `protobuf:"bytes,53,opt,name=challenge_token_store,json=challengeTokenStore,proto3,oneof"`
}

type Command_SubnetAllocate struct {
	SubnetAllocate *SubnetAllocate `protobuf:"bytes,60,opt,name=subnet_allocate,json=subnetAllocate,proto3,oneof"`
}

type Command_SubnetFree struct {
	SubnetFree *SubnetFree `protobuf:"bytes,61,opt,name=subnet_free,json=subnetFree,proto3,oneof"`
}

type Command_TokenIssue struct {
	TokenIssue *TokenIssue `protobuf:"bytes,70,opt,name=token_issue,json=tokenIssue,proto3,oneof"`
}

type Command_TokenRevoke struct {
	TokenRevoke *TokenRevoke `protobuf:"bytes,71,opt,name=token_revoke,json=tokenRevoke,proto3,oneof"`
}

type Command_JoinTokenIssue struct {
	JoinTokenIssue *JoinTokenIssue `protobuf:"bytes,72,opt,name=join_token_issue,json=joinTokenIssue,proto3,oneof"`
}

type Command_JoinTokenConsume struct {
	JoinTokenConsume *JoinTokenConsume `protobuf:"bytes,73,opt,name=join_token_consume,json=joinTokenConsume,proto3,oneof"`
}

type Command_AuditAppend struct {
	AuditAppend *AuditAppend `protobuf:"bytes,80,opt,name=audit_append,json=auditAppend,proto3,oneof"`
}

type Command_Batch struct {
	Batch *Batch `protobuf:"bytes,90,opt,name=batch,proto3,oneof"`
}

func (*Command_ClusterInit) isCommand_Payload() {}

func (*Command_NodeJoin) isCommand_Payload() {}

func (*Command_NodeRemove) isCommand_Payload() {}

func (*Command_NodeStatusUpdate) isCommand_Payload() {}

func (*Command_DeploymentApply) isCommand_Payload() {}

func (*Command_DeploymentRollback) isCommand_Payload() {}

func (*Command_DeploymentDelete) isCommand_Payload() {}

func (*Command_DeploymentStatusUpdate) isCommand_Payload() {}

func (*Command_ReplicaDesiredUpsert) isCommand_Payload() {}

func (*Command_ReplicaDesiredRemove) isCommand_Payload() {}

func (*Command_ReplicaObservedUpdate) isCommand_Payload() {}

func (*Command_ReplicaCommandIssue) isCommand_Payload() {}

func (*Command_RolloutPlanUpdate) isCommand_Payload() {}

func (*Command_ReplicaCounterIncrement) isCommand_Payload() {}

func (*Command_RestartCounterUpdate) isCommand_Payload() {}

func (*Command_RouteUpsert) isCommand_Payload() {}

func (*Command_RouteRemove) isCommand_Payload() {}

func (*Command_CertStore) isCommand_Payload() {}

func (*Command_CertLock) isCommand_Payload() {}

func (*Command_CertUnlock) isCommand_Payload() {}

func (*Command_ChallengeTokenStore) isCommand_Payload() {}

func (*Command_SubnetAllocate) isCommand_Payload() {}

func (*Command_SubnetFree) isCommand_Payload() {}

func (*Command_TokenIssue) isCommand_Payload() {}

func (*Command_TokenRevoke) isCommand_Payload() {}

func (*Command_JoinTokenIssue) isCommand_Payload() {}

func (*Command_JoinTokenConsume) isCommand_Payload() {}

func (*Command_AuditAppend) isCommand_Payload() {}

func (*Command_Batch) isCommand_Payload() {}

// Batch carries multiple commands applied atomically inside one raft Apply.
type Batch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Children      []*Command             `protobuf:"bytes,1,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_jaco_v1_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{1}
}

func (x *Batch) GetChildren() []*Command {
	if x != nil {
		return x.Children
	}
	return nil
}

type ClusterInit struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ClusterId string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	CaCert    []byte                 `protobuf:"bytes,2,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	CaKey     []byte                 `protobuf:"bytes,3,opt,name=ca_key,json=caKey,proto3" json:"ca_key,omitempty"`
	// Hashed secret for the initial operator token; the cleartext is returned to
	// the bootstrap caller and is never stored.
	OperatorTokenHashedSecret []byte `protobuf:"bytes,4,opt,name=operator_token_hashed_secret,json=operatorTokenHashedSecret,proto3" json:"operator_token_hashed_secret,omitempty"`
	// Self-node identity recorded in state.Nodes so NodeList reflects the
	// bootstrap node from the start.
	SelfHostname  string `protobuf:"bytes,5,opt,name=self_hostname,json=selfHostname,proto3" json:"self_hostname,omitempty"`
	SelfAddress   string `protobuf:"bytes,6,opt,name=self_address,json=selfAddress,proto3" json:"self_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterInit) Reset() {
	*x = ClusterInit{}
	mi := &file_jaco_v1_commands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterInit) ProtoMessage() {}

func (x *ClusterInit) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterInit.ProtoReflect.Descriptor instead.
func (*ClusterInit) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterInit) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ClusterInit) GetCaCert() []byte {
	if x != nil {
		return x.CaCert
	}
	return nil
}

func (x *ClusterInit) GetCaKey() []byte {
	if x != nil {
		return x.CaKey
	}
	return nil
}

func (x *ClusterInit) GetOperatorTokenHashedSecret() []byte {
	if x != nil {
		return x.OperatorTokenHashedSecret
	}
	return nil
}

func (x *ClusterInit) GetSelfHostname() string {
	if x != nil {
		return x.SelfHostname
	}
	return ""
}

func (x *ClusterInit) GetSelfAddress() string {
	if x != nil {
		return x.SelfAddress
	}
	return ""
}

type NodeJoin struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Hostname              string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Address               string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	ServerCertFingerprint []byte                 `protobuf:"bytes,3,opt,name=server_cert_fingerprint,json=serverCertFingerprint,proto3" json:"server_cert_fingerprint,omitempty"`
	WireguardPubkey       []byte                 `protobuf:"bytes,4,opt,name=wireguard_pubkey,json=wireguardPubkey,proto3" json:"wireguard_pubkey,omitempty"`
	GrpcAddress           string                 `protobuf:"bytes,5,opt,name=grpc_address,json=grpcAddress,proto3" json:"grpc_address,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *NodeJoin) Reset() {
	*x = NodeJoin{}
	mi := &file_jaco_v1_commands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeJoin) ProtoMessage() {}

func (x *NodeJoin) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeJoin.ProtoReflect.Descriptor instead.
func (*NodeJoin) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{3}
}

func (x *NodeJoin) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeJoin) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeJoin) GetServerCertFingerprint() []byte {
	if x != nil {
		return x.ServerCertFingerprint
	}
	return nil
}

func (x *NodeJoin) GetWireguardPubkey() []byte {
	if x != nil {
		return x.WireguardPubkey
	}
	return nil
}

func (x *NodeJoin) GetGrpcAddress() string {
	if x != nil {
		return x.GrpcAddress
	}
	return ""
}

type NodeRemove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRemove) Reset() {
	*x = NodeRemove{}
	mi := &file_jaco_v1_commands_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRemove) ProtoMessage() {}

func (x *NodeRemove) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRemove.ProtoReflect.Descriptor instead.
func (*NodeRemove) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{4}
}

func (x *NodeRemove) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type NodeStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Status        NodeStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=jaco.v1.NodeStatus" json:"status,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatusUpdate) Reset() {
	*x = NodeStatusUpdate{}
	mi := &file_jaco_v1_commands_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusUpdate) ProtoMessage() {}

func (x *NodeStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusUpdate.ProtoReflect.Descriptor instead.
func (*NodeStatusUpdate) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{5}
}

func (x *NodeStatusUpdate) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeStatusUpdate) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *NodeStatusUpdate) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type DeploymentApply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    string                 `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	JacoYaml      []byte                 `protobuf:"bytes,3,opt,name=jaco_yaml,json=jacoYaml,proto3" json:"jaco_yaml,omitempty"`
	ComposeYaml   []byte                 `protobuf:"bytes,4,opt,name=compose_yaml,json=composeYaml,proto3" json:"compose_yaml,omitempty"`
	Services      []*ServiceSpec         `protobuf:"bytes,5,rep,name=services,proto3" json:"services,omitempty"`
	Routes        []*Route               `protobuf:"bytes,6,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentApply) Reset() {
	*x = DeploymentApply{}
	mi := &file_jaco_v1_commands_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentApply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentApply) ProtoMessage() {}

func (x *DeploymentApply) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentApply.ProtoReflect.Descriptor instead.
func (*DeploymentApply) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{6}
}

func (x *DeploymentApply) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

func (x *DeploymentApply) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *DeploymentApply) GetJacoYaml() []byte {
	if x != nil {
		return x.JacoYaml
	}
	return nil
}

func (x *DeploymentApply) GetComposeYaml() []byte {
	if x != nil {
		return x.ComposeYaml
	}
	return nil
}

func (x *DeploymentApply) GetServices() []*ServiceSpec {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *DeploymentApply) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type DeploymentRollback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    string                 `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentRollback) Reset() {
	*x = DeploymentRollback{}
	mi := &file_jaco_v1_commands_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentRollback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentRollback) ProtoMessage() {}

func (x *DeploymentRollback) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentRollback.ProtoReflect.Descriptor instead.
func (*DeploymentRollback) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{7}
}

func (x *DeploymentRollback) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

func (x *DeploymentRollback) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type DeploymentDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    string                 `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentDelete) Reset() {
	*x = DeploymentDelete{}
	mi := &file_jaco_v1_commands_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentDelete) ProtoMessage() {}

func (x *DeploymentDelete) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentDelete.ProtoReflect.Descriptor instead.
func (*DeploymentDelete) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{8}
}

func (x *DeploymentDelete) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

type DeploymentStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    string                 `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Status        DeploymentStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=jaco.v1.DeploymentStatus" json:"status,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentStatusUpdate) Reset() {
	*x = DeploymentStatusUpdate{}
	mi := &file_jaco_v1_commands_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentStatusUpdate) ProtoMessage() {}

func (x *DeploymentStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentStatusUpdate.ProtoReflect.Descriptor instead.
func (*DeploymentStatusUpdate) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{9}
}

func (x *DeploymentStatusUpdate) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

func (x *DeploymentStatusUpdate) GetStatus() DeploymentStatus {
	if x != nil {
		return x.Status
	}
	return DeploymentStatus_DEPLOYMENT_STATUS_UNSPECIFIED
}

func (x *DeploymentStatusUpdate) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type ReplicaDesiredUpsert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replica       *ReplicaDesired        `protobuf:"bytes,1,opt,name=replica,proto3" json:"replica,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaDesiredUpsert) Reset() {
	*x = ReplicaDesiredUpsert{}
	mi := &file_jaco_v1_commands_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaDesiredUpsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaDesiredUpsert) ProtoMessage() {}

func (x *ReplicaDesiredUpsert) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaDesiredUpsert.ProtoReflect.Descriptor instead.
func (*ReplicaDesiredUpsert) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{10}
}

func (x *ReplicaDesiredUpsert) GetReplica() *ReplicaDesired {
	if x != nil {
		return x.Replica
	}
	return nil
}

type ReplicaDesiredRemove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaDesiredRemove) Reset() {
	*x = ReplicaDesiredRemove{}
	mi := &file_jaco_v1_commands_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaDesiredRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaDesiredRemove) ProtoMessage() {}

func (x *ReplicaDesiredRemove) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaDesiredRemove.ProtoReflect.Descriptor instead.
func (*ReplicaDesiredRemove) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{11}
}

func (x *ReplicaDesiredRemove) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReplicaObservedUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replica       *ReplicaObserved       `protobuf:"bytes,1,opt,name=replica,proto3" json:"replica,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaObservedUpdate) Reset() {
	*x = ReplicaObservedUpdate{}
	mi := &file_jaco_v1_commands_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaObservedUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaObservedUpdate) ProtoMessage() {}

func (x *ReplicaObservedUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaObservedUpdate.ProtoReflect.Descriptor instead.
func (*ReplicaObservedUpdate) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{12}
}

func (x *ReplicaObservedUpdate) GetReplica() *ReplicaObserved {
	if x != nil {
		return x.Replica
	}
	return nil
}

// ReplicaCommandIssue is consumed by runtime / ingress via watches; not a
// stored entity, just a one-shot ledger entry.
type ReplicaCommandIssue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicaId     string                 `protobuf:"bytes,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Op            string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaCommandIssue) Reset() {
	*x = ReplicaCommandIssue{}
	mi := &file_jaco_v1_commands_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaCommandIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaCommandIssue) ProtoMessage() {}

func (x *ReplicaCommandIssue) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaCommandIssue.ProtoReflect.Descriptor instead.
func (*ReplicaCommandIssue) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{13}
}

func (x *ReplicaCommandIssue) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *ReplicaCommandIssue) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

type RolloutPlanUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          *RolloutPlan           `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolloutPlanUpdate) Reset() {
	*x = RolloutPlanUpdate{}
	mi := &file_jaco_v1_commands_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolloutPlanUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolloutPlanUpdate) ProtoMessage() {}

func (x *RolloutPlanUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolloutPlanUpdate.ProtoReflect.Descriptor instead.
func (*RolloutPlanUpdate) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{14}
}

func (x *RolloutPlanUpdate) GetPlan() *RolloutPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

type ReplicaCounterIncrement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    string                 `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaCounterIncrement) Reset() {
	*x = ReplicaCounterIncrement{}
	mi := &file_jaco_v1_commands_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaCounterIncrement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaCounterIncrement) ProtoMessage() {}

func (x *ReplicaCounterIncrement) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaCounterIncrement.ProtoReflect.Descriptor instead.
func (*ReplicaCounterIncrement) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{15}
}

func (x *ReplicaCounterIncrement) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

func (x *ReplicaCounterIncrement) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// RestartCounterUpdate is the scheduler/health mutation that bumps the
// per-replica restart counter (INCREMENT) on a failed observation, or
// removes it entirely (RESET) on a healthy observation.
type RestartCounterUpdate struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	ReplicaId     string                      `protobuf:"bytes,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Action        RestartCounterUpdate_Action `protobuf:"varint,2,opt,name=action,proto3,enum=jaco.v1.RestartCounterUpdate_Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartCounterUpdate) Reset() {
	*x = RestartCounterUpdate{}
	mi := &file_jaco_v1_commands_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartCounterUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartCounterUpdate) ProtoMessage() {}

func (x *RestartCounterUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartCounterUpdate.ProtoReflect.Descriptor instead.
func (*RestartCounterUpdate) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{16}
}

func (x *RestartCounterUpdate) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *RestartCounterUpdate) GetAction() RestartCounterUpdate_Action {
	if x != nil {
		return x.Action
	}
	return RestartCounterUpdate_ACTION_UNSPECIFIED
}

type RouteUpsert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *Route                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteUpsert) Reset() {
	*x = RouteUpsert{}
	mi := &file_jaco_v1_commands_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteUpsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteUpsert) ProtoMessage() {}

func (x *RouteUpsert) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteUpsert.ProtoReflect.Descriptor instead.
func (*RouteUpsert) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{17}
}

func (x *RouteUpsert) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type RouteRemove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRemove) Reset() {
	*x = RouteRemove{}
	mi := &file_jaco_v1_commands_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRemove) ProtoMessage() {}

func (x *RouteRemove) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRemove.ProtoReflect.Descriptor instead.
func (*RouteRemove) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{18}
}

func (x *RouteRemove) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type CertStore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertStore) Reset() {
	*x = CertStore{}
	mi := &file_jaco_v1_commands_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertStore) ProtoMessage() {}

func (x *CertStore) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertStore.ProtoReflect.Descriptor instead.
func (*CertStore) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{19}
}

func (x *CertStore) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CertStore) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CertStore) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type CertLock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Lessee        string                 `protobuf:"bytes,2,opt,name=lessee,proto3" json:"lessee,omitempty"`
	Until         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertLock) Reset() {
	*x = CertLock{}
	mi := &file_jaco_v1_commands_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertLock) ProtoMessage() {}

func (x *CertLock) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertLock.ProtoReflect.Descriptor instead.
func (*CertLock) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{20}
}

func (x *CertLock) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CertLock) GetLessee() string {
	if x != nil {
		return x.Lessee
	}
	return ""
}

func (x *CertLock) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

type CertUnlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertUnlock) Reset() {
	*x = CertUnlock{}
	mi := &file_jaco_v1_commands_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertUnlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertUnlock) ProtoMessage() {}

func (x *CertUnlock) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertUnlock.ProtoReflect.Descriptor instead.
func (*CertUnlock) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{21}
}

func (x *CertUnlock) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChallengeTokenStore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *ChallengeToken        `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeTokenStore) Reset() {
	*x = ChallengeTokenStore{}
	mi := &file_jaco_v1_commands_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeTokenStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeTokenStore) ProtoMessage() {}

func (x *ChallengeTokenStore) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeTokenStore.ProtoReflect.Descriptor instead.
func (*ChallengeTokenStore) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{22}
}

func (x *ChallengeTokenStore) GetToken() *ChallengeToken {
	if x != nil {
		return x.Token
	}
	return nil
}

type SubnetAllocate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    string                 `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Network       string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Cidr          string                 `protobuf:"bytes,3,opt,name=cidr,proto3" json:"cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubnetAllocate) Reset() {
	*x = SubnetAllocate{}
	mi := &file_jaco_v1_commands_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubnetAllocate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetAllocate) ProtoMessage() {}

func (x *SubnetAllocate) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubnetAllocate.ProtoReflect.Descriptor instead.
func (*SubnetAllocate) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{23}
}

func (x *SubnetAllocate) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

func (x *SubnetAllocate) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *SubnetAllocate) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

type SubnetFree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    string                 `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Network       string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubnetFree) Reset() {
	*x = SubnetFree{}
	mi := &file_jaco_v1_commands_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubnetFree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetFree) ProtoMessage() {}

func (x *SubnetFree) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubnetFree.ProtoReflect.Descriptor instead.
func (*SubnetFree) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{24}
}

func (x *SubnetFree) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

func (x *SubnetFree) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type TokenIssue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	HashedSecret  []byte                 `protobuf:"bytes,2,opt,name=hashed_secret,json=hashedSecret,proto3" json:"hashed_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenIssue) Reset() {
	*x = TokenIssue{}
	mi := &file_jaco_v1_commands_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenIssue) ProtoMessage() {}

func (x *TokenIssue) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenIssue.ProtoReflect.Descriptor instead.
func (*TokenIssue) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{25}
}

func (x *TokenIssue) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *TokenIssue) GetHashedSecret() []byte {
	if x != nil {
		return x.HashedSecret
	}
	return nil
}

type TokenRevoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRevoke) Reset() {
	*x = TokenRevoke{}
	mi := &file_jaco_v1_commands_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRevoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRevoke) ProtoMessage() {}

func (x *TokenRevoke) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRevoke.ProtoReflect.Descriptor instead.
func (*TokenRevoke) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{26}
}

func (x *TokenRevoke) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type JoinTokenIssue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HashedSecret  []byte                 `protobuf:"bytes,1,opt,name=hashed_secret,json=hashedSecret,proto3" json:"hashed_secret,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinTokenIssue) Reset() {
	*x = JoinTokenIssue{}
	mi := &file_jaco_v1_commands_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinTokenIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTokenIssue) ProtoMessage() {}

func (x *JoinTokenIssue) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTokenIssue.ProtoReflect.Descriptor instead.
func (*JoinTokenIssue) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{27}
}

func (x *JoinTokenIssue) GetHashedSecret() []byte {
	if x != nil {
		return x.HashedSecret
	}
	return nil
}

func (x *JoinTokenIssue) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type JoinTokenConsume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HashedSecret  []byte                 `protobuf:"bytes,1,opt,name=hashed_secret,json=hashedSecret,proto3" json:"hashed_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinTokenConsume) Reset() {
	*x = JoinTokenConsume{}
	mi := &file_jaco_v1_commands_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinTokenConsume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTokenConsume) ProtoMessage() {}

func (x *JoinTokenConsume) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTokenConsume.ProtoReflect.Descriptor instead.
func (*JoinTokenConsume) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{28}
}

func (x *JoinTokenConsume) GetHashedSecret() []byte {
	if x != nil {
		return x.HashedSecret
	}
	return nil
}

type AuditAppend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *AuditEvent            `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditAppend) Reset() {
	*x = AuditAppend{}
	mi := &file_jaco_v1_commands_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditAppend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditAppend) ProtoMessage() {}

func (x *AuditAppend) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_commands_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditAppend.ProtoReflect.Descriptor instead.
func (*AuditAppend) Descriptor() ([]byte, []int) {
	return file_jaco_v1_commands_proto_rawDescGZIP(), []int{29}
}

func (x *AuditAppend) GetEvent() *AuditEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_jaco_v1_commands_proto protoreflect.FileDescriptor

const file_jaco_v1_commands_proto_rawDesc = "" +
	"\n" +
	"\x16jaco/v1/commands.proto\x12\ajaco.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16jaco/v1/entities.proto\"\xf4\x10\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1d\n" +
	"\n" +
	"raft_index\x18\x02 \x01(\x04R\traftIndex\x12*\n" +
	"\x02ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x1a\n" +
	"\bidentity\x18\x04 \x01(\tR\bidentity\x129\n" +
	"\fcluster_init\x18\n" +
	" \x01(\v2\x14.jaco.v1.ClusterInitH\x00R\vclusterInit\x120\n" +
	"\tnode_join\x18\v \x01(\v2\x11.jaco.v1.NodeJoinH\x00R\bnodeJoin\x126\n" +
	"\vnode_remove\x18\f \x01(\v2\x13.jaco.v1.NodeRemoveH\x00R\n" +
	"nodeRemove\x12I\n" +
	"\x12node_status_update\x18\r \x01(\v2\x19.jaco.v1.NodeStatusUpdateH\x00R\x10nodeStatusUpdate\x12E\n" +
	"\x10deployment_apply\x18\x14 \x01(\v2\x18.jaco.v1.DeploymentApplyH\x00R\x0fdeploymentApply\x12N\n" +
	"\x13deployment_rollback\x18\x15 \x01(\v2\x1b.jaco.v1.DeploymentRollbackH\x00R\x12deploymentRollback\x12H\n" +
	"\x11deployment_delete\x18\x16 \x01(\v2\x19.jaco.v1.DeploymentDeleteH\x00R\x10deploymentDelete\x12[\n" +
	"\x18deployment_status_update\x18\x17 \x01(\v2\x1f.jaco.v1.DeploymentStatusUpdateH\x00R\x16deploymentStatusUpdate\x12U\n" +
	"\x16replica_desired_upsert\x18\x1e \x01(\v2\x1d.jaco.v1.ReplicaDesiredUpsertH\x00R\x14replicaDesiredUpsert\x12U\n" +
	"\x16replica_desired_remove\x18\x1f \x01(\v2\x1d.jaco.v1.ReplicaDesiredRemoveH\x00R\x14replicaDesiredRemove\x12X\n" +
	"\x17replica_observed_update\x18  \x01(\v2\x1e.jaco.v1.ReplicaObservedUpdateH\x00R\x15replicaObservedUpdate\x12R\n" +
	"\x15replica_command_issue\x18! \x01(\v2\x1c.jaco.v1.ReplicaCommandIssueH\x00R\x13replicaCommandIssue\x12L\n" +
	"\x13rollout_plan_update\x18\" \x01(\v2\x1a.jaco.v1.RolloutPlanUpdateH\x00R\x11rolloutPlanUpdate\x12^\n" +
	"\x19replica_counter_increment\x18# \x01(\v2 .jaco.v1.ReplicaCounterIncrementH\x00R\x17replicaCounterIncrement\x12U\n" +
	"\x16restart_counter_update\x18$ \x01(\v2\x1d.jaco.v1.RestartCounterUpdateH\x00R\x14restartCounterUpdate\x129\n" +
	"\froute_upsert\x18( \x01(\v2\x14.jaco.v1.RouteUpsertH\x00R\vrouteUpsert\x129\n" +
	"\froute_remove\x18) \x01(\v2\x14.jaco.v1.RouteRemoveH\x00R\vrouteRemove\x123\n" +
	"\n" +
	"cert_store\x182 \x01(\v2\x12.jaco.v1.CertStoreH\x00R\tcertStore\x120\n" +
	"\tcert_lock\x183 \x01(\v2\x11.jaco.v1.CertLockH\x00R\bcertLock\x126\n" +
	"\vcert_unlock\x184 \x01(\v2\x13.jaco.v1.CertUnlockH\x00R\n" +
	"certUnlock\x12R\n" +
	"\x15challenge_token_store\x185 \x01(\v2\x1c.jaco.v1.ChallengeTokenStoreH\x00R\x13challengeTokenStore\x12B\n" +
	"\x0fsubnet_allocate\x18< \x01(\v2\x17.jaco.v1.SubnetAllocateH\x00R\x0esubnetAllocate\x126\n" +
	"\vsubnet_free\x18= \x01(\v2\x13.jaco.v1.SubnetFreeH\x00R\n" +
	"subnetFree\x126\n" +
	"\vtoken_issue\x18F \x01(\v2\x13.jaco.v1.TokenIssueH\x00R\n" +
	"tokenIssue\x129\n" +
	"\ftoken_revoke\x18G \x01(\v2\x14.jaco.v1.TokenRevokeH\x00R\vtokenRevoke\x12C\n" +
	"\x10join_token_issue\x18H \x01(\v2\x17.jaco.v1.JoinTokenIssueH\x00R\x0ejoinTokenIssue\x12I\n" +
	"\x12join_token_consume\x18I \x01(\v2\x19.jaco.v1.JoinTokenConsumeH\x00R\x10joinTokenConsume\x129\n" +
	"\faudit_append\x18P \x01(\v2\x14.jaco.v1.AuditAppendH\x00R\vauditAppend\x12&\n" +
	"\x05batch\x18Z \x01(\v2\x0e.jaco.v1.BatchH\x00R\x05batchB\t\n" +
	"\apayload\"5\n" +
	"\x05Batch\x12,\n" +
	"\bchildren\x18\x01 \x03(\v2\x10.jaco.v1.CommandR\bchildren\"\xe5\x01\n" +
	"\vClusterInit\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x17\n" +
	"\aca_cert\x18\x02 \x01(\fR\x06caCert\x12\x15\n" +
	"\x06ca_key\x18\x03 \x01(\fR\x05caKey\x12?\n" +
	"\x1coperator_token_hashed_secret\x18\x04 \x01(\fR\x19operatorTokenHashedSecret\x12#\n" +
	"\rself_hostname\x18\x05 \x01(\tR\fselfHostname\x12!\n" +
	"\fself_address\x18\x06 \x01(\tR\vselfAddress\"\xc6\x01\n" +
	"\bNodeJoin\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x126\n" +
	"\x17server_cert_fingerprint\x18\x03 \x01(\fR\x15serverCertFingerprint\x12)\n" +
	"\x10wireguard_pubkey\x18\x04 \x01(\fR\x0fwireguardPubkey\x12!\n" +
	"\fgrpc_address\x18\x05 \x01(\tR\vgrpcAddress\"(\n" +
	"\n" +
	"NodeRemove\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"\xd9\x01\n" +
	"\x10NodeStatusUpdate\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.jaco.v1.NodeStatusR\x06status\x12@\n" +
	"\adetails\x18\x03 \x03(\v2&.jaco.v1.NodeStatusUpdate.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe7\x01\n" +
	"\x0fDeploymentApply\x12\x1e\n" +
	"\n" +
	"deployment\x18\x01 \x01(\tR\n" +
	"deployment\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x12\x1b\n" +
	"\tjaco_yaml\x18\x03 \x01(\fR\bjacoYaml\x12!\n" +
	"\fcompose_yaml\x18\x04 \x01(\fR\vcomposeYaml\x120\n" +
	"\bservices\x18\x05 \x03(\v2\x14.jaco.v1.ServiceSpecR\bservices\x12&\n" +
	"\x06routes\x18\x06 \x03(\v2\x0e.jaco.v1.RouteR\x06routes\"P\n" +
	"\x12DeploymentRollback\x12\x1e\n" +
	"\n" +
	"deployment\x18\x01 \x01(\tR\n" +
	"deployment\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\"2\n" +
	"\x10DeploymentDelete\x12\x1e\n" +
	"\n" +
	"deployment\x18\x01 \x01(\tR\n" +
	"deployment\"\xef\x01\n" +
	"\x16DeploymentStatusUpdate\x12\x1e\n" +
	"\n" +
	"deployment\x18\x01 \x01(\tR\n" +
	"deployment\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.jaco.v1.DeploymentStatusR\x06status\x12F\n" +
	"\adetails\x18\x03 \x03(\v2,.jaco.v1.DeploymentStatusUpdate.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\x14ReplicaDesiredUpsert\x121\n" +
	"\areplica\x18\x01 \x01(\v2\x17.jaco.v1.ReplicaDesiredR\areplica\"&\n" +
	"\x14ReplicaDesiredRemove\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x15ReplicaObservedUpdate\x122\n" +
	"\areplica\x18\x01 \x01(\v2\x18.jaco.v1.ReplicaObservedR\areplica\"D\n" +
	"\x13ReplicaCommandIssue\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\tR\treplicaId\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\"=\n" +
	"\x11RolloutPlanUpdate\x12(\n" +
	"\x04plan\x18\x01 \x01(\v2\x14.jaco.v1.RolloutPlanR\x04plan\"S\n" +
	"\x17ReplicaCounterIncrement\x12\x1e\n" +
	"\n" +
	"deployment\x18\x01 \x01(\tR\n" +
	"deployment\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\"\xbd\x01\n" +
	"\x14RestartCounterUpdate\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\tR\treplicaId\x12<\n" +
	"\x06action\x18\x02 \x01(\x0e2$.jaco.v1.RestartCounterUpdate.ActionR\x06action\"H\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ACTION_INCREMENT\x10\x01\x12\x10\n" +
	"\fACTION_RESET\x10\x02\"3\n" +
	"\vRouteUpsert\x12$\n" +
	"\x05route\x18\x01 \x01(\v2\x0e.jaco.v1.RouteR\x05route\"%\n" +
	"\vRouteRemove\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"T\n" +
	"\tCertStore\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"h\n" +
	"\bCertLock\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06lessee\x18\x02 \x01(\tR\x06lessee\x120\n" +
	"\x05until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05until\" \n" +
	"\n" +
	"CertUnlock\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"D\n" +
	"\x13ChallengeTokenStore\x12-\n" +
	"\x05token\x18\x01 \x01(\v2\x17.jaco.v1.ChallengeTokenR\x05token\"^\n" +
	"\x0eSubnetAllocate\x12\x1e\n" +
	"\n" +
	"deployment\x18\x01 \x01(\tR\n" +
	"deployment\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x12\x12\n" +
	"\x04cidr\x18\x03 \x01(\tR\x04cidr\"F\n" +
	"\n" +
	"SubnetFree\x12\x1e\n" +
	"\n" +
	"deployment\x18\x01 \x01(\tR\n" +
	"deployment\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\"M\n" +
	"\n" +
	"TokenIssue\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12#\n" +
	"\rhashed_secret\x18\x02 \x01(\fR\fhashedSecret\")\n" +
	"\vTokenRevoke\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\"p\n" +
	"\x0eJoinTokenIssue\x12#\n" +
	"\rhashed_secret\x18\x01 \x01(\fR\fhashedSecret\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"7\n" +
	"\x10JoinTokenConsume\x12#\n" +
	"\rhashed_secret\x18\x01 \x01(\fR\fhashedSecret\"8\n" +
	"\vAuditAppend\x12)\n" +
	"\x05event\x18\x01 \x01(\v2\x13.jaco.v1.AuditEventR\x05eventB:Z8github.com/PatrickRuddiman/jaco/pkg/proto/jaco/v1;jacov1b\x06proto3"

var (
	file_jaco_v1_commands_proto_rawDescOnce sync.Once
	file_jaco_v1_commands_proto_rawDescData []byte
)

func file_jaco_v1_commands_proto_rawDescGZIP() []byte {
	file_jaco_v1_commands_proto_rawDescOnce.Do(func() {
		file_jaco_v1_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jaco_v1_commands_proto_rawDesc), len(file_jaco_v1_commands_proto_rawDesc)))
	})
	return file_jaco_v1_commands_proto_rawDescData
}

var file_jaco_v1_commands_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jaco_v1_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_jaco_v1_commands_proto_goTypes = []any{
	(RestartCounterUpdate_Action)(0), // 0: jaco.v1.RestartCounterUpdate.Action
	(*Command)(nil),                  // 1: jaco.v1.Command
	(*Batch)(nil),                    // 2: jaco.v1.Batch
	(*ClusterInit)(nil),              // 3: jaco.v1.ClusterInit
	(*NodeJoin)(nil),                 // 4: jaco.v1.NodeJoin
	(*NodeRemove)(nil),               // 5: jaco.v1.NodeRemove
	(*NodeStatusUpdate)(nil),         // 6: jaco.v1.NodeStatusUpdate
	(*DeploymentApply)(nil),          // 7: jaco.v1.DeploymentApply
	(*DeploymentRollback)(nil),       // 8: jaco.v1.DeploymentRollback
	(*DeploymentDelete)(nil),         // 9: jaco.v1.DeploymentDelete
	(*DeploymentStatusUpdate)(nil),   // 10: jaco.v1.DeploymentStatusUpdate
	(*ReplicaDesiredUpsert)(nil),     // 11: jaco.v1.ReplicaDesiredUpsert
	(*ReplicaDesiredRemove)(nil),     // 12: jaco.v1.ReplicaDesiredRemove
	(*ReplicaObservedUpdate)(nil),    // 13: jaco.v1.ReplicaObservedUpdate
	(*ReplicaCommandIssue)(nil),      // 14: jaco.v1.ReplicaCommandIssue
	(*RolloutPlanUpdate)(nil),        // 15: jaco.v1.RolloutPlanUpdate
	(*ReplicaCounterIncrement)(nil),  // 16: jaco.v1.ReplicaCounterIncrement
	(*RestartCounterUpdate)(nil),     // 17: jaco.v1.RestartCounterUpdate
	(*RouteUpsert)(nil),              // 18: jaco.v1.RouteUpsert
	(*RouteRemove)(nil),              // 19: jaco.v1.RouteRemove
	(*CertStore)(nil),                // 20: jaco.v1.CertStore
	(*CertLock)(nil),                 // 21: jaco.v1.CertLock
	(*CertUnlock)(nil),               // 22: jaco.v1.CertUnlock
	(*ChallengeTokenStore)(nil),      // 23: jaco.v1.ChallengeTokenStore
	(*SubnetAllocate)(nil),           // 24: jaco.v1.SubnetAllocate
	(*SubnetFree)(nil),               // 25: jaco.v1.SubnetFree
	(*TokenIssue)(nil),               // 26: jaco.v1.TokenIssue
	(*TokenRevoke)(nil),              // 27: jaco.v1.TokenRevoke
	(*JoinTokenIssue)(nil),           // 28: jaco.v1.JoinTokenIssue
	(*JoinTokenConsume)(nil),         // 29: jaco.v1.JoinTokenConsume
	(*AuditAppend)(nil),              // 30: jaco.v1.AuditAppend
	nil,                              // 31: jaco.v1.NodeStatusUpdate.DetailsEntry
	nil,                              // 32: jaco.v1.DeploymentStatusUpdate.DetailsEntry
	(*timestamppb.Timestamp)(nil),    // 33: google.protobuf.Timestamp
	(NodeStatus)(0),                  // 34: jaco.v1.NodeStatus
	(*ServiceSpec)(nil),              // 35: jaco.v1.ServiceSpec
	(*Route)(nil),                    // 36: jaco.v1.Route
	(DeploymentStatus)(0),            // 37: jaco.v1.DeploymentStatus
	(*ReplicaDesired)(nil),           // 38: jaco.v1.ReplicaDesired
	(*ReplicaObserved)(nil),          // 39: jaco.v1.ReplicaObserved
	(*RolloutPlan)(nil),              // 40: jaco.v1.RolloutPlan
	(*ChallengeToken)(nil),           // 41: jaco.v1.ChallengeToken
	(*AuditEvent)(nil),               // 42: jaco.v1.AuditEvent
}
var file_jaco_v1_commands_proto_depIdxs = []int32{
	33, // 0: jaco.v1.Command.ts:type_name -> google.protobuf.Timestamp
	3,  // 1: jaco.v1.Command.cluster_init:type_name -> jaco.v1.ClusterInit
	4,  // 2: jaco.v1.Command.node_join:type_name -> jaco.v1.NodeJoin
	5,  // 3: jaco.v1.Command.node_remove:type_name -> jaco.v1.NodeRemove
	6,  // 4: jaco.v1.Command.node_status_update:type_name -> jaco.v1.NodeStatusUpdate
	7,  // 5: jaco.v1.Command.deployment_apply:type_name -> jaco.v1.DeploymentApply
	8,  // 6: jaco.v1.Command.deployment_rollback:type_name -> jaco.v1.DeploymentRollback
	9,  // 7: jaco.v1.Command.deployment_delete:type_name -> jaco.v1.DeploymentDelete
	10, // 8: jaco.v1.Command.deployment_status_update:type_name -> jaco.v1.DeploymentStatusUpdate
	11, // 9: jaco.v1.Command.replica_desired_upsert:type_name -> jaco.v1.ReplicaDesiredUpsert
	12, // 10: jaco.v1.Command.replica_desired_remove:type_name -> jaco.v1.ReplicaDesiredRemove
	13, // 11: jaco.v1.Command.replica_observed_update:type_name -> jaco.v1.ReplicaObservedUpdate
	14, // 12: jaco.v1.Command.replica_command_issue:type_name -> jaco.v1.ReplicaCommandIssue
	15, // 13: jaco.v1.Command.rollout_plan_update:type_name -> jaco.v1.RolloutPlanUpdate
	16, // 14: jaco.v1.Command.replica_counter_increment:type_name -> jaco.v1.ReplicaCounterIncrement
	17, // 15: jaco.v1.Command.restart_counter_update:type_name -> jaco.v1.RestartCounterUpdate
	18, // 16: jaco.v1.Command.route_upsert:type_name -> jaco.v1.RouteUpsert
	19, // 17: jaco.v1.Command.route_remove:type_name -> jaco.v1.RouteRemove
	20, // 18: jaco.v1.Command.cert_store:type_name -> jaco.v1.CertStore
	21, // 19: jaco.v1.Command.cert_lock:type_name -> jaco.v1.CertLock
	22, // 20: jaco.v1.Command.cert_unlock:type_name -> jaco.v1.CertUnlock
	23, // 21: jaco.v1.Command.challenge_token_store:type_name -> jaco.v1.ChallengeTokenStore
	24, // 22: jaco.v1.Command.subnet_allocate:type_name -> jaco.v1.SubnetAllocate
	25, // 23: jaco.v1.Command.subnet_free:type_name -> jaco.v1.SubnetFree
	26, // 24: jaco.v1.Command.token_issue:type_name -> jaco.v1.TokenIssue
	27, // 25: jaco.v1.Command.token_revoke:type_name -> jaco.v1.TokenRevoke
	28, // 26: jaco.v1.Command.join_token_issue:type_name -> jaco.v1.JoinTokenIssue
	29, // 27: jaco.v1.Command.join_token_consume:type_name -> jaco.v1.JoinTokenConsume
	30, // 28: jaco.v1.Command.audit_append:type_name -> jaco.v1.AuditAppend
	2,  // 29: jaco.v1.Command.batch:type_name -> jaco.v1.Batch
	1,  // 30: jaco.v1.Batch.children:type_name -> jaco.v1.Command
	34, // 31: jaco.v1.NodeStatusUpdate.status:type_name -> jaco.v1.NodeStatus
	31, // 32: jaco.v1.NodeStatusUpdate.details:type_name -> jaco.v1.NodeStatusUpdate.DetailsEntry
	35, // 33: jaco.v1.DeploymentApply.services:type_name -> jaco.v1.ServiceSpec
	36, // 34: jaco.v1.DeploymentApply.routes:type_name -> jaco.v1.Route
	37, // 35: jaco.v1.DeploymentStatusUpdate.status:type_name -> jaco.v1.DeploymentStatus
	32, // 36: jaco.v1.DeploymentStatusUpdate.details:type_name -> jaco.v1.DeploymentStatusUpdate.DetailsEntry
	38, // 37: jaco.v1.ReplicaDesiredUpsert.replica:type_name -> jaco.v1.ReplicaDesired
	39, // 38: jaco.v1.ReplicaObservedUpdate.replica:type_name -> jaco.v1.ReplicaObserved
	40, // 39: jaco.v1.RolloutPlanUpdate.plan:type_name -> jaco.v1.RolloutPlan
	0,  // 40: jaco.v1.RestartCounterUpdate.action:type_name -> jaco.v1.RestartCounterUpdate.Action
	36, // 41: jaco.v1.RouteUpsert.route:type_name -> jaco.v1.Route
	33, // 42: jaco.v1.CertLock.until:type_name -> google.protobuf.Timestamp
	41, // 43: jaco.v1.ChallengeTokenStore.token:type_name -> jaco.v1.ChallengeToken
	33, // 44: jaco.v1.JoinTokenIssue.expires_at:type_name -> google.protobuf.Timestamp
	42, // 45: jaco.v1.AuditAppend.event:type_name -> jaco.v1.AuditEvent
	46, // [46:46] is the sub-list for method output_type
	46, // [46:46] is the sub-list for method input_type
	46, // [46:46] is the sub-list for extension type_name
	46, // [46:46] is the sub-list for extension extendee
	0,  // [0:46] is the sub-list for field type_name
}

func init() { file_jaco_v1_commands_proto_init() }
func file_jaco_v1_commands_proto_init() {
	if File_jaco_v1_commands_proto != nil {
		return
	}
	file_jaco_v1_entities_proto_init()
	file_jaco_v1_commands_proto_msgTypes[0].OneofWrappers = []any{
		(*Command_ClusterInit)(nil),
		(*Command_NodeJoin)(nil),
		(*Command_NodeRemove)(nil),
		(*Command_NodeStatusUpdate)(nil),
		(*Command_DeploymentApply)(nil),
		(*Command_DeploymentRollback)(nil),
		(*Command_DeploymentDelete)(nil),
		(*Command_DeploymentStatusUpdate)(nil),
		(*Command_ReplicaDesiredUpsert)(nil),
		(*Command_ReplicaDesiredRemove)(nil),
		(*Command_ReplicaObservedUpdate)(nil),
		(*Command_ReplicaCommandIssue)(nil),
		(*Command_RolloutPlanUpdate)(nil),
		(*Command_ReplicaCounterIncrement)(nil),
		(*Command_RestartCounterUpdate)(nil),
		(*Command_RouteUpsert)(nil),
		(*Command_RouteRemove)(nil),
		(*Command_CertStore)(nil),
		(*Command_CertLock)(nil),
		(*Command_CertUnlock)(nil),
		(*Command_ChallengeTokenStore)(nil),
		(*Command_SubnetAllocate)(nil),
		(*Command_SubnetFree)(nil),
		(*Command_TokenIssue)(nil),
		(*Command_TokenRevoke)(nil),
		(*Command_JoinTokenIssue)(nil),
		(*Command_JoinTokenConsume)(nil),
		(*Command_AuditAppend)(nil),
		(*Command_Batch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jaco_v1_commands_proto_rawDesc), len(file_jaco_v1_commands_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jaco_v1_commands_proto_goTypes,
		DependencyIndexes: file_jaco_v1_commands_proto_depIdxs,
		EnumInfos:         file_jaco_v1_commands_proto_enumTypes,
		MessageInfos:      file_jaco_v1_commands_proto_msgTypes,
	}.Build()
	File_jaco_v1_commands_proto = out.File
	file_jaco_v1_commands_proto_goTypes = nil
	file_jaco_v1_commands_proto_depIdxs = nil
}
