// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jaco/v1/entities.proto

package jacov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplicaState int32

const (
	ReplicaState_REPLICA_STATE_UNSPECIFIED ReplicaState = 0
	ReplicaState_REPLICA_STATE_PENDING     ReplicaState = 1
	ReplicaState_REPLICA_STATE_PULLING     ReplicaState = 2
	ReplicaState_REPLICA_STATE_RUNNING     ReplicaState = 3
	ReplicaState_REPLICA_STATE_DEGRADED    ReplicaState = 4
	ReplicaState_REPLICA_STATE_UPDATING    ReplicaState = 5
	ReplicaState_REPLICA_STATE_FAILED      ReplicaState = 6
	ReplicaState_REPLICA_STATE_STOPPED     ReplicaState = 7
)

// Enum value maps for ReplicaState.
var (
	ReplicaState_name = map[int32]string{
		0: "REPLICA_STATE_UNSPECIFIED",
		1: "REPLICA_STATE_PENDING",
		2: "REPLICA_STATE_PULLING",
		3: "REPLICA_STATE_RUNNING",
		4: "REPLICA_STATE_DEGRADED",
		5: "REPLICA_STATE_UPDATING",
		6: "REPLICA_STATE_FAILED",
		7: "REPLICA_STATE_STOPPED",
	}
	ReplicaState_value = map[string]int32{
		"REPLICA_STATE_UNSPECIFIED": 0,
		"REPLICA_STATE_PENDING":     1,
		"REPLICA_STATE_PULLING":     2,
		"REPLICA_STATE_RUNNING":     3,
		"REPLICA_STATE_DEGRADED":    4,
		"REPLICA_STATE_UPDATING":    5,
		"REPLICA_STATE_FAILED":      6,
		"REPLICA_STATE_STOPPED":     7,
	}
)

func (x ReplicaState) Enum() *ReplicaState {
	p := new(ReplicaState)
	*p = x
	return p
}

func (x ReplicaState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReplicaState) Descriptor() protoreflect.EnumDescriptor {
	return file_jaco_v1_entities_proto_enumTypes[0].Descriptor()
}

func (ReplicaState) Type() protoreflect.EnumType {
	return &file_jaco_v1_entities_proto_enumTypes[0]
}

func (x ReplicaState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReplicaState.Descriptor instead.
func (ReplicaState) EnumDescriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{0}
}

type RolloutState int32

const (
	RolloutState_ROLLOUT_STATE_UNSPECIFIED RolloutState = 0
	RolloutState_ROLLOUT_STATE_IN_PROGRESS RolloutState = 1
	RolloutState_ROLLOUT_STATE_COMPLETED   RolloutState = 2
	RolloutState_ROLLOUT_STATE_ABORTED     RolloutState = 3
)

// Enum value maps for RolloutState.
var (
	RolloutState_name = map[int32]string{
		0: "ROLLOUT_STATE_UNSPECIFIED",
		1: "ROLLOUT_STATE_IN_PROGRESS",
		2: "ROLLOUT_STATE_COMPLETED",
		3: "ROLLOUT_STATE_ABORTED",
	}
	RolloutState_value = map[string]int32{
		"ROLLOUT_STATE_UNSPECIFIED": 0,
		"ROLLOUT_STATE_IN_PROGRESS": 1,
		"ROLLOUT_STATE_COMPLETED":   2,
		"ROLLOUT_STATE_ABORTED":     3,
	}
)

func (x RolloutState) Enum() *RolloutState {
	p := new(RolloutState)
	*p = x
	return p
}

func (x RolloutState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RolloutState) Descriptor() protoreflect.EnumDescriptor {
	return file_jaco_v1_entities_proto_enumTypes[1].Descriptor()
}

func (RolloutState) Type() protoreflect.EnumType {
	return &file_jaco_v1_entities_proto_enumTypes[1]
}

func (x RolloutState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RolloutState.Descriptor instead.
func (RolloutState) EnumDescriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{1}
}

type NodeStatus int32

const (
	NodeStatus_NODE_STATUS_UNSPECIFIED           NodeStatus = 0
	NodeStatus_NODE_STATUS_JOINING               NodeStatus = 1
	NodeStatus_NODE_STATUS_READY                 NodeStatus = 2
	NodeStatus_NODE_STATUS_ISOLATION_UNAVAILABLE NodeStatus = 3
	NodeStatus_NODE_STATUS_DRAIN_TIMEOUT         NodeStatus = 4
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_UNSPECIFIED",
		1: "NODE_STATUS_JOINING",
		2: "NODE_STATUS_READY",
		3: "NODE_STATUS_ISOLATION_UNAVAILABLE",
		4: "NODE_STATUS_DRAIN_TIMEOUT",
	}
	NodeStatus_value = map[string]int32{
		"NODE_STATUS_UNSPECIFIED":           0,
		"NODE_STATUS_JOINING":               1,
		"NODE_STATUS_READY":                 2,
		"NODE_STATUS_ISOLATION_UNAVAILABLE": 3,
		"NODE_STATUS_DRAIN_TIMEOUT":         4,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_jaco_v1_entities_proto_enumTypes[2].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_jaco_v1_entities_proto_enumTypes[2]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{2}
}

type DeploymentStatus int32

const (
	DeploymentStatus_DEPLOYMENT_STATUS_UNSPECIFIED DeploymentStatus = 0
	DeploymentStatus_DEPLOYMENT_STATUS_PENDING     DeploymentStatus = 1
	DeploymentStatus_DEPLOYMENT_STATUS_ACTIVE      DeploymentStatus = 2
)

// Enum value maps for DeploymentStatus.
var (
	DeploymentStatus_name = map[int32]string{
		0: "DEPLOYMENT_STATUS_UNSPECIFIED",
		1: "DEPLOYMENT_STATUS_PENDING",
		2: "DEPLOYMENT_STATUS_ACTIVE",
	}
	DeploymentStatus_value = map[string]int32{
		"DEPLOYMENT_STATUS_UNSPECIFIED": 0,
		"DEPLOYMENT_STATUS_PENDING":     1,
		"DEPLOYMENT_STATUS_ACTIVE":      2,
	}
)

func (x DeploymentStatus) Enum() *DeploymentStatus {
	p := new(DeploymentStatus)
	*p = x
	return p
}

func (x DeploymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeploymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_jaco_v1_entities_proto_enumTypes[3].Descriptor()
}

func (DeploymentStatus) Type() protoreflect.EnumType {
	return &file_jaco_v1_entities_proto_enumTypes[3]
}

func (x DeploymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeploymentStatus.Descriptor instead.
func (DeploymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{3}
}

type AuditEventType int32

const (
	AuditEventType_AUDIT_EVENT_TYPE_UNSPECIFIED                  AuditEventType = 0
	AuditEventType_AUDIT_EVENT_TYPE_APPLY                        AuditEventType = 1
	AuditEventType_AUDIT_EVENT_TYPE_DELETE                       AuditEventType = 2
	AuditEventType_AUDIT_EVENT_TYPE_ROLLBACK                     AuditEventType = 3
	AuditEventType_AUDIT_EVENT_TYPE_NODE_JOIN                    AuditEventType = 4
	AuditEventType_AUDIT_EVENT_TYPE_NODE_REMOVE                  AuditEventType = 5
	AuditEventType_AUDIT_EVENT_TYPE_TOKEN_ISSUE                  AuditEventType = 6
	AuditEventType_AUDIT_EVENT_TYPE_TOKEN_REVOKE                 AuditEventType = 7
	AuditEventType_AUDIT_EVENT_TYPE_CERTIFICATE_ISSUED           AuditEventType = 8
	AuditEventType_AUDIT_EVENT_TYPE_CERTIFICATE_RENEWED          AuditEventType = 9
	AuditEventType_AUDIT_EVENT_TYPE_CERTIFICATE_FAILED           AuditEventType = 10
	AuditEventType_AUDIT_EVENT_TYPE_ISOLATION_RULESET_RECONCILED AuditEventType = 11
	AuditEventType_AUDIT_EVENT_TYPE_ISOLATION_UNAVAILABLE        AuditEventType = 12
	AuditEventType_AUDIT_EVENT_TYPE_BACKUP_TAKEN                 AuditEventType = 13
	AuditEventType_AUDIT_EVENT_TYPE_RESTORE_COMPLETED            AuditEventType = 14
	AuditEventType_AUDIT_EVENT_TYPE_UPGRADE_SUCCEEDED            AuditEventType = 15
	AuditEventType_AUDIT_EVENT_TYPE_UPGRADE_FAILED               AuditEventType = 16
	AuditEventType_AUDIT_EVENT_TYPE_ROLLOUT_INVARIANT_HOLD       AuditEventType = 17
	AuditEventType_AUDIT_EVENT_TYPE_REGISTRY_CREDENTIAL_UPSERT   AuditEventType = 18
	AuditEventType_AUDIT_EVENT_TYPE_REGISTRY_CREDENTIAL_REMOVE   AuditEventType = 19
	// Privileged workload admitted by Apply (issue #119): emitted exactly
	// once per admitted manifest that carries `privileged:` or
	// `security_opt:`. Payload: deployment, service, identity (token id),
	// fields (csv of which fields were set on the service).
	AuditEventType_AUDIT_EVENT_TYPE_PRIVILEGED_WORKLOAD_ADMITTED AuditEventType = 20
	// Rebalance decisions emitted by internal/scheduler/rebalance (issue
	// #92, ADR 0002). Payload shape:
	//
	//	replica_id, deployment, service, src, dst,
	//	relief, dominant (cpu|memory),
	//	src_pressure_before, dst_pressure_before,
	//	src_pressure_after, dst_pressure_after,
	//	move_cost, score,
	//	reason (only on SKIPPED: cooldown_replica | cooldown_node |
	//	        no_eligible_dst | dst_cap | relief_floor |
	//	        resource_limits | anti_affinity | no_candidate).
	AuditEventType_AUDIT_EVENT_TYPE_REBALANCE_MOVED   AuditEventType = 21
	AuditEventType_AUDIT_EVENT_TYPE_REBALANCE_SKIPPED AuditEventType = 23
)

// Enum value maps for AuditEventType.
var (
	AuditEventType_name = map[int32]string{
		0:  "AUDIT_EVENT_TYPE_UNSPECIFIED",
		1:  "AUDIT_EVENT_TYPE_APPLY",
		2:  "AUDIT_EVENT_TYPE_DELETE",
		3:  "AUDIT_EVENT_TYPE_ROLLBACK",
		4:  "AUDIT_EVENT_TYPE_NODE_JOIN",
		5:  "AUDIT_EVENT_TYPE_NODE_REMOVE",
		6:  "AUDIT_EVENT_TYPE_TOKEN_ISSUE",
		7:  "AUDIT_EVENT_TYPE_TOKEN_REVOKE",
		8:  "AUDIT_EVENT_TYPE_CERTIFICATE_ISSUED",
		9:  "AUDIT_EVENT_TYPE_CERTIFICATE_RENEWED",
		10: "AUDIT_EVENT_TYPE_CERTIFICATE_FAILED",
		11: "AUDIT_EVENT_TYPE_ISOLATION_RULESET_RECONCILED",
		12: "AUDIT_EVENT_TYPE_ISOLATION_UNAVAILABLE",
		13: "AUDIT_EVENT_TYPE_BACKUP_TAKEN",
		14: "AUDIT_EVENT_TYPE_RESTORE_COMPLETED",
		15: "AUDIT_EVENT_TYPE_UPGRADE_SUCCEEDED",
		16: "AUDIT_EVENT_TYPE_UPGRADE_FAILED",
		17: "AUDIT_EVENT_TYPE_ROLLOUT_INVARIANT_HOLD",
		18: "AUDIT_EVENT_TYPE_REGISTRY_CREDENTIAL_UPSERT",
		19: "AUDIT_EVENT_TYPE_REGISTRY_CREDENTIAL_REMOVE",
		20: "AUDIT_EVENT_TYPE_PRIVILEGED_WORKLOAD_ADMITTED",
		21: "AUDIT_EVENT_TYPE_REBALANCE_MOVED",
		23: "AUDIT_EVENT_TYPE_REBALANCE_SKIPPED",
	}
	AuditEventType_value = map[string]int32{
		"AUDIT_EVENT_TYPE_UNSPECIFIED":                  0,
		"AUDIT_EVENT_TYPE_APPLY":                        1,
		"AUDIT_EVENT_TYPE_DELETE":                       2,
		"AUDIT_EVENT_TYPE_ROLLBACK":                     3,
		"AUDIT_EVENT_TYPE_NODE_JOIN":                    4,
		"AUDIT_EVENT_TYPE_NODE_REMOVE":                  5,
		"AUDIT_EVENT_TYPE_TOKEN_ISSUE":                  6,
		"AUDIT_EVENT_TYPE_TOKEN_REVOKE":                 7,
		"AUDIT_EVENT_TYPE_CERTIFICATE_ISSUED":           8,
		"AUDIT_EVENT_TYPE_CERTIFICATE_RENEWED":          9,
		"AUDIT_EVENT_TYPE_CERTIFICATE_FAILED":           10,
		"AUDIT_EVENT_TYPE_ISOLATION_RULESET_RECONCILED": 11,
		"AUDIT_EVENT_TYPE_ISOLATION_UNAVAILABLE":        12,
		"AUDIT_EVENT_TYPE_BACKUP_TAKEN":                 13,
		"AUDIT_EVENT_TYPE_RESTORE_COMPLETED":            14,
		"AUDIT_EVENT_TYPE_UPGRADE_SUCCEEDED":            15,
		"AUDIT_EVENT_TYPE_UPGRADE_FAILED":               16,
		"AUDIT_EVENT_TYPE_ROLLOUT_INVARIANT_HOLD":       17,
		"AUDIT_EVENT_TYPE_REGISTRY_CREDENTIAL_UPSERT":   18,
		"AUDIT_EVENT_TYPE_REGISTRY_CREDENTIAL_REMOVE":   19,
		"AUDIT_EVENT_TYPE_PRIVILEGED_WORKLOAD_ADMITTED": 20,
		"AUDIT_EVENT_TYPE_REBALANCE_MOVED":              21,
		"AUDIT_EVENT_TYPE_REBALANCE_SKIPPED":            23,
	}
)

func (x AuditEventType) Enum() *AuditEventType {
	p := new(AuditEventType)
	*p = x
	return p
}

func (x AuditEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_jaco_v1_entities_proto_enumTypes[4].Descriptor()
}

func (AuditEventType) Type() protoreflect.EnumType {
	return &file_jaco_v1_entities_proto_enumTypes[4]
}

func (x AuditEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditEventType.Descriptor instead.
func (AuditEventType) EnumDescriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{4}
}

type ServiceSpec_PlacementMode int32

const (
	ServiceSpec_PLACEMENT_MODE_UNSPECIFIED ServiceSpec_PlacementMode = 0
	ServiceSpec_PLACEMENT_MODE_SPREAD      ServiceSpec_PlacementMode = 1
	ServiceSpec_PLACEMENT_MODE_PACK        ServiceSpec_PlacementMode = 2
	ServiceSpec_PLACEMENT_MODE_HOSTS       ServiceSpec_PlacementMode = 3
	ServiceSpec_PLACEMENT_MODE_GLOBAL      ServiceSpec_PlacementMode = 4
)

// Enum value maps for ServiceSpec_PlacementMode.
var (
	ServiceSpec_PlacementMode_name = map[int32]string{
		0: "PLACEMENT_MODE_UNSPECIFIED",
		1: "PLACEMENT_MODE_SPREAD",
		2: "PLACEMENT_MODE_PACK",
		3: "PLACEMENT_MODE_HOSTS",
		4: "PLACEMENT_MODE_GLOBAL",
	}
	ServiceSpec_PlacementMode_value = map[string]int32{
		"PLACEMENT_MODE_UNSPECIFIED": 0,
		"PLACEMENT_MODE_SPREAD":      1,
		"PLACEMENT_MODE_PACK":        2,
		"PLACEMENT_MODE_HOSTS":       3,
		"PLACEMENT_MODE_GLOBAL":      4,
	}
)

func (x ServiceSpec_PlacementMode) Enum() *ServiceSpec_PlacementMode {
	p := new(ServiceSpec_PlacementMode)
	*p = x
	return p
}

func (x ServiceSpec_PlacementMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceSpec_PlacementMode) Descriptor() protoreflect.EnumDescriptor {
	return file_jaco_v1_entities_proto_enumTypes[5].Descriptor()
}

func (ServiceSpec_PlacementMode) Type() protoreflect.EnumType {
	return &file_jaco_v1_entities_proto_enumTypes[5]
}

func (x ServiceSpec_PlacementMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceSpec_PlacementMode.Descriptor instead.
func (ServiceSpec_PlacementMode) EnumDescriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{2, 0}
}

type ClusterMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	CaCert        []byte                 `protobuf:"bytes,2,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	CaKey         []byte                 `protobuf:"bytes,3,opt,name=ca_key,json=caKey,proto3" json:"ca_key,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMeta) Reset() {
	*x = ClusterMeta{}
	mi := &file_jaco_v1_entities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMeta) ProtoMessage() {}

func (x *ClusterMeta) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_entities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMeta.ProtoReflect.Descriptor instead.
func (*ClusterMeta) Descriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterMeta) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ClusterMeta) GetCaCert() []byte {
	if x != nil {
		return x.CaCert
	}
	return nil
}

func (x *ClusterMeta) GetCaKey() []byte {
	if x != nil {
		return x.CaKey
	}
	return nil
}

func (x *ClusterMeta) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Node struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Hostname              string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Address               string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	ServerCertFingerprint []byte                 `protobuf:"bytes,3,opt,name=server_cert_fingerprint,json=serverCertFingerprint,proto3" json:"server_cert_fingerprint,omitempty"`
	WireguardPubkey       []byte                 `protobuf:"bytes,4,opt,name=wireguard_pubkey,json=wireguardPubkey,proto3" json:"wireguard_pubkey,omitempty"`
	Status                NodeStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=jaco.v1.NodeStatus" json:"status,omitempty"`
	StatusDetails         map[string]string      `protobuf:"bytes,6,rep,name=status_details,json=statusDetails,proto3" json:"status_details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	JoinedAt              *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	// grpc_address is the host:port of this node's cross-host gRPC
	// listener (cfg.ListenAddr). Distinct from `address` (which is the
	// raft transport addr). Followers dial this via Internal.Submit to
	// forward ReplicaObserved updates to the leader.
	GrpcAddress string `protobuf:"bytes,8,opt,name=grpc_address,json=grpcAddress,proto3" json:"grpc_address,omitempty"`
	// cpu_pressure / memory_pressure are the latest gossiped
	// utilisation samples for this node, in [0, 1]. Updated by the
	// periodic NodeStatusUpdate heartbeat from the node itself.
	// Consumed by the rebalancer (#92) on the leader. Use
	// last_pressure_at as the freshness gate — zero values are
	// indistinguishable from "node idle", so the rebalancer's
	// state-backed source rejects samples older than 3× the
	// configured heartbeat interval.
	CpuPressure    float64                `protobuf:"fixed64,9,opt,name=cpu_pressure,json=cpuPressure,proto3" json:"cpu_pressure,omitempty"`
	MemoryPressure float64                `protobuf:"fixed64,10,opt,name=memory_pressure,json=memoryPressure,proto3" json:"memory_pressure,omitempty"`
	LastPressureAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_pressure_at,json=lastPressureAt,proto3" json:"last_pressure_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_jaco_v1_entities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_entities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Node) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Node) GetServerCertFingerprint() []byte {
	if x != nil {
		return x.ServerCertFingerprint
	}
	return nil
}

func (x *Node) GetWireguardPubkey() []byte {
	if x != nil {
		return x.WireguardPubkey
	}
	return nil
}

func (x *Node) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *Node) GetStatusDetails() map[string]string {
	if x != nil {
		return x.StatusDetails
	}
	return nil
}

func (x *Node) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *Node) GetGrpcAddress() string {
	if x != nil {
		return x.GrpcAddress
	}
	return ""
}

func (x *Node) GetCpuPressure() float64 {
	if x != nil {
		return x.CpuPressure
	}
	return 0
}

func (x *Node) GetMemoryPressure() float64 {
	if x != nil {
		return x.MemoryPressure
	}
	return 0
}

func (x *Node) GetLastPressureAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPressureAt
	}
	return nil
}

type ServiceSpec struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Name          string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Replicas      int32                     `protobuf:"varint,2,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Placement     ServiceSpec_PlacementMode `protobuf:"varint,3,opt,name=placement,proto3,enum=jaco.v1.ServiceSpec_PlacementMode" json:"placement,omitempty"`
	Hosts         []string                  `protobuf:"bytes,4,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Networks      []string                  `protobuf:"bytes,6,rep,name=networks,proto3" json:"networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceSpec) Reset() {
	*x = ServiceSpec{}
	mi := &file_jaco_v1_entities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceSpec) ProtoMessage() {}

func (x *ServiceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_entities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceSpec.ProtoReflect.Descriptor instead.
func (*ServiceSpec) Descriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceSpec) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *ServiceSpec) GetPlacement() ServiceSpec_PlacementMode {
	if x != nil {
		return x.Placement
	}
	return ServiceSpec_PLACEMENT_MODE_UNSPECIFIED
}

func (x *ServiceSpec) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *ServiceSpec) GetNetworks() []string {
	if x != nil {
		return x.Networks
	}
	return nil
}

type Deployment struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AppliedRevision  uint64                 `protobuf:"varint,2,opt,name=applied_revision,json=appliedRevision,proto3" json:"applied_revision,omitempty"`
	PreviousRevision uint64                 `protobuf:"varint,3,opt,name=previous_revision,json=previousRevision,proto3" json:"previous_revision,omitempty"`
	Status           DeploymentStatus       `protobuf:"varint,4,opt,name=status,proto3,enum=jaco.v1.DeploymentStatus" json:"status,omitempty"`
	StatusDetails    map[string]string      `protobuf:"bytes,5,rep,name=status_details,json=statusDetails,proto3" json:"status_details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	JacoYaml         []byte                 `protobuf:"bytes,6,opt,name=jaco_yaml,json=jacoYaml,proto3" json:"jaco_yaml,omitempty"`
	ComposeYaml      []byte                 `protobuf:"bytes,7,opt,name=compose_yaml,json=composeYaml,proto3" json:"compose_yaml,omitempty"`
	Services         []*ServiceSpec         `protobuf:"bytes,8,rep,name=services,proto3" json:"services,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// acme_email is this deployment's ACME (Let's Encrypt) contact address,
	// sourced from the top-level `acme_email:` field in the stack's
	// jaco.yaml. Empty = fall back to the cluster-wide jacod.yaml
	// `acme_email`. Each unique non-empty value yields its own Caddy
	// automation policy (separate ACME account / contact). See #102.
	AcmeEmail     string `protobuf:"bytes,10,opt,name=acme_email,json=acmeEmail,proto3" json:"acme_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_jaco_v1_entities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_entities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{3}
}

func (x *Deployment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Deployment) GetAppliedRevision() uint64 {
	if x != nil {
		return x.AppliedRevision
	}
	return 0
}

func (x *Deployment) GetPreviousRevision() uint64 {
	if x != nil {
		return x.PreviousRevision
	}
	return 0
}

func (x *Deployment) GetStatus() DeploymentStatus {
	if x != nil {
		return x.Status
	}
	return DeploymentStatus_DEPLOYMENT_STATUS_UNSPECIFIED
}

func (x *Deployment) GetStatusDetails() map[string]string {
	if x != nil {
		return x.StatusDetails
	}
	return nil
}

func (x *Deployment) GetJacoYaml() []byte {
	if x != nil {
		return x.JacoYaml
	}
	return nil
}

func (x *Deployment) GetComposeYaml() []byte {
	if x != nil {
		return x.ComposeYaml
	}
	return nil
}

func (x *Deployment) GetServices() []*ServiceSpec {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Deployment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Deployment) GetAcmeEmail() string {
	if x != nil {
		return x.AcmeEmail
	}
	return ""
}

type ReplicaDesired struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Deployment    string                 `protobuf:"bytes,2,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Index         int32                  `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	Host          string                 `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	Image         string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	RaftIndex     uint64                 `protobuf:"varint,7,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaDesired) Reset() {
	*x = ReplicaDesired{}
	mi := &file_jaco_v1_entities_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaDesired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaDesired) ProtoMessage() {}

func (x *ReplicaDesired) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_entities_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaDesired.ProtoReflect.Descriptor instead.
func (*ReplicaDesired) Descriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{4}
}

func (x *ReplicaDesired) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReplicaDesired) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

func (x *ReplicaDesired) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ReplicaDesired) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ReplicaDesired) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ReplicaDesired) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ReplicaDesired) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

type ReplicaObserved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State         ReplicaState           `protobuf:"varint,2,opt,name=state,proto3,enum=jaco.v1.ReplicaState" json:"state,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContainerId   string                 `protobuf:"bytes,6,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Host          string                 `protobuf:"bytes,7,opt,name=host,proto3" json:"host,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	LastHealthAt  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_health_at,json=lastHealthAt,proto3" json:"last_health_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaObserved) Reset() {
	*x = ReplicaObserved{}
	mi := &file_jaco_v1_entities_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaObserved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaObserved) ProtoMessage() {}

func (x *ReplicaObserved) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_entities_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaObserved.ProtoReflect.Descriptor instead.
func (*ReplicaObserved) Descriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{5}
}

func (x *ReplicaObserved) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReplicaObserved) GetState() ReplicaState {
	if x != nil {
		return x.State
	}
	return ReplicaState_REPLICA_STATE_UNSPECIFIED
}

func (x *ReplicaObserved) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ReplicaObserved) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReplicaObserved) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ReplicaObserved) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ReplicaObserved) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ReplicaObserved) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ReplicaObserved) GetLastHealthAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHealthAt
	}
	return nil
}

type Route struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Domain     string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Deployment string                 `protobuf:"bytes,2,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Service    string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Port       int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	TlsAuto    bool                   `protobuf:"varint,5,opt,name=tls_auto,json=tlsAuto,proto3" json:"tls_auto,omitempty"`
	// path is an optional URL path prefix (e.g. "/api/"). Default "" means
	// catch-all. Caddy matches routes in declaration order (first match
	// wins); JACO is responsible for emitting routes longest-prefix-first
	// so the more specific path is tried before the catch-all.
	Path string `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	// strip_path, when true and path is non-empty, strips the matched path
	// prefix from the request URI before proxying upstream (Caddy
	// strip_path_prefix rewrite). E.g. with path "/api", GET /api/foo reaches
	// the upstream as GET /foo. Default false forwards the full URI unchanged.
	StripPath     bool `protobuf:"varint,7,opt,name=strip_path,json=stripPath,proto3" json:"strip_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_jaco_v1_entities_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_entities_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{6}
}

func (x *Route) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Route) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

func (x *Route) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Route) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Route) GetTlsAuto() bool {
	if x != nil {
		return x.TlsAuto
	}
	return false
}

func (x *Route) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Route) GetStripPath() bool {
	if x != nil {
		return x.StripPath
	}
	return false
}

// TCPRoute is a raw-TCP (L4) ingress listener derived from a compose
// `ports:` entry that publishes a host port. Every node listens on
// published_port and forwards to a healthy replica of (deployment, service)
// on container_port, wherever that replica runs. Keyed cluster-wide by
// published_port — two deployments cannot publish the same host port.
type TCPRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublishedPort int32                  `protobuf:"varint,1,opt,name=published_port,json=publishedPort,proto3" json:"published_port,omitempty"`
	Deployment    string                 `protobuf:"bytes,2,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	ContainerPort int32                  `protobuf:"varint,4,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCPRoute) Reset() {
	*x = TCPRoute{}
	mi := &file_jaco_v1_entities_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPRoute) ProtoMessage() {}

func (x *TCPRoute) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_entities_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPRoute.ProtoReflect.Descriptor instead.
func (*TCPRoute) Descriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{7}
}

func (x *TCPRoute) GetPublishedPort() int32 {
	if x != nil {
		return x.PublishedPort
	}
	return 0
}

func (x *TCPRoute) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

func (x *TCPRoute) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *TCPRoute) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

type Cert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	PrivateKey    []byte                 `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	CertChain     []byte                 `protobuf:"bytes,3,opt,name=cert_chain,json=certChain,proto3" json:"cert_chain,omitempty"`
	NotBefore     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	Lessee        string                 `protobuf:"bytes,6,opt,name=lessee,proto3" json:"lessee,omitempty"`
	LockUntil     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=lock_until,json=lockUntil,proto3" json:"lock_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cert) Reset() {
	*x = Cert{}
	mi := &file_jaco_v1_entities_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cert) ProtoMessage() {}

func (x *Cert) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_entities_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cert.ProtoReflect.Descriptor instead.
func (*Cert) Descriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{8}
}

func (x *Cert) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Cert) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *Cert) GetCertChain() []byte {
	if x != nil {
		return x.CertChain
	}
	return nil
}

func (x *Cert) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *Cert) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *Cert) GetLessee() string {
	if x != nil {
		return x.Lessee
	}
	return ""
}

func (x *Cert) GetLockUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.LockUntil
	}
	return nil
}

type ChallengeToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	KeyAuth       string                 `protobuf:"bytes,3,opt,name=key_auth,json=keyAuth,proto3" json:"key_auth,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeToken) Reset() {
	*x = ChallengeToken{}
	mi := &file_jaco_v1_entities_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeToken) ProtoMessage() {}

func (x *ChallengeToken) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_entities_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeToken.ProtoReflect.Descriptor instead.
func (*ChallengeToken) Descriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{9}
}

func (x *ChallengeToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ChallengeToken) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ChallengeToken) GetKeyAuth() string {
	if x != nil {
		return x.KeyAuth
	}
	return ""
}

func (x *ChallengeToken) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// CertBlob is the raft-replicated payload behind ingress/storage's
// certmagic.Storage. The key is whatever CertMagic hands us
// (e.g. "certificates/<domain>/<file>"); the value is the opaque blob.
type CertBlob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertBlob) Reset() {
	*x = CertBlob{}
	mi := &file_jaco_v1_entities_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertBlob) ProtoMessage() {}

func (x *CertBlob) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_entities_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertBlob.ProtoReflect.Descriptor instead.
func (*CertBlob) Descriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{10}
}

func (x *CertBlob) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CertBlob) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CertBlob) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Token struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Identity     string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	HashedSecret []byte                 `protobuf:"bytes,2,opt,name=hashed_secret,json=hashedSecret,proto3" json:"hashed_secret,omitempty"`
	IssuedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	RevokedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	// allows_privileged gates manifests that set `privileged:` or
	// `security_opt:` (issue #119). Bootstrap-issued tokens default false;
	// operators opt in explicitly via `jaco token issue --allow-privileged`.
	AllowsPrivileged bool `protobuf:"varint,5,opt,name=allows_privileged,json=allowsPrivileged,proto3" json:"allows_privileged,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_jaco_v1_entities_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_entities_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{11}
}

func (x *Token) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *Token) GetHashedSecret() []byte {
	if x != nil {
		return x.HashedSecret
	}
	return nil
}

func (x *Token) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *Token) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *Token) GetAllowsPrivileged() bool {
	if x != nil {
		return x.AllowsPrivileged
	}
	return false
}

type JoinToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HashedSecret  []byte                 `protobuf:"bytes,1,opt,name=hashed_secret,json=hashedSecret,proto3" json:"hashed_secret,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ConsumedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=consumed_at,json=consumedAt,proto3" json:"consumed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinToken) Reset() {
	*x = JoinToken{}
	mi := &file_jaco_v1_entities_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinToken) ProtoMessage() {}

func (x *JoinToken) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_entities_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinToken.ProtoReflect.Descriptor instead.
func (*JoinToken) Descriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{12}
}

func (x *JoinToken) GetHashedSecret() []byte {
	if x != nil {
		return x.HashedSecret
	}
	return nil
}

func (x *JoinToken) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *JoinToken) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *JoinToken) GetConsumedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConsumedAt
	}
	return nil
}

type AuditEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RaftIndex     uint64                 `protobuf:"varint,1,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	Type          AuditEventType         `protobuf:"varint,2,opt,name=type,proto3,enum=jaco.v1.AuditEventType" json:"type,omitempty"`
	Identity      string                 `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ts,proto3" json:"ts,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,5,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_jaco_v1_entities_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_entities_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{13}
}

func (x *AuditEvent) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

func (x *AuditEvent) GetType() AuditEventType {
	if x != nil {
		return x.Type
	}
	return AuditEventType_AUDIT_EVENT_TYPE_UNSPECIFIED
}

func (x *AuditEvent) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *AuditEvent) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *AuditEvent) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Subnet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    string                 `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Network       string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Cidr          string                 `protobuf:"bytes,3,opt,name=cidr,proto3" json:"cidr,omitempty"`
	AllocatedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=allocated_at,json=allocatedAt,proto3" json:"allocated_at,omitempty"`
	Host          string                 `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subnet) Reset() {
	*x = Subnet{}
	mi := &file_jaco_v1_entities_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subnet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subnet) ProtoMessage() {}

func (x *Subnet) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_entities_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subnet.ProtoReflect.Descriptor instead.
func (*Subnet) Descriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{14}
}

func (x *Subnet) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

func (x *Subnet) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Subnet) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *Subnet) GetAllocatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AllocatedAt
	}
	return nil
}

func (x *Subnet) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type RolloutPlan struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Deployment     string                 `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Service        string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	TargetRevision uint64                 `protobuf:"varint,3,opt,name=target_revision,json=targetRevision,proto3" json:"target_revision,omitempty"`
	TotalSteps     int32                  `protobuf:"varint,4,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`
	CurrentStep    int32                  `protobuf:"varint,5,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	State          RolloutState           `protobuf:"varint,6,opt,name=state,proto3,enum=jaco.v1.RolloutState" json:"state,omitempty"`
	FailureReason  string                 `protobuf:"bytes,7,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	LastStepAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_step_at,json=lastStepAt,proto3" json:"last_step_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RolloutPlan) Reset() {
	*x = RolloutPlan{}
	mi := &file_jaco_v1_entities_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolloutPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolloutPlan) ProtoMessage() {}

func (x *RolloutPlan) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_entities_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolloutPlan.ProtoReflect.Descriptor instead.
func (*RolloutPlan) Descriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{15}
}

func (x *RolloutPlan) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

func (x *RolloutPlan) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *RolloutPlan) GetTargetRevision() uint64 {
	if x != nil {
		return x.TargetRevision
	}
	return 0
}

func (x *RolloutPlan) GetTotalSteps() int32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

func (x *RolloutPlan) GetCurrentStep() int32 {
	if x != nil {
		return x.CurrentStep
	}
	return 0
}

func (x *RolloutPlan) GetState() RolloutState {
	if x != nil {
		return x.State
	}
	return RolloutState_ROLLOUT_STATE_UNSPECIFIED
}

func (x *RolloutPlan) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *RolloutPlan) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *RolloutPlan) GetLastStepAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastStepAt
	}
	return nil
}

type ReplicaCounter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    string                 `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	NextIndex     uint64                 `protobuf:"varint,3,opt,name=next_index,json=nextIndex,proto3" json:"next_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaCounter) Reset() {
	*x = ReplicaCounter{}
	mi := &file_jaco_v1_entities_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaCounter) ProtoMessage() {}

func (x *ReplicaCounter) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_entities_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaCounter.ProtoReflect.Descriptor instead.
func (*ReplicaCounter) Descriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{16}
}

func (x *ReplicaCounter) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

func (x *ReplicaCounter) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ReplicaCounter) GetNextIndex() uint64 {
	if x != nil {
		return x.NextIndex
	}
	return 0
}

type RestartCounter struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ReplicaId           string                 `protobuf:"bytes,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	ConsecutiveFailures int32                  `protobuf:"varint,2,opt,name=consecutive_failures,json=consecutiveFailures,proto3" json:"consecutive_failures,omitempty"`
	LastAttemptAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_attempt_at,json=lastAttemptAt,proto3" json:"last_attempt_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RestartCounter) Reset() {
	*x = RestartCounter{}
	mi := &file_jaco_v1_entities_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartCounter) ProtoMessage() {}

func (x *RestartCounter) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_entities_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartCounter.ProtoReflect.Descriptor instead.
func (*RestartCounter) Descriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{17}
}

func (x *RestartCounter) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *RestartCounter) GetConsecutiveFailures() int32 {
	if x != nil {
		return x.ConsecutiveFailures
	}
	return 0
}

func (x *RestartCounter) GetLastAttemptAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAttemptAt
	}
	return nil
}

// RegistryCredential is the raft-replicated container-registry credential
// consumed at image-pull time. Keyed by canonical registry host:
//   - "docker.io"   for Docker Hub (normalized from index.docker.io / docker.io)
//   - "ghcr.io"     for GitHub Container Registry
//   - "registry.example.com:5000"  for self-hosted registries on non-443 ports
//
// secret is the password / API token / PAT, held opaquely. Encoded
// at-rest in raft alongside the cluster CA private key under the same
// filesystem-permission + WireGuard-transport trust posture; see
// docs/concepts/auth-and-tokens.md. Every list/audit surface MUST redact it.
type RegistryCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registry      string                 `protobuf:"bytes,1,opt,name=registry,proto3" json:"registry,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Secret        []byte                 `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryCredential) Reset() {
	*x = RegistryCredential{}
	mi := &file_jaco_v1_entities_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryCredential) ProtoMessage() {}

func (x *RegistryCredential) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_entities_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryCredential.ProtoReflect.Descriptor instead.
func (*RegistryCredential) Descriptor() ([]byte, []int) {
	return file_jaco_v1_entities_proto_rawDescGZIP(), []int{18}
}

func (x *RegistryCredential) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

func (x *RegistryCredential) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegistryCredential) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *RegistryCredential) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_jaco_v1_entities_proto protoreflect.FileDescriptor

const file_jaco_v1_entities_proto_rawDesc = "" +
	"\n" +
	"\x16jaco/v1/entities.proto\x12\ajaco.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x01\n" +
	"\vClusterMeta\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x17\n" +
	"\aca_cert\x18\x02 \x01(\fR\x06caCert\x12\x15\n" +
	"\x06ca_key\x18\x03 \x01(\fR\x05caKey\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc5\x04\n" +
	"\x04Node\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x126\n" +
	"\x17server_cert_fingerprint\x18\x03 \x01(\fR\x15serverCertFingerprint\x12)\n" +
	"\x10wireguard_pubkey\x18\x04 \x01(\fR\x0fwireguardPubkey\x12+\n" +
	"\x06status\x18\x05 \x01(\x0e2\x13.jaco.v1.NodeStatusR\x06status\x12G\n" +
	"\x0estatus_details\x18\x06 \x03(\v2 .jaco.v1.Node.StatusDetailsEntryR\rstatusDetails\x127\n" +
	"\tjoined_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x12!\n" +
	"\fgrpc_address\x18\b \x01(\tR\vgrpcAddress\x12!\n" +
	"\fcpu_pressure\x18\t \x01(\x01R\vcpuPressure\x12'\n" +
	"\x0fmemory_pressure\x18\n" +
	" \x01(\x01R\x0ememoryPressure\x12D\n" +
	"\x10last_pressure_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x0elastPressureAt\x1a@\n" +
	"\x12StatusDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe3\x02\n" +
	"\vServiceSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\breplicas\x18\x02 \x01(\x05R\breplicas\x12@\n" +
	"\tplacement\x18\x03 \x01(\x0e2\".jaco.v1.ServiceSpec.PlacementModeR\tplacement\x12\x14\n" +
	"\x05hosts\x18\x04 \x03(\tR\x05hosts\x12\x1a\n" +
	"\bnetworks\x18\x06 \x03(\tR\bnetworks\"\x98\x01\n" +
	"\rPlacementMode\x12\x1e\n" +
	"\x1aPLACEMENT_MODE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PLACEMENT_MODE_SPREAD\x10\x01\x12\x17\n" +
	"\x13PLACEMENT_MODE_PACK\x10\x02\x12\x18\n" +
	"\x14PLACEMENT_MODE_HOSTS\x10\x03\x12\x19\n" +
	"\x15PLACEMENT_MODE_GLOBAL\x10\x04J\x04\b\x05\x10\x06R\x0fcompose_service\"\x88\x04\n" +
	"\n" +
	"Deployment\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x10applied_revision\x18\x02 \x01(\x04R\x0fappliedRevision\x12+\n" +
	"\x11previous_revision\x18\x03 \x01(\x04R\x10previousRevision\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.jaco.v1.DeploymentStatusR\x06status\x12M\n" +
	"\x0estatus_details\x18\x05 \x03(\v2&.jaco.v1.Deployment.StatusDetailsEntryR\rstatusDetails\x12\x1b\n" +
	"\tjaco_yaml\x18\x06 \x01(\fR\bjacoYaml\x12!\n" +
	"\fcompose_yaml\x18\a \x01(\fR\vcomposeYaml\x120\n" +
	"\bservices\x18\b \x03(\v2\x14.jaco.v1.ServiceSpecR\bservices\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"acme_email\x18\n" +
	" \x01(\tR\tacmeEmail\x1a@\n" +
	"\x12StatusDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x01\n" +
	"\x0eReplicaDesired\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"deployment\x18\x02 \x01(\tR\n" +
	"deployment\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x14\n" +
	"\x05index\x18\x04 \x01(\x05R\x05index\x12\x12\n" +
	"\x04host\x18\x05 \x01(\tR\x04host\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x12\x1d\n" +
	"\n" +
	"raft_index\x18\a \x01(\x04R\traftIndex\"\xad\x03\n" +
	"\x0fReplicaObserved\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x05state\x18\x02 \x01(\x0e2\x15.jaco.v1.ReplicaStateR\x05state\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12?\n" +
	"\adetails\x18\x05 \x03(\v2%.jaco.v1.ReplicaObserved.DetailsEntryR\adetails\x12!\n" +
	"\fcontainer_id\x18\x06 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04host\x18\a \x01(\tR\x04host\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12@\n" +
	"\x0elast_health_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\flastHealthAt\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x01\n" +
	"\x05Route\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1e\n" +
	"\n" +
	"deployment\x18\x02 \x01(\tR\n" +
	"deployment\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x19\n" +
	"\btls_auto\x18\x05 \x01(\bR\atlsAuto\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"strip_path\x18\a \x01(\bR\tstripPath\"\x92\x01\n" +
	"\bTCPRoute\x12%\n" +
	"\x0epublished_port\x18\x01 \x01(\x05R\rpublishedPort\x12\x1e\n" +
	"\n" +
	"deployment\x18\x02 \x01(\tR\n" +
	"deployment\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12%\n" +
	"\x0econtainer_port\x18\x04 \x01(\x05R\rcontainerPort\"\xa5\x02\n" +
	"\x04Cert\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1f\n" +
	"\vprivate_key\x18\x02 \x01(\fR\n" +
	"privateKey\x12\x1d\n" +
	"\n" +
	"cert_chain\x18\x03 \x01(\fR\tcertChain\x129\n" +
	"\n" +
	"not_before\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12\x16\n" +
	"\x06lessee\x18\x06 \x01(\tR\x06lessee\x129\n" +
	"\n" +
	"lock_until\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tlockUntil\"\x94\x01\n" +
	"\x0eChallengeToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x19\n" +
	"\bkey_auth\x18\x03 \x01(\tR\akeyAuth\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"m\n" +
	"\bCertBlob\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe9\x01\n" +
	"\x05Token\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12#\n" +
	"\rhashed_secret\x18\x02 \x01(\fR\fhashedSecret\x127\n" +
	"\tissued_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"revoked_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x12+\n" +
	"\x11allows_privileged\x18\x05 \x01(\bR\x10allowsPrivileged\"\xe1\x01\n" +
	"\tJoinToken\x12#\n" +
	"\rhashed_secret\x18\x01 \x01(\fR\fhashedSecret\x127\n" +
	"\tissued_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12;\n" +
	"\vconsumed_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"consumedAt\"\x98\x02\n" +
	"\n" +
	"AuditEvent\x12\x1d\n" +
	"\n" +
	"raft_index\x18\x01 \x01(\x04R\traftIndex\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.jaco.v1.AuditEventTypeR\x04type\x12\x1a\n" +
	"\bidentity\x18\x03 \x01(\tR\bidentity\x12*\n" +
	"\x02ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12:\n" +
	"\apayload\x18\x05 \x03(\v2 .jaco.v1.AuditEvent.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa9\x01\n" +
	"\x06Subnet\x12\x1e\n" +
	"\n" +
	"deployment\x18\x01 \x01(\tR\n" +
	"deployment\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x12\x12\n" +
	"\x04cidr\x18\x03 \x01(\tR\x04cidr\x12=\n" +
	"\fallocated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vallocatedAt\x12\x12\n" +
	"\x04host\x18\x05 \x01(\tR\x04host\"\x81\x03\n" +
	"\vRolloutPlan\x12\x1e\n" +
	"\n" +
	"deployment\x18\x01 \x01(\tR\n" +
	"deployment\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12'\n" +
	"\x0ftarget_revision\x18\x03 \x01(\x04R\x0etargetRevision\x12\x1f\n" +
	"\vtotal_steps\x18\x04 \x01(\x05R\n" +
	"totalSteps\x12!\n" +
	"\fcurrent_step\x18\x05 \x01(\x05R\vcurrentStep\x12+\n" +
	"\x05state\x18\x06 \x01(\x0e2\x15.jaco.v1.RolloutStateR\x05state\x12%\n" +
	"\x0efailure_reason\x18\a \x01(\tR\rfailureReason\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12<\n" +
	"\flast_step_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastStepAt\"i\n" +
	"\x0eReplicaCounter\x12\x1e\n" +
	"\n" +
	"deployment\x18\x01 \x01(\tR\n" +
	"deployment\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"next_index\x18\x03 \x01(\x04R\tnextIndex\"\xa6\x01\n" +
	"\x0eRestartCounter\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\tR\treplicaId\x121\n" +
	"\x14consecutive_failures\x18\x02 \x01(\x05R\x13consecutiveFailures\x12B\n" +
	"\x0flast_attempt_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rlastAttemptAt\"\x9f\x01\n" +
	"\x12RegistryCredential\x12\x1a\n" +
	"\bregistry\x18\x01 \x01(\tR\bregistry\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\fR\x06secret\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\xeb\x01\n" +
	"\fReplicaState\x12\x1d\n" +
	"\x19REPLICA_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15REPLICA_STATE_PENDING\x10\x01\x12\x19\n" +
	"\x15REPLICA_STATE_PULLING\x10\x02\x12\x19\n" +
	"\x15REPLICA_STATE_RUNNING\x10\x03\x12\x1a\n" +
	"\x16REPLICA_STATE_DEGRADED\x10\x04\x12\x1a\n" +
	"\x16REPLICA_STATE_UPDATING\x10\x05\x12\x18\n" +
	"\x14REPLICA_STATE_FAILED\x10\x06\x12\x19\n" +
	"\x15REPLICA_STATE_STOPPED\x10\a*\x84\x01\n" +
	"\fRolloutState\x12\x1d\n" +
	"\x19ROLLOUT_STATE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ROLLOUT_STATE_IN_PROGRESS\x10\x01\x12\x1b\n" +
	"\x17ROLLOUT_STATE_COMPLETED\x10\x02\x12\x19\n" +
	"\x15ROLLOUT_STATE_ABORTED\x10\x03*\x9f\x01\n" +
	"\n" +
	"NodeStatus\x12\x1b\n" +
	"\x17NODE_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13NODE_STATUS_JOINING\x10\x01\x12\x15\n" +
	"\x11NODE_STATUS_READY\x10\x02\x12%\n" +
	"!NODE_STATUS_ISOLATION_UNAVAILABLE\x10\x03\x12\x1d\n" +
	"\x19NODE_STATUS_DRAIN_TIMEOUT\x10\x04*r\n" +
	"\x10DeploymentStatus\x12!\n" +
	"\x1dDEPLOYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19DEPLOYMENT_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18DEPLOYMENT_STATUS_ACTIVE\x10\x02*\xbe\a\n" +
	"\x0eAuditEventType\x12 \n" +
	"\x1cAUDIT_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16AUDIT_EVENT_TYPE_APPLY\x10\x01\x12\x1b\n" +
	"\x17AUDIT_EVENT_TYPE_DELETE\x10\x02\x12\x1d\n" +
	"\x19AUDIT_EVENT_TYPE_ROLLBACK\x10\x03\x12\x1e\n" +
	"\x1aAUDIT_EVENT_TYPE_NODE_JOIN\x10\x04\x12 \n" +
	"\x1cAUDIT_EVENT_TYPE_NODE_REMOVE\x10\x05\x12 \n" +
	"\x1cAUDIT_EVENT_TYPE_TOKEN_ISSUE\x10\x06\x12!\n" +
	"\x1dAUDIT_EVENT_TYPE_TOKEN_REVOKE\x10\a\x12'\n" +
	"#AUDIT_EVENT_TYPE_CERTIFICATE_ISSUED\x10\b\x12(\n" +
	"$AUDIT_EVENT_TYPE_CERTIFICATE_RENEWED\x10\t\x12'\n" +
	"#AUDIT_EVENT_TYPE_CERTIFICATE_FAILED\x10\n" +
	"\x121\n" +
	"-AUDIT_EVENT_TYPE_ISOLATION_RULESET_RECONCILED\x10\v\x12*\n" +
	"&AUDIT_EVENT_TYPE_ISOLATION_UNAVAILABLE\x10\f\x12!\n" +
	"\x1dAUDIT_EVENT_TYPE_BACKUP_TAKEN\x10\r\x12&\n" +
	"\"AUDIT_EVENT_TYPE_RESTORE_COMPLETED\x10\x0e\x12&\n" +
	"\"AUDIT_EVENT_TYPE_UPGRADE_SUCCEEDED\x10\x0f\x12#\n" +
	"\x1fAUDIT_EVENT_TYPE_UPGRADE_FAILED\x10\x10\x12+\n" +
	"'AUDIT_EVENT_TYPE_ROLLOUT_INVARIANT_HOLD\x10\x11\x12/\n" +
	"+AUDIT_EVENT_TYPE_REGISTRY_CREDENTIAL_UPSERT\x10\x12\x12/\n" +
	"+AUDIT_EVENT_TYPE_REGISTRY_CREDENTIAL_REMOVE\x10\x13\x121\n" +
	"-AUDIT_EVENT_TYPE_PRIVILEGED_WORKLOAD_ADMITTED\x10\x14\x12$\n" +
	" AUDIT_EVENT_TYPE_REBALANCE_MOVED\x10\x15\x12&\n" +
	"\"AUDIT_EVENT_TYPE_REBALANCE_SKIPPED\x10\x17\"\x04\b\x16\x10\x16*\"AUDIT_EVENT_TYPE_REBALANCE_DRY_RUNB:Z8github.com/PatrickRuddiman/jaco/pkg/proto/jaco/v1;jacov1b\x06proto3"

var (
	file_jaco_v1_entities_proto_rawDescOnce sync.Once
	file_jaco_v1_entities_proto_rawDescData []byte
)

func file_jaco_v1_entities_proto_rawDescGZIP() []byte {
	file_jaco_v1_entities_proto_rawDescOnce.Do(func() {
		file_jaco_v1_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jaco_v1_entities_proto_rawDesc), len(file_jaco_v1_entities_proto_rawDesc)))
	})
	return file_jaco_v1_entities_proto_rawDescData
}

var file_jaco_v1_entities_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_jaco_v1_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_jaco_v1_entities_proto_goTypes = []any{
	(ReplicaState)(0),              // 0: jaco.v1.ReplicaState
	(RolloutState)(0),              // 1: jaco.v1.RolloutState
	(NodeStatus)(0),                // 2: jaco.v1.NodeStatus
	(DeploymentStatus)(0),          // 3: jaco.v1.DeploymentStatus
	(AuditEventType)(0),            // 4: jaco.v1.AuditEventType
	(ServiceSpec_PlacementMode)(0), // 5: jaco.v1.ServiceSpec.PlacementMode
	(*ClusterMeta)(nil),            // 6: jaco.v1.ClusterMeta
	(*Node)(nil),                   // 7: jaco.v1.Node
	(*ServiceSpec)(nil),            // 8: jaco.v1.ServiceSpec
	(*Deployment)(nil),             // 9: jaco.v1.Deployment
	(*ReplicaDesired)(nil),         // 10: jaco.v1.ReplicaDesired
	(*ReplicaObserved)(nil),        // 11: jaco.v1.ReplicaObserved
	(*Route)(nil),                  // 12: jaco.v1.Route
	(*TCPRoute)(nil),               // 13: jaco.v1.TCPRoute
	(*Cert)(nil),                   // 14: jaco.v1.Cert
	(*ChallengeToken)(nil),         // 15: jaco.v1.ChallengeToken
	(*CertBlob)(nil),               // 16: jaco.v1.CertBlob
	(*Token)(nil),                  // 17: jaco.v1.Token
	(*JoinToken)(nil),              // 18: jaco.v1.JoinToken
	(*AuditEvent)(nil),             // 19: jaco.v1.AuditEvent
	(*Subnet)(nil),                 // 20: jaco.v1.Subnet
	(*RolloutPlan)(nil),            // 21: jaco.v1.RolloutPlan
	(*ReplicaCounter)(nil),         // 22: jaco.v1.ReplicaCounter
	(*RestartCounter)(nil),         // 23: jaco.v1.RestartCounter
	(*RegistryCredential)(nil),     // 24: jaco.v1.RegistryCredential
	nil,                            // 25: jaco.v1.Node.StatusDetailsEntry
	nil,                            // 26: jaco.v1.Deployment.StatusDetailsEntry
	nil,                            // 27: jaco.v1.ReplicaObserved.DetailsEntry
	nil,                            // 28: jaco.v1.AuditEvent.PayloadEntry
	(*timestamppb.Timestamp)(nil),  // 29: google.protobuf.Timestamp
}
var file_jaco_v1_entities_proto_depIdxs = []int32{
	29, // 0: jaco.v1.ClusterMeta.created_at:type_name -> google.protobuf.Timestamp
	2,  // 1: jaco.v1.Node.status:type_name -> jaco.v1.NodeStatus
	25, // 2: jaco.v1.Node.status_details:type_name -> jaco.v1.Node.StatusDetailsEntry
	29, // 3: jaco.v1.Node.joined_at:type_name -> google.protobuf.Timestamp
	29, // 4: jaco.v1.Node.last_pressure_at:type_name -> google.protobuf.Timestamp
	5,  // 5: jaco.v1.ServiceSpec.placement:type_name -> jaco.v1.ServiceSpec.PlacementMode
	3,  // 6: jaco.v1.Deployment.status:type_name -> jaco.v1.DeploymentStatus
	26, // 7: jaco.v1.Deployment.status_details:type_name -> jaco.v1.Deployment.StatusDetailsEntry
	8,  // 8: jaco.v1.Deployment.services:type_name -> jaco.v1.ServiceSpec
	29, // 9: jaco.v1.Deployment.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 10: jaco.v1.ReplicaObserved.state:type_name -> jaco.v1.ReplicaState
	27, // 11: jaco.v1.ReplicaObserved.details:type_name -> jaco.v1.ReplicaObserved.DetailsEntry
	29, // 12: jaco.v1.ReplicaObserved.started_at:type_name -> google.protobuf.Timestamp
	29, // 13: jaco.v1.ReplicaObserved.last_health_at:type_name -> google.protobuf.Timestamp
	29, // 14: jaco.v1.Cert.not_before:type_name -> google.protobuf.Timestamp
	29, // 15: jaco.v1.Cert.not_after:type_name -> google.protobuf.Timestamp
	29, // 16: jaco.v1.Cert.lock_until:type_name -> google.protobuf.Timestamp
	29, // 17: jaco.v1.ChallengeToken.expires_at:type_name -> google.protobuf.Timestamp
	29, // 18: jaco.v1.CertBlob.updated_at:type_name -> google.protobuf.Timestamp
	29, // 19: jaco.v1.Token.issued_at:type_name -> google.protobuf.Timestamp
	29, // 20: jaco.v1.Token.revoked_at:type_name -> google.protobuf.Timestamp
	29, // 21: jaco.v1.JoinToken.issued_at:type_name -> google.protobuf.Timestamp
	29, // 22: jaco.v1.JoinToken.expires_at:type_name -> google.protobuf.Timestamp
	29, // 23: jaco.v1.JoinToken.consumed_at:type_name -> google.protobuf.Timestamp
	4,  // 24: jaco.v1.AuditEvent.type:type_name -> jaco.v1.AuditEventType
	29, // 25: jaco.v1.AuditEvent.ts:type_name -> google.protobuf.Timestamp
	28, // 26: jaco.v1.AuditEvent.payload:type_name -> jaco.v1.AuditEvent.PayloadEntry
	29, // 27: jaco.v1.Subnet.allocated_at:type_name -> google.protobuf.Timestamp
	1,  // 28: jaco.v1.RolloutPlan.state:type_name -> jaco.v1.RolloutState
	29, // 29: jaco.v1.RolloutPlan.started_at:type_name -> google.protobuf.Timestamp
	29, // 30: jaco.v1.RolloutPlan.last_step_at:type_name -> google.protobuf.Timestamp
	29, // 31: jaco.v1.RestartCounter.last_attempt_at:type_name -> google.protobuf.Timestamp
	29, // 32: jaco.v1.RegistryCredential.updated_at:type_name -> google.protobuf.Timestamp
	33, // [33:33] is the sub-list for method output_type
	33, // [33:33] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_jaco_v1_entities_proto_init() }
func file_jaco_v1_entities_proto_init() {
	if File_jaco_v1_entities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jaco_v1_entities_proto_rawDesc), len(file_jaco_v1_entities_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jaco_v1_entities_proto_goTypes,
		DependencyIndexes: file_jaco_v1_entities_proto_depIdxs,
		EnumInfos:         file_jaco_v1_entities_proto_enumTypes,
		MessageInfos:      file_jaco_v1_entities_proto_msgTypes,
	}.Build()
	File_jaco_v1_entities_proto = out.File
	file_jaco_v1_entities_proto_goTypes = nil
	file_jaco_v1_entities_proto_depIdxs = nil
}
