// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jaco/v1/events.proto

package jacov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventKind int32

const (
	EventKind_EVENT_KIND_UNSPECIFIED EventKind = 0
	EventKind_EVENT_KIND_ADDED       EventKind = 1
	EventKind_EVENT_KIND_UPDATED     EventKind = 2
	EventKind_EVENT_KIND_REMOVED     EventKind = 3
	EventKind_EVENT_KIND_RESYNC      EventKind = 4
)

// Enum value maps for EventKind.
var (
	EventKind_name = map[int32]string{
		0: "EVENT_KIND_UNSPECIFIED",
		1: "EVENT_KIND_ADDED",
		2: "EVENT_KIND_UPDATED",
		3: "EVENT_KIND_REMOVED",
		4: "EVENT_KIND_RESYNC",
	}
	EventKind_value = map[string]int32{
		"EVENT_KIND_UNSPECIFIED": 0,
		"EVENT_KIND_ADDED":       1,
		"EVENT_KIND_UPDATED":     2,
		"EVENT_KIND_REMOVED":     3,
		"EVENT_KIND_RESYNC":      4,
	}
)

func (x EventKind) Enum() *EventKind {
	p := new(EventKind)
	*p = x
	return p
}

func (x EventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_jaco_v1_events_proto_enumTypes[0].Descriptor()
}

func (EventKind) Type() protoreflect.EnumType {
	return &file_jaco_v1_events_proto_enumTypes[0]
}

func (x EventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventKind.Descriptor instead.
func (EventKind) EnumDescriptor() ([]byte, []int) {
	return file_jaco_v1_events_proto_rawDescGZIP(), []int{0}
}

type NodeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EventKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=jaco.v1.EventKind" json:"kind,omitempty"`
	Before        *Node                  `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	After         *Node                  `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	RaftIndex     uint64                 `protobuf:"varint,4,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeEvent) Reset() {
	*x = NodeEvent{}
	mi := &file_jaco_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEvent) ProtoMessage() {}

func (x *NodeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEvent.ProtoReflect.Descriptor instead.
func (*NodeEvent) Descriptor() ([]byte, []int) {
	return file_jaco_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *NodeEvent) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *NodeEvent) GetBefore() *Node {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *NodeEvent) GetAfter() *Node {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *NodeEvent) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

type DeploymentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EventKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=jaco.v1.EventKind" json:"kind,omitempty"`
	Before        *Deployment            `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	After         *Deployment            `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	RaftIndex     uint64                 `protobuf:"varint,4,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentEvent) Reset() {
	*x = DeploymentEvent{}
	mi := &file_jaco_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentEvent) ProtoMessage() {}

func (x *DeploymentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentEvent.ProtoReflect.Descriptor instead.
func (*DeploymentEvent) Descriptor() ([]byte, []int) {
	return file_jaco_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *DeploymentEvent) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *DeploymentEvent) GetBefore() *Deployment {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *DeploymentEvent) GetAfter() *Deployment {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *DeploymentEvent) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

type ReplicaDesiredEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EventKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=jaco.v1.EventKind" json:"kind,omitempty"`
	Before        *ReplicaDesired        `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	After         *ReplicaDesired        `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	RaftIndex     uint64                 `protobuf:"varint,4,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaDesiredEvent) Reset() {
	*x = ReplicaDesiredEvent{}
	mi := &file_jaco_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaDesiredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaDesiredEvent) ProtoMessage() {}

func (x *ReplicaDesiredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaDesiredEvent.ProtoReflect.Descriptor instead.
func (*ReplicaDesiredEvent) Descriptor() ([]byte, []int) {
	return file_jaco_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *ReplicaDesiredEvent) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *ReplicaDesiredEvent) GetBefore() *ReplicaDesired {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *ReplicaDesiredEvent) GetAfter() *ReplicaDesired {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *ReplicaDesiredEvent) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

type ReplicaObservedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EventKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=jaco.v1.EventKind" json:"kind,omitempty"`
	Before        *ReplicaObserved       `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	After         *ReplicaObserved       `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	RaftIndex     uint64                 `protobuf:"varint,4,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaObservedEvent) Reset() {
	*x = ReplicaObservedEvent{}
	mi := &file_jaco_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaObservedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaObservedEvent) ProtoMessage() {}

func (x *ReplicaObservedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaObservedEvent.ProtoReflect.Descriptor instead.
func (*ReplicaObservedEvent) Descriptor() ([]byte, []int) {
	return file_jaco_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *ReplicaObservedEvent) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *ReplicaObservedEvent) GetBefore() *ReplicaObserved {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *ReplicaObservedEvent) GetAfter() *ReplicaObserved {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *ReplicaObservedEvent) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

type RouteEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EventKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=jaco.v1.EventKind" json:"kind,omitempty"`
	Before        *Route                 `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	After         *Route                 `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	RaftIndex     uint64                 `protobuf:"varint,4,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteEvent) Reset() {
	*x = RouteEvent{}
	mi := &file_jaco_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteEvent) ProtoMessage() {}

func (x *RouteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteEvent.ProtoReflect.Descriptor instead.
func (*RouteEvent) Descriptor() ([]byte, []int) {
	return file_jaco_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *RouteEvent) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *RouteEvent) GetBefore() *Route {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *RouteEvent) GetAfter() *Route {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *RouteEvent) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

type CertEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EventKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=jaco.v1.EventKind" json:"kind,omitempty"`
	Before        *Cert                  `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	After         *Cert                  `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	RaftIndex     uint64                 `protobuf:"varint,4,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertEvent) Reset() {
	*x = CertEvent{}
	mi := &file_jaco_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertEvent) ProtoMessage() {}

func (x *CertEvent) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertEvent.ProtoReflect.Descriptor instead.
func (*CertEvent) Descriptor() ([]byte, []int) {
	return file_jaco_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *CertEvent) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *CertEvent) GetBefore() *Cert {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *CertEvent) GetAfter() *Cert {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *CertEvent) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

type ChallengeTokenEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EventKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=jaco.v1.EventKind" json:"kind,omitempty"`
	Before        *ChallengeToken        `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	After         *ChallengeToken        `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	RaftIndex     uint64                 `protobuf:"varint,4,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeTokenEvent) Reset() {
	*x = ChallengeTokenEvent{}
	mi := &file_jaco_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeTokenEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeTokenEvent) ProtoMessage() {}

func (x *ChallengeTokenEvent) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeTokenEvent.ProtoReflect.Descriptor instead.
func (*ChallengeTokenEvent) Descriptor() ([]byte, []int) {
	return file_jaco_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *ChallengeTokenEvent) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *ChallengeTokenEvent) GetBefore() *ChallengeToken {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *ChallengeTokenEvent) GetAfter() *ChallengeToken {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *ChallengeTokenEvent) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

type TokenEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EventKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=jaco.v1.EventKind" json:"kind,omitempty"`
	Before        *Token                 `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	After         *Token                 `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	RaftIndex     uint64                 `protobuf:"varint,4,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenEvent) Reset() {
	*x = TokenEvent{}
	mi := &file_jaco_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenEvent) ProtoMessage() {}

func (x *TokenEvent) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenEvent.ProtoReflect.Descriptor instead.
func (*TokenEvent) Descriptor() ([]byte, []int) {
	return file_jaco_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *TokenEvent) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *TokenEvent) GetBefore() *Token {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *TokenEvent) GetAfter() *Token {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *TokenEvent) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

type JoinTokenEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EventKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=jaco.v1.EventKind" json:"kind,omitempty"`
	Before        *JoinToken             `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	After         *JoinToken             `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	RaftIndex     uint64                 `protobuf:"varint,4,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinTokenEvent) Reset() {
	*x = JoinTokenEvent{}
	mi := &file_jaco_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinTokenEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTokenEvent) ProtoMessage() {}

func (x *JoinTokenEvent) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTokenEvent.ProtoReflect.Descriptor instead.
func (*JoinTokenEvent) Descriptor() ([]byte, []int) {
	return file_jaco_v1_events_proto_rawDescGZIP(), []int{8}
}

func (x *JoinTokenEvent) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *JoinTokenEvent) GetBefore() *JoinToken {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *JoinTokenEvent) GetAfter() *JoinToken {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *JoinTokenEvent) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

type AuditLogEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EventKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=jaco.v1.EventKind" json:"kind,omitempty"`
	Before        *AuditEvent            `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	After         *AuditEvent            `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	RaftIndex     uint64                 `protobuf:"varint,4,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogEvent) Reset() {
	*x = AuditLogEvent{}
	mi := &file_jaco_v1_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogEvent) ProtoMessage() {}

func (x *AuditLogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogEvent.ProtoReflect.Descriptor instead.
func (*AuditLogEvent) Descriptor() ([]byte, []int) {
	return file_jaco_v1_events_proto_rawDescGZIP(), []int{9}
}

func (x *AuditLogEvent) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *AuditLogEvent) GetBefore() *AuditEvent {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *AuditLogEvent) GetAfter() *AuditEvent {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *AuditLogEvent) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

type SubnetEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EventKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=jaco.v1.EventKind" json:"kind,omitempty"`
	Before        *Subnet                `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	After         *Subnet                `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	RaftIndex     uint64                 `protobuf:"varint,4,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubnetEvent) Reset() {
	*x = SubnetEvent{}
	mi := &file_jaco_v1_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubnetEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetEvent) ProtoMessage() {}

func (x *SubnetEvent) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubnetEvent.ProtoReflect.Descriptor instead.
func (*SubnetEvent) Descriptor() ([]byte, []int) {
	return file_jaco_v1_events_proto_rawDescGZIP(), []int{10}
}

func (x *SubnetEvent) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *SubnetEvent) GetBefore() *Subnet {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *SubnetEvent) GetAfter() *Subnet {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *SubnetEvent) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

type RolloutPlanEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EventKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=jaco.v1.EventKind" json:"kind,omitempty"`
	Before        *RolloutPlan           `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	After         *RolloutPlan           `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	RaftIndex     uint64                 `protobuf:"varint,4,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolloutPlanEvent) Reset() {
	*x = RolloutPlanEvent{}
	mi := &file_jaco_v1_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolloutPlanEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolloutPlanEvent) ProtoMessage() {}

func (x *RolloutPlanEvent) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolloutPlanEvent.ProtoReflect.Descriptor instead.
func (*RolloutPlanEvent) Descriptor() ([]byte, []int) {
	return file_jaco_v1_events_proto_rawDescGZIP(), []int{11}
}

func (x *RolloutPlanEvent) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *RolloutPlanEvent) GetBefore() *RolloutPlan {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *RolloutPlanEvent) GetAfter() *RolloutPlan {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *RolloutPlanEvent) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

type ReplicaCounterEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EventKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=jaco.v1.EventKind" json:"kind,omitempty"`
	Before        *ReplicaCounter        `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	After         *ReplicaCounter        `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	RaftIndex     uint64                 `protobuf:"varint,4,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaCounterEvent) Reset() {
	*x = ReplicaCounterEvent{}
	mi := &file_jaco_v1_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaCounterEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaCounterEvent) ProtoMessage() {}

func (x *ReplicaCounterEvent) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaCounterEvent.ProtoReflect.Descriptor instead.
func (*ReplicaCounterEvent) Descriptor() ([]byte, []int) {
	return file_jaco_v1_events_proto_rawDescGZIP(), []int{12}
}

func (x *ReplicaCounterEvent) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *ReplicaCounterEvent) GetBefore() *ReplicaCounter {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *ReplicaCounterEvent) GetAfter() *ReplicaCounter {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *ReplicaCounterEvent) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

type RestartCounterEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EventKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=jaco.v1.EventKind" json:"kind,omitempty"`
	Before        *RestartCounter        `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	After         *RestartCounter        `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	RaftIndex     uint64                 `protobuf:"varint,4,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartCounterEvent) Reset() {
	*x = RestartCounterEvent{}
	mi := &file_jaco_v1_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartCounterEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartCounterEvent) ProtoMessage() {}

func (x *RestartCounterEvent) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartCounterEvent.ProtoReflect.Descriptor instead.
func (*RestartCounterEvent) Descriptor() ([]byte, []int) {
	return file_jaco_v1_events_proto_rawDescGZIP(), []int{13}
}

func (x *RestartCounterEvent) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *RestartCounterEvent) GetBefore() *RestartCounter {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *RestartCounterEvent) GetAfter() *RestartCounter {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *RestartCounterEvent) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

var File_jaco_v1_events_proto protoreflect.FileDescriptor

const file_jaco_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x14jaco/v1/events.proto\x12\ajaco.v1\x1a\x16jaco/v1/entities.proto\"\x9e\x01\n" +
	"\tNodeEvent\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.jaco.v1.EventKindR\x04kind\x12%\n" +
	"\x06before\x18\x02 \x01(\v2\r.jaco.v1.NodeR\x06before\x12#\n" +
	"\x05after\x18\x03 \x01(\v2\r.jaco.v1.NodeR\x05after\x12\x1d\n" +
	"\n" +
	"raft_index\x18\x04 \x01(\x04R\traftIndex\"\xb0\x01\n" +
	"\x0fDeploymentEvent\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.jaco.v1.EventKindR\x04kind\x12+\n" +
	"\x06before\x18\x02 \x01(\v2\x13.jaco.v1.DeploymentR\x06before\x12)\n" +
	"\x05after\x18\x03 \x01(\v2\x13.jaco.v1.DeploymentR\x05after\x12\x1d\n" +
	"\n" +
	"raft_index\x18\x04 \x01(\x04R\traftIndex\"\xbc\x01\n" +
	"\x13ReplicaDesiredEvent\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.jaco.v1.EventKindR\x04kind\x12/\n" +
	"\x06before\x18\x02 \x01(\v2\x17.jaco.v1.ReplicaDesiredR\x06before\x12-\n" +
	"\x05after\x18\x03 \x01(\v2\x17.jaco.v1.ReplicaDesiredR\x05after\x12\x1d\n" +
	"\n" +
	"raft_index\x18\x04 \x01(\x04R\traftIndex\"\xbf\x01\n" +
	"\x14ReplicaObservedEvent\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.jaco.v1.EventKindR\x04kind\x120\n" +
	"\x06before\x18\x02 \x01(\v2\x18.jaco.v1.ReplicaObservedR\x06before\x12.\n" +
	"\x05after\x18\x03 \x01(\v2\x18.jaco.v1.ReplicaObservedR\x05after\x12\x1d\n" +
	"\n" +
	"raft_index\x18\x04 \x01(\x04R\traftIndex\"\xa1\x01\n" +
	"\n" +
	"RouteEvent\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.jaco.v1.EventKindR\x04kind\x12&\n" +
	"\x06before\x18\x02 \x01(\v2\x0e.jaco.v1.RouteR\x06before\x12$\n" +
	"\x05after\x18\x03 \x01(\v2\x0e.jaco.v1.RouteR\x05after\x12\x1d\n" +
	"\n" +
	"raft_index\x18\x04 \x01(\x04R\traftIndex\"\x9e\x01\n" +
	"\tCertEvent\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.jaco.v1.EventKindR\x04kind\x12%\n" +
	"\x06before\x18\x02 \x01(\v2\r.jaco.v1.CertR\x06before\x12#\n" +
	"\x05after\x18\x03 \x01(\v2\r.jaco.v1.CertR\x05after\x12\x1d\n" +
	"\n" +
	"raft_index\x18\x04 \x01(\x04R\traftIndex\"\xbc\x01\n" +
	"\x13ChallengeTokenEvent\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.jaco.v1.EventKindR\x04kind\x12/\n" +
	"\x06before\x18\x02 \x01(\v2\x17.jaco.v1.ChallengeTokenR\x06before\x12-\n" +
	"\x05after\x18\x03 \x01(\v2\x17.jaco.v1.ChallengeTokenR\x05after\x12\x1d\n" +
	"\n" +
	"raft_index\x18\x04 \x01(\x04R\traftIndex\"\xa1\x01\n" +
	"\n" +
	"TokenEvent\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.jaco.v1.EventKindR\x04kind\x12&\n" +
	"\x06before\x18\x02 \x01(\v2\x0e.jaco.v1.TokenR\x06before\x12$\n" +
	"\x05after\x18\x03 \x01(\v2\x0e.jaco.v1.TokenR\x05after\x12\x1d\n" +
	"\n" +
	"raft_index\x18\x04 \x01(\x04R\traftIndex\"\xad\x01\n" +
	"\x0eJoinTokenEvent\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.jaco.v1.EventKindR\x04kind\x12*\n" +
	"\x06before\x18\x02 \x01(\v2\x12.jaco.v1.JoinTokenR\x06before\x12(\n" +
	"\x05after\x18\x03 \x01(\v2\x12.jaco.v1.JoinTokenR\x05after\x12\x1d\n" +
	"\n" +
	"raft_index\x18\x04 \x01(\x04R\traftIndex\"\xae\x01\n" +
	"\rAuditLogEvent\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.jaco.v1.EventKindR\x04kind\x12+\n" +
	"\x06before\x18\x02 \x01(\v2\x13.jaco.v1.AuditEventR\x06before\x12)\n" +
	"\x05after\x18\x03 \x01(\v2\x13.jaco.v1.AuditEventR\x05after\x12\x1d\n" +
	"\n" +
	"raft_index\x18\x04 \x01(\x04R\traftIndex\"\xa4\x01\n" +
	"\vSubnetEvent\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.jaco.v1.EventKindR\x04kind\x12'\n" +
	"\x06before\x18\x02 \x01(\v2\x0f.jaco.v1.SubnetR\x06before\x12%\n" +
	"\x05after\x18\x03 \x01(\v2\x0f.jaco.v1.SubnetR\x05after\x12\x1d\n" +
	"\n" +
	"raft_index\x18\x04 \x01(\x04R\traftIndex\"\xb3\x01\n" +
	"\x10RolloutPlanEvent\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.jaco.v1.EventKindR\x04kind\x12,\n" +
	"\x06before\x18\x02 \x01(\v2\x14.jaco.v1.RolloutPlanR\x06before\x12*\n" +
	"\x05after\x18\x03 \x01(\v2\x14.jaco.v1.RolloutPlanR\x05after\x12\x1d\n" +
	"\n" +
	"raft_index\x18\x04 \x01(\x04R\traftIndex\"\xbc\x01\n" +
	"\x13ReplicaCounterEvent\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.jaco.v1.EventKindR\x04kind\x12/\n" +
	"\x06before\x18\x02 \x01(\v2\x17.jaco.v1.ReplicaCounterR\x06before\x12-\n" +
	"\x05after\x18\x03 \x01(\v2\x17.jaco.v1.ReplicaCounterR\x05after\x12\x1d\n" +
	"\n" +
	"raft_index\x18\x04 \x01(\x04R\traftIndex\"\xbc\x01\n" +
	"\x13RestartCounterEvent\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.jaco.v1.EventKindR\x04kind\x12/\n" +
	"\x06before\x18\x02 \x01(\v2\x17.jaco.v1.RestartCounterR\x06before\x12-\n" +
	"\x05after\x18\x03 \x01(\v2\x17.jaco.v1.RestartCounterR\x05after\x12\x1d\n" +
	"\n" +
	"raft_index\x18\x04 \x01(\x04R\traftIndex*\x84\x01\n" +
	"\tEventKind\x12\x1a\n" +
	"\x16EVENT_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10EVENT_KIND_ADDED\x10\x01\x12\x16\n" +
	"\x12EVENT_KIND_UPDATED\x10\x02\x12\x16\n" +
	"\x12EVENT_KIND_REMOVED\x10\x03\x12\x15\n" +
	"\x11EVENT_KIND_RESYNC\x10\x04B:Z8github.com/PatrickRuddiman/jaco/pkg/proto/jaco/v1;jacov1b\x06proto3"

var (
	file_jaco_v1_events_proto_rawDescOnce sync.Once
	file_jaco_v1_events_proto_rawDescData []byte
)

func file_jaco_v1_events_proto_rawDescGZIP() []byte {
	file_jaco_v1_events_proto_rawDescOnce.Do(func() {
		file_jaco_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jaco_v1_events_proto_rawDesc), len(file_jaco_v1_events_proto_rawDesc)))
	})
	return file_jaco_v1_events_proto_rawDescData
}

var file_jaco_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jaco_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_jaco_v1_events_proto_goTypes = []any{
	(EventKind)(0),               // 0: jaco.v1.EventKind
	(*NodeEvent)(nil),            // 1: jaco.v1.NodeEvent
	(*DeploymentEvent)(nil),      // 2: jaco.v1.DeploymentEvent
	(*ReplicaDesiredEvent)(nil),  // 3: jaco.v1.ReplicaDesiredEvent
	(*ReplicaObservedEvent)(nil), // 4: jaco.v1.ReplicaObservedEvent
	(*RouteEvent)(nil),           // 5: jaco.v1.RouteEvent
	(*CertEvent)(nil),            // 6: jaco.v1.CertEvent
	(*ChallengeTokenEvent)(nil),  // 7: jaco.v1.ChallengeTokenEvent
	(*TokenEvent)(nil),           // 8: jaco.v1.TokenEvent
	(*JoinTokenEvent)(nil),       // 9: jaco.v1.JoinTokenEvent
	(*AuditLogEvent)(nil),        // 10: jaco.v1.AuditLogEvent
	(*SubnetEvent)(nil),          // 11: jaco.v1.SubnetEvent
	(*RolloutPlanEvent)(nil),     // 12: jaco.v1.RolloutPlanEvent
	(*ReplicaCounterEvent)(nil),  // 13: jaco.v1.ReplicaCounterEvent
	(*RestartCounterEvent)(nil),  // 14: jaco.v1.RestartCounterEvent
	(*Node)(nil),                 // 15: jaco.v1.Node
	(*Deployment)(nil),           // 16: jaco.v1.Deployment
	(*ReplicaDesired)(nil),       // 17: jaco.v1.ReplicaDesired
	(*ReplicaObserved)(nil),      // 18: jaco.v1.ReplicaObserved
	(*Route)(nil),                // 19: jaco.v1.Route
	(*Cert)(nil),                 // 20: jaco.v1.Cert
	(*ChallengeToken)(nil),       // 21: jaco.v1.ChallengeToken
	(*Token)(nil),                // 22: jaco.v1.Token
	(*JoinToken)(nil),            // 23: jaco.v1.JoinToken
	(*AuditEvent)(nil),           // 24: jaco.v1.AuditEvent
	(*Subnet)(nil),               // 25: jaco.v1.Subnet
	(*RolloutPlan)(nil),          // 26: jaco.v1.RolloutPlan
	(*ReplicaCounter)(nil),       // 27: jaco.v1.ReplicaCounter
	(*RestartCounter)(nil),       // 28: jaco.v1.RestartCounter
}
var file_jaco_v1_events_proto_depIdxs = []int32{
	0,  // 0: jaco.v1.NodeEvent.kind:type_name -> jaco.v1.EventKind
	15, // 1: jaco.v1.NodeEvent.before:type_name -> jaco.v1.Node
	15, // 2: jaco.v1.NodeEvent.after:type_name -> jaco.v1.Node
	0,  // 3: jaco.v1.DeploymentEvent.kind:type_name -> jaco.v1.EventKind
	16, // 4: jaco.v1.DeploymentEvent.before:type_name -> jaco.v1.Deployment
	16, // 5: jaco.v1.DeploymentEvent.after:type_name -> jaco.v1.Deployment
	0,  // 6: jaco.v1.ReplicaDesiredEvent.kind:type_name -> jaco.v1.EventKind
	17, // 7: jaco.v1.ReplicaDesiredEvent.before:type_name -> jaco.v1.ReplicaDesired
	17, // 8: jaco.v1.ReplicaDesiredEvent.after:type_name -> jaco.v1.ReplicaDesired
	0,  // 9: jaco.v1.ReplicaObservedEvent.kind:type_name -> jaco.v1.EventKind
	18, // 10: jaco.v1.ReplicaObservedEvent.before:type_name -> jaco.v1.ReplicaObserved
	18, // 11: jaco.v1.ReplicaObservedEvent.after:type_name -> jaco.v1.ReplicaObserved
	0,  // 12: jaco.v1.RouteEvent.kind:type_name -> jaco.v1.EventKind
	19, // 13: jaco.v1.RouteEvent.before:type_name -> jaco.v1.Route
	19, // 14: jaco.v1.RouteEvent.after:type_name -> jaco.v1.Route
	0,  // 15: jaco.v1.CertEvent.kind:type_name -> jaco.v1.EventKind
	20, // 16: jaco.v1.CertEvent.before:type_name -> jaco.v1.Cert
	20, // 17: jaco.v1.CertEvent.after:type_name -> jaco.v1.Cert
	0,  // 18: jaco.v1.ChallengeTokenEvent.kind:type_name -> jaco.v1.EventKind
	21, // 19: jaco.v1.ChallengeTokenEvent.before:type_name -> jaco.v1.ChallengeToken
	21, // 20: jaco.v1.ChallengeTokenEvent.after:type_name -> jaco.v1.ChallengeToken
	0,  // 21: jaco.v1.TokenEvent.kind:type_name -> jaco.v1.EventKind
	22, // 22: jaco.v1.TokenEvent.before:type_name -> jaco.v1.Token
	22, // 23: jaco.v1.TokenEvent.after:type_name -> jaco.v1.Token
	0,  // 24: jaco.v1.JoinTokenEvent.kind:type_name -> jaco.v1.EventKind
	23, // 25: jaco.v1.JoinTokenEvent.before:type_name -> jaco.v1.JoinToken
	23, // 26: jaco.v1.JoinTokenEvent.after:type_name -> jaco.v1.JoinToken
	0,  // 27: jaco.v1.AuditLogEvent.kind:type_name -> jaco.v1.EventKind
	24, // 28: jaco.v1.AuditLogEvent.before:type_name -> jaco.v1.AuditEvent
	24, // 29: jaco.v1.AuditLogEvent.after:type_name -> jaco.v1.AuditEvent
	0,  // 30: jaco.v1.SubnetEvent.kind:type_name -> jaco.v1.EventKind
	25, // 31: jaco.v1.SubnetEvent.before:type_name -> jaco.v1.Subnet
	25, // 32: jaco.v1.SubnetEvent.after:type_name -> jaco.v1.Subnet
	0,  // 33: jaco.v1.RolloutPlanEvent.kind:type_name -> jaco.v1.EventKind
	26, // 34: jaco.v1.RolloutPlanEvent.before:type_name -> jaco.v1.RolloutPlan
	26, // 35: jaco.v1.RolloutPlanEvent.after:type_name -> jaco.v1.RolloutPlan
	0,  // 36: jaco.v1.ReplicaCounterEvent.kind:type_name -> jaco.v1.EventKind
	27, // 37: jaco.v1.ReplicaCounterEvent.before:type_name -> jaco.v1.ReplicaCounter
	27, // 38: jaco.v1.ReplicaCounterEvent.after:type_name -> jaco.v1.ReplicaCounter
	0,  // 39: jaco.v1.RestartCounterEvent.kind:type_name -> jaco.v1.EventKind
	28, // 40: jaco.v1.RestartCounterEvent.before:type_name -> jaco.v1.RestartCounter
	28, // 41: jaco.v1.RestartCounterEvent.after:type_name -> jaco.v1.RestartCounter
	42, // [42:42] is the sub-list for method output_type
	42, // [42:42] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_jaco_v1_events_proto_init() }
func file_jaco_v1_events_proto_init() {
	if File_jaco_v1_events_proto != nil {
		return
	}
	file_jaco_v1_entities_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jaco_v1_events_proto_rawDesc), len(file_jaco_v1_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jaco_v1_events_proto_goTypes,
		DependencyIndexes: file_jaco_v1_events_proto_depIdxs,
		EnumInfos:         file_jaco_v1_events_proto_enumTypes,
		MessageInfos:      file_jaco_v1_events_proto_msgTypes,
	}.Build()
	File_jaco_v1_events_proto = out.File
	file_jaco_v1_events_proto_goTypes = nil
	file_jaco_v1_events_proto_depIdxs = nil
}
