// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jaco/v1/fsm.proto

package jacov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FSMSnapshot captures the full control-plane state for raft snapshot
// persistence and restore. Encoded with proto.Marshal; written as a single
// blob to the raft snapshot sink.
type FSMSnapshot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Cluster          *ClusterMeta           `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Nodes            []*Node                `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Deployments      []*Deployment          `protobuf:"bytes,3,rep,name=deployments,proto3" json:"deployments,omitempty"`
	ReplicasDesired  []*ReplicaDesired      `protobuf:"bytes,4,rep,name=replicas_desired,json=replicasDesired,proto3" json:"replicas_desired,omitempty"`
	ReplicasObserved []*ReplicaObserved     `protobuf:"bytes,5,rep,name=replicas_observed,json=replicasObserved,proto3" json:"replicas_observed,omitempty"`
	Routes           []*Route               `protobuf:"bytes,6,rep,name=routes,proto3" json:"routes,omitempty"`
	Certs            []*Cert                `protobuf:"bytes,7,rep,name=certs,proto3" json:"certs,omitempty"`
	ChallengeTokens  []*ChallengeToken      `protobuf:"bytes,8,rep,name=challenge_tokens,json=challengeTokens,proto3" json:"challenge_tokens,omitempty"`
	Tokens           []*Token               `protobuf:"bytes,9,rep,name=tokens,proto3" json:"tokens,omitempty"`
	JoinTokens       []*JoinToken           `protobuf:"bytes,10,rep,name=join_tokens,json=joinTokens,proto3" json:"join_tokens,omitempty"`
	Subnets          []*Subnet              `protobuf:"bytes,11,rep,name=subnets,proto3" json:"subnets,omitempty"`
	RolloutPlans     []*RolloutPlan         `protobuf:"bytes,12,rep,name=rollout_plans,json=rolloutPlans,proto3" json:"rollout_plans,omitempty"`
	ReplicaCounters  []*ReplicaCounter      `protobuf:"bytes,13,rep,name=replica_counters,json=replicaCounters,proto3" json:"replica_counters,omitempty"`
	RestartCounters  []*RestartCounter      `protobuf:"bytes,14,rep,name=restart_counters,json=restartCounters,proto3" json:"restart_counters,omitempty"`
	AuditEvents      []*AuditEvent          `protobuf:"bytes,15,rep,name=audit_events,json=auditEvents,proto3" json:"audit_events,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FSMSnapshot) Reset() {
	*x = FSMSnapshot{}
	mi := &file_jaco_v1_fsm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSMSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSMSnapshot) ProtoMessage() {}

func (x *FSMSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_fsm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSMSnapshot.ProtoReflect.Descriptor instead.
func (*FSMSnapshot) Descriptor() ([]byte, []int) {
	return file_jaco_v1_fsm_proto_rawDescGZIP(), []int{0}
}

func (x *FSMSnapshot) GetCluster() *ClusterMeta {
	if x != nil {
		return x.Cluster
	}
	return nil
}

func (x *FSMSnapshot) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *FSMSnapshot) GetDeployments() []*Deployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

func (x *FSMSnapshot) GetReplicasDesired() []*ReplicaDesired {
	if x != nil {
		return x.ReplicasDesired
	}
	return nil
}

func (x *FSMSnapshot) GetReplicasObserved() []*ReplicaObserved {
	if x != nil {
		return x.ReplicasObserved
	}
	return nil
}

func (x *FSMSnapshot) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *FSMSnapshot) GetCerts() []*Cert {
	if x != nil {
		return x.Certs
	}
	return nil
}

func (x *FSMSnapshot) GetChallengeTokens() []*ChallengeToken {
	if x != nil {
		return x.ChallengeTokens
	}
	return nil
}

func (x *FSMSnapshot) GetTokens() []*Token {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *FSMSnapshot) GetJoinTokens() []*JoinToken {
	if x != nil {
		return x.JoinTokens
	}
	return nil
}

func (x *FSMSnapshot) GetSubnets() []*Subnet {
	if x != nil {
		return x.Subnets
	}
	return nil
}

func (x *FSMSnapshot) GetRolloutPlans() []*RolloutPlan {
	if x != nil {
		return x.RolloutPlans
	}
	return nil
}

func (x *FSMSnapshot) GetReplicaCounters() []*ReplicaCounter {
	if x != nil {
		return x.ReplicaCounters
	}
	return nil
}

func (x *FSMSnapshot) GetRestartCounters() []*RestartCounter {
	if x != nil {
		return x.RestartCounters
	}
	return nil
}

func (x *FSMSnapshot) GetAuditEvents() []*AuditEvent {
	if x != nil {
		return x.AuditEvents
	}
	return nil
}

var File_jaco_v1_fsm_proto protoreflect.FileDescriptor

const file_jaco_v1_fsm_proto_rawDesc = "" +
	"\n" +
	"\x11jaco/v1/fsm.proto\x12\ajaco.v1\x1a\x16jaco/v1/entities.proto\"\xb8\x06\n" +
	"\vFSMSnapshot\x12.\n" +
	"\acluster\x18\x01 \x01(\v2\x14.jaco.v1.ClusterMetaR\acluster\x12#\n" +
	"\x05nodes\x18\x02 \x03(\v2\r.jaco.v1.NodeR\x05nodes\x125\n" +
	"\vdeployments\x18\x03 \x03(\v2\x13.jaco.v1.DeploymentR\vdeployments\x12B\n" +
	"\x10replicas_desired\x18\x04 \x03(\v2\x17.jaco.v1.ReplicaDesiredR\x0freplicasDesired\x12E\n" +
	"\x11replicas_observed\x18\x05 \x03(\v2\x18.jaco.v1.ReplicaObservedR\x10replicasObserved\x12&\n" +
	"\x06routes\x18\x06 \x03(\v2\x0e.jaco.v1.RouteR\x06routes\x12#\n" +
	"\x05certs\x18\a \x03(\v2\r.jaco.v1.CertR\x05certs\x12B\n" +
	"\x10challenge_tokens\x18\b \x03(\v2\x17.jaco.v1.ChallengeTokenR\x0fchallengeTokens\x12&\n" +
	"\x06tokens\x18\t \x03(\v2\x0e.jaco.v1.TokenR\x06tokens\x123\n" +
	"\vjoin_tokens\x18\n" +
	" \x03(\v2\x12.jaco.v1.JoinTokenR\n" +
	"joinTokens\x12)\n" +
	"\asubnets\x18\v \x03(\v2\x0f.jaco.v1.SubnetR\asubnets\x129\n" +
	"\rrollout_plans\x18\f \x03(\v2\x14.jaco.v1.RolloutPlanR\frolloutPlans\x12B\n" +
	"\x10replica_counters\x18\r \x03(\v2\x17.jaco.v1.ReplicaCounterR\x0freplicaCounters\x12B\n" +
	"\x10restart_counters\x18\x0e \x03(\v2\x17.jaco.v1.RestartCounterR\x0frestartCounters\x126\n" +
	"\faudit_events\x18\x0f \x03(\v2\x13.jaco.v1.AuditEventR\vauditEventsB:Z8github.com/PatrickRuddiman/jaco/pkg/proto/jaco/v1;jacov1b\x06proto3"

var (
	file_jaco_v1_fsm_proto_rawDescOnce sync.Once
	file_jaco_v1_fsm_proto_rawDescData []byte
)

func file_jaco_v1_fsm_proto_rawDescGZIP() []byte {
	file_jaco_v1_fsm_proto_rawDescOnce.Do(func() {
		file_jaco_v1_fsm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jaco_v1_fsm_proto_rawDesc), len(file_jaco_v1_fsm_proto_rawDesc)))
	})
	return file_jaco_v1_fsm_proto_rawDescData
}

var file_jaco_v1_fsm_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_jaco_v1_fsm_proto_goTypes = []any{
	(*FSMSnapshot)(nil),     // 0: jaco.v1.FSMSnapshot
	(*ClusterMeta)(nil),     // 1: jaco.v1.ClusterMeta
	(*Node)(nil),            // 2: jaco.v1.Node
	(*Deployment)(nil),      // 3: jaco.v1.Deployment
	(*ReplicaDesired)(nil),  // 4: jaco.v1.ReplicaDesired
	(*ReplicaObserved)(nil), // 5: jaco.v1.ReplicaObserved
	(*Route)(nil),           // 6: jaco.v1.Route
	(*Cert)(nil),            // 7: jaco.v1.Cert
	(*ChallengeToken)(nil),  // 8: jaco.v1.ChallengeToken
	(*Token)(nil),           // 9: jaco.v1.Token
	(*JoinToken)(nil),       // 10: jaco.v1.JoinToken
	(*Subnet)(nil),          // 11: jaco.v1.Subnet
	(*RolloutPlan)(nil),     // 12: jaco.v1.RolloutPlan
	(*ReplicaCounter)(nil),  // 13: jaco.v1.ReplicaCounter
	(*RestartCounter)(nil),  // 14: jaco.v1.RestartCounter
	(*AuditEvent)(nil),      // 15: jaco.v1.AuditEvent
}
var file_jaco_v1_fsm_proto_depIdxs = []int32{
	1,  // 0: jaco.v1.FSMSnapshot.cluster:type_name -> jaco.v1.ClusterMeta
	2,  // 1: jaco.v1.FSMSnapshot.nodes:type_name -> jaco.v1.Node
	3,  // 2: jaco.v1.FSMSnapshot.deployments:type_name -> jaco.v1.Deployment
	4,  // 3: jaco.v1.FSMSnapshot.replicas_desired:type_name -> jaco.v1.ReplicaDesired
	5,  // 4: jaco.v1.FSMSnapshot.replicas_observed:type_name -> jaco.v1.ReplicaObserved
	6,  // 5: jaco.v1.FSMSnapshot.routes:type_name -> jaco.v1.Route
	7,  // 6: jaco.v1.FSMSnapshot.certs:type_name -> jaco.v1.Cert
	8,  // 7: jaco.v1.FSMSnapshot.challenge_tokens:type_name -> jaco.v1.ChallengeToken
	9,  // 8: jaco.v1.FSMSnapshot.tokens:type_name -> jaco.v1.Token
	10, // 9: jaco.v1.FSMSnapshot.join_tokens:type_name -> jaco.v1.JoinToken
	11, // 10: jaco.v1.FSMSnapshot.subnets:type_name -> jaco.v1.Subnet
	12, // 11: jaco.v1.FSMSnapshot.rollout_plans:type_name -> jaco.v1.RolloutPlan
	13, // 12: jaco.v1.FSMSnapshot.replica_counters:type_name -> jaco.v1.ReplicaCounter
	14, // 13: jaco.v1.FSMSnapshot.restart_counters:type_name -> jaco.v1.RestartCounter
	15, // 14: jaco.v1.FSMSnapshot.audit_events:type_name -> jaco.v1.AuditEvent
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_jaco_v1_fsm_proto_init() }
func file_jaco_v1_fsm_proto_init() {
	if File_jaco_v1_fsm_proto != nil {
		return
	}
	file_jaco_v1_entities_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jaco_v1_fsm_proto_rawDesc), len(file_jaco_v1_fsm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jaco_v1_fsm_proto_goTypes,
		DependencyIndexes: file_jaco_v1_fsm_proto_depIdxs,
		MessageInfos:      file_jaco_v1_fsm_proto_msgTypes,
	}.Build()
	File_jaco_v1_fsm_proto = out.File
	file_jaco_v1_fsm_proto_goTypes = nil
	file_jaco_v1_fsm_proto_depIdxs = nil
}
