// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: jaco/v1/services.proto

package jacov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Cluster_Init_FullMethodName           = "/jaco.v1.Cluster/Init"
	Cluster_Join_FullMethodName           = "/jaco.v1.Cluster/Join"
	Cluster_Bootstrap_FullMethodName      = "/jaco.v1.Cluster/Bootstrap"
	Cluster_IssueJoinToken_FullMethodName = "/jaco.v1.Cluster/IssueJoinToken"
	Cluster_NodeJoin_FullMethodName       = "/jaco.v1.Cluster/NodeJoin"
	Cluster_NodeRemove_FullMethodName     = "/jaco.v1.Cluster/NodeRemove"
	Cluster_NodeList_FullMethodName       = "/jaco.v1.Cluster/NodeList"
	Cluster_Backup_FullMethodName         = "/jaco.v1.Cluster/Backup"
	Cluster_Restore_FullMethodName        = "/jaco.v1.Cluster/Restore"
	Cluster_Status_FullMethodName         = "/jaco.v1.Cluster/Status"
)

// ClusterClient is the client API for Cluster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterClient interface {
	// Local-control RPCs (called by `jaco` CLI over the unix socket against
	// the local jacod).
	Init(ctx context.Context, in *ClusterInitRequest, opts ...grpc.CallOption) (*ClusterInitResponse, error)
	Join(ctx context.Context, in *ClusterJoinRequest, opts ...grpc.CallOption) (*ClusterJoinResponse, error)
	// Cluster-wide RPCs (called from any node; leader-forwarded internally).
	Bootstrap(ctx context.Context, in *BootstrapRequest, opts ...grpc.CallOption) (*BootstrapResponse, error)
	IssueJoinToken(ctx context.Context, in *IssueJoinTokenRequest, opts ...grpc.CallOption) (*IssueJoinTokenResponse, error)
	NodeJoin(ctx context.Context, in *NodeJoinRequest, opts ...grpc.CallOption) (*NodeJoinResponse, error)
	NodeRemove(ctx context.Context, in *NodeRemoveRequest, opts ...grpc.CallOption) (*NodeRemoveResponse, error)
	NodeList(ctx context.Context, in *NodeListRequest, opts ...grpc.CallOption) (*NodeListResponse, error)
	Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BackupChunk], error)
	Restore(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BackupChunk, RestoreResponse], error)
	Status(ctx context.Context, in *ClusterStatusRequest, opts ...grpc.CallOption) (*ClusterStatusResponse, error)
}

type clusterClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterClient(cc grpc.ClientConnInterface) ClusterClient {
	return &clusterClient{cc}
}

func (c *clusterClient) Init(ctx context.Context, in *ClusterInitRequest, opts ...grpc.CallOption) (*ClusterInitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterInitResponse)
	err := c.cc.Invoke(ctx, Cluster_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) Join(ctx context.Context, in *ClusterJoinRequest, opts ...grpc.CallOption) (*ClusterJoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterJoinResponse)
	err := c.cc.Invoke(ctx, Cluster_Join_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) Bootstrap(ctx context.Context, in *BootstrapRequest, opts ...grpc.CallOption) (*BootstrapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BootstrapResponse)
	err := c.cc.Invoke(ctx, Cluster_Bootstrap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) IssueJoinToken(ctx context.Context, in *IssueJoinTokenRequest, opts ...grpc.CallOption) (*IssueJoinTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueJoinTokenResponse)
	err := c.cc.Invoke(ctx, Cluster_IssueJoinToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) NodeJoin(ctx context.Context, in *NodeJoinRequest, opts ...grpc.CallOption) (*NodeJoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeJoinResponse)
	err := c.cc.Invoke(ctx, Cluster_NodeJoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) NodeRemove(ctx context.Context, in *NodeRemoveRequest, opts ...grpc.CallOption) (*NodeRemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeRemoveResponse)
	err := c.cc.Invoke(ctx, Cluster_NodeRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) NodeList(ctx context.Context, in *NodeListRequest, opts ...grpc.CallOption) (*NodeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeListResponse)
	err := c.cc.Invoke(ctx, Cluster_NodeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BackupChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Cluster_ServiceDesc.Streams[0], Cluster_Backup_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BackupRequest, BackupChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cluster_BackupClient = grpc.ServerStreamingClient[BackupChunk]

func (c *clusterClient) Restore(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BackupChunk, RestoreResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Cluster_ServiceDesc.Streams[1], Cluster_Restore_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BackupChunk, RestoreResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cluster_RestoreClient = grpc.ClientStreamingClient[BackupChunk, RestoreResponse]

func (c *clusterClient) Status(ctx context.Context, in *ClusterStatusRequest, opts ...grpc.CallOption) (*ClusterStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterStatusResponse)
	err := c.cc.Invoke(ctx, Cluster_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterServer is the server API for Cluster service.
// All implementations must embed UnimplementedClusterServer
// for forward compatibility.
type ClusterServer interface {
	// Local-control RPCs (called by `jaco` CLI over the unix socket against
	// the local jacod).
	Init(context.Context, *ClusterInitRequest) (*ClusterInitResponse, error)
	Join(context.Context, *ClusterJoinRequest) (*ClusterJoinResponse, error)
	// Cluster-wide RPCs (called from any node; leader-forwarded internally).
	Bootstrap(context.Context, *BootstrapRequest) (*BootstrapResponse, error)
	IssueJoinToken(context.Context, *IssueJoinTokenRequest) (*IssueJoinTokenResponse, error)
	NodeJoin(context.Context, *NodeJoinRequest) (*NodeJoinResponse, error)
	NodeRemove(context.Context, *NodeRemoveRequest) (*NodeRemoveResponse, error)
	NodeList(context.Context, *NodeListRequest) (*NodeListResponse, error)
	Backup(*BackupRequest, grpc.ServerStreamingServer[BackupChunk]) error
	Restore(grpc.ClientStreamingServer[BackupChunk, RestoreResponse]) error
	Status(context.Context, *ClusterStatusRequest) (*ClusterStatusResponse, error)
	mustEmbedUnimplementedClusterServer()
}

// UnimplementedClusterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterServer struct{}

func (UnimplementedClusterServer) Init(context.Context, *ClusterInitRequest) (*ClusterInitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedClusterServer) Join(context.Context, *ClusterJoinRequest) (*ClusterJoinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedClusterServer) Bootstrap(context.Context, *BootstrapRequest) (*BootstrapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Bootstrap not implemented")
}
func (UnimplementedClusterServer) IssueJoinToken(context.Context, *IssueJoinTokenRequest) (*IssueJoinTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueJoinToken not implemented")
}
func (UnimplementedClusterServer) NodeJoin(context.Context, *NodeJoinRequest) (*NodeJoinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeJoin not implemented")
}
func (UnimplementedClusterServer) NodeRemove(context.Context, *NodeRemoveRequest) (*NodeRemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeRemove not implemented")
}
func (UnimplementedClusterServer) NodeList(context.Context, *NodeListRequest) (*NodeListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeList not implemented")
}
func (UnimplementedClusterServer) Backup(*BackupRequest, grpc.ServerStreamingServer[BackupChunk]) error {
	return status.Error(codes.Unimplemented, "method Backup not implemented")
}
func (UnimplementedClusterServer) Restore(grpc.ClientStreamingServer[BackupChunk, RestoreResponse]) error {
	return status.Error(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedClusterServer) Status(context.Context, *ClusterStatusRequest) (*ClusterStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedClusterServer) mustEmbedUnimplementedClusterServer() {}
func (UnimplementedClusterServer) testEmbeddedByValue()                 {}

// UnsafeClusterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterServer will
// result in compilation errors.
type UnsafeClusterServer interface {
	mustEmbedUnimplementedClusterServer()
}

func RegisterClusterServer(s grpc.ServiceRegistrar, srv ClusterServer) {
	// If the following call panics, it indicates UnimplementedClusterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Cluster_ServiceDesc, srv)
}

func _Cluster_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Init(ctx, req.(*ClusterInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Join(ctx, req.(*ClusterJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_Bootstrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootstrapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Bootstrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_Bootstrap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Bootstrap(ctx, req.(*BootstrapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_IssueJoinToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueJoinTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).IssueJoinToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_IssueJoinToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).IssueJoinToken(ctx, req.(*IssueJoinTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_NodeJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).NodeJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_NodeJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).NodeJoin(ctx, req.(*NodeJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_NodeRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).NodeRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_NodeRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).NodeRemove(ctx, req.(*NodeRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_NodeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).NodeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_NodeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).NodeList(ctx, req.(*NodeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_Backup_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BackupRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClusterServer).Backup(m, &grpc.GenericServerStream[BackupRequest, BackupChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cluster_BackupServer = grpc.ServerStreamingServer[BackupChunk]

func _Cluster_Restore_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterServer).Restore(&grpc.GenericServerStream[BackupChunk, RestoreResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cluster_RestoreServer = grpc.ClientStreamingServer[BackupChunk, RestoreResponse]

func _Cluster_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Status(ctx, req.(*ClusterStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Cluster_ServiceDesc is the grpc.ServiceDesc for Cluster service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cluster_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jaco.v1.Cluster",
	HandlerType: (*ClusterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _Cluster_Init_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _Cluster_Join_Handler,
		},
		{
			MethodName: "Bootstrap",
			Handler:    _Cluster_Bootstrap_Handler,
		},
		{
			MethodName: "IssueJoinToken",
			Handler:    _Cluster_IssueJoinToken_Handler,
		},
		{
			MethodName: "NodeJoin",
			Handler:    _Cluster_NodeJoin_Handler,
		},
		{
			MethodName: "NodeRemove",
			Handler:    _Cluster_NodeRemove_Handler,
		},
		{
			MethodName: "NodeList",
			Handler:    _Cluster_NodeList_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Cluster_Status_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Backup",
			Handler:       _Cluster_Backup_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Restore",
			Handler:       _Cluster_Restore_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "jaco/v1/services.proto",
}

const (
	Deploy_Apply_FullMethodName    = "/jaco.v1.Deploy/Apply"
	Deploy_Rollback_FullMethodName = "/jaco.v1.Deploy/Rollback"
	Deploy_Delete_FullMethodName   = "/jaco.v1.Deploy/Delete"
	Deploy_Status_FullMethodName   = "/jaco.v1.Deploy/Status"
	Deploy_Logs_FullMethodName     = "/jaco.v1.Deploy/Logs"
	Deploy_GetRoute_FullMethodName = "/jaco.v1.Deploy/GetRoute"
)

// DeployClient is the client API for Deploy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeployClient interface {
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error)
	Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Status(ctx context.Context, in *DeployStatusRequest, opts ...grpc.CallOption) (*DeployStatusResponse, error)
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error)
	// GetRoute returns the realized ingress view for one domain: the ordered
	// routes Caddy serves (path matches longest-prefix-first, catch-all last),
	// each with its upstream service/port and how many replicas are currently
	// eligible as upstreams. Lets operators verify path-scoping and spot a
	// route whose upstream service has no healthy replicas (issue #174).
	GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*GetRouteResponse, error)
}

type deployClient struct {
	cc grpc.ClientConnInterface
}

func NewDeployClient(cc grpc.ClientConnInterface) DeployClient {
	return &deployClient{cc}
}

func (c *deployClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResponse)
	err := c.cc.Invoke(ctx, Deploy_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployClient) Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackResponse)
	err := c.cc.Invoke(ctx, Deploy_Rollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, Deploy_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployClient) Status(ctx context.Context, in *DeployStatusRequest, opts ...grpc.CallOption) (*DeployStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployStatusResponse)
	err := c.cc.Invoke(ctx, Deploy_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Deploy_ServiceDesc.Streams[0], Deploy_Logs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogsRequest, LogLine]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Deploy_LogsClient = grpc.ServerStreamingClient[LogLine]

func (c *deployClient) GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*GetRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRouteResponse)
	err := c.cc.Invoke(ctx, Deploy_GetRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeployServer is the server API for Deploy service.
// All implementations must embed UnimplementedDeployServer
// for forward compatibility.
type DeployServer interface {
	Apply(context.Context, *ApplyRequest) (*ApplyResponse, error)
	Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Status(context.Context, *DeployStatusRequest) (*DeployStatusResponse, error)
	Logs(*LogsRequest, grpc.ServerStreamingServer[LogLine]) error
	// GetRoute returns the realized ingress view for one domain: the ordered
	// routes Caddy serves (path matches longest-prefix-first, catch-all last),
	// each with its upstream service/port and how many replicas are currently
	// eligible as upstreams. Lets operators verify path-scoping and spot a
	// route whose upstream service has no healthy replicas (issue #174).
	GetRoute(context.Context, *GetRouteRequest) (*GetRouteResponse, error)
	mustEmbedUnimplementedDeployServer()
}

// UnimplementedDeployServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeployServer struct{}

func (UnimplementedDeployServer) Apply(context.Context, *ApplyRequest) (*ApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedDeployServer) Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rollback not implemented")
}
func (UnimplementedDeployServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedDeployServer) Status(context.Context, *DeployStatusRequest) (*DeployStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedDeployServer) Logs(*LogsRequest, grpc.ServerStreamingServer[LogLine]) error {
	return status.Error(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedDeployServer) GetRoute(context.Context, *GetRouteRequest) (*GetRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoute not implemented")
}
func (UnimplementedDeployServer) mustEmbedUnimplementedDeployServer() {}
func (UnimplementedDeployServer) testEmbeddedByValue()                {}

// UnsafeDeployServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeployServer will
// result in compilation errors.
type UnsafeDeployServer interface {
	mustEmbedUnimplementedDeployServer()
}

func RegisterDeployServer(s grpc.ServiceRegistrar, srv DeployServer) {
	// If the following call panics, it indicates UnimplementedDeployServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Deploy_ServiceDesc, srv)
}

func _Deploy_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Deploy_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployServer).Apply(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deploy_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Deploy_Rollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployServer).Rollback(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deploy_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Deploy_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deploy_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Deploy_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployServer).Status(ctx, req.(*DeployStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deploy_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeployServer).Logs(m, &grpc.GenericServerStream[LogsRequest, LogLine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Deploy_LogsServer = grpc.ServerStreamingServer[LogLine]

func _Deploy_GetRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployServer).GetRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Deploy_GetRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployServer).GetRoute(ctx, req.(*GetRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Deploy_ServiceDesc is the grpc.ServiceDesc for Deploy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Deploy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jaco.v1.Deploy",
	HandlerType: (*DeployServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _Deploy_Apply_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _Deploy_Rollback_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Deploy_Delete_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Deploy_Status_Handler,
		},
		{
			MethodName: "GetRoute",
			Handler:    _Deploy_GetRoute_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Logs",
			Handler:       _Deploy_Logs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "jaco/v1/services.proto",
}

const (
	Tokens_Issue_FullMethodName  = "/jaco.v1.Tokens/Issue"
	Tokens_Revoke_FullMethodName = "/jaco.v1.Tokens/Revoke"
	Tokens_List_FullMethodName   = "/jaco.v1.Tokens/List"
)

// TokensClient is the client API for Tokens service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokensClient interface {
	Issue(ctx context.Context, in *TokenIssueRequest, opts ...grpc.CallOption) (*TokenIssueResponse, error)
	Revoke(ctx context.Context, in *TokenRevokeRequest, opts ...grpc.CallOption) (*TokenRevokeResponse, error)
	List(ctx context.Context, in *TokenListRequest, opts ...grpc.CallOption) (*TokenListResponse, error)
}

type tokensClient struct {
	cc grpc.ClientConnInterface
}

func NewTokensClient(cc grpc.ClientConnInterface) TokensClient {
	return &tokensClient{cc}
}

func (c *tokensClient) Issue(ctx context.Context, in *TokenIssueRequest, opts ...grpc.CallOption) (*TokenIssueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenIssueResponse)
	err := c.cc.Invoke(ctx, Tokens_Issue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokensClient) Revoke(ctx context.Context, in *TokenRevokeRequest, opts ...grpc.CallOption) (*TokenRevokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenRevokeResponse)
	err := c.cc.Invoke(ctx, Tokens_Revoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokensClient) List(ctx context.Context, in *TokenListRequest, opts ...grpc.CallOption) (*TokenListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenListResponse)
	err := c.cc.Invoke(ctx, Tokens_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokensServer is the server API for Tokens service.
// All implementations must embed UnimplementedTokensServer
// for forward compatibility.
type TokensServer interface {
	Issue(context.Context, *TokenIssueRequest) (*TokenIssueResponse, error)
	Revoke(context.Context, *TokenRevokeRequest) (*TokenRevokeResponse, error)
	List(context.Context, *TokenListRequest) (*TokenListResponse, error)
	mustEmbedUnimplementedTokensServer()
}

// UnimplementedTokensServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokensServer struct{}

func (UnimplementedTokensServer) Issue(context.Context, *TokenIssueRequest) (*TokenIssueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Issue not implemented")
}
func (UnimplementedTokensServer) Revoke(context.Context, *TokenRevokeRequest) (*TokenRevokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Revoke not implemented")
}
func (UnimplementedTokensServer) List(context.Context, *TokenListRequest) (*TokenListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedTokensServer) mustEmbedUnimplementedTokensServer() {}
func (UnimplementedTokensServer) testEmbeddedByValue()                {}

// UnsafeTokensServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokensServer will
// result in compilation errors.
type UnsafeTokensServer interface {
	mustEmbedUnimplementedTokensServer()
}

func RegisterTokensServer(s grpc.ServiceRegistrar, srv TokensServer) {
	// If the following call panics, it indicates UnimplementedTokensServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tokens_ServiceDesc, srv)
}

func _Tokens_Issue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokensServer).Issue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tokens_Issue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokensServer).Issue(ctx, req.(*TokenIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tokens_Revoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRevokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokensServer).Revoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tokens_Revoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokensServer).Revoke(ctx, req.(*TokenRevokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tokens_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokensServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tokens_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokensServer).List(ctx, req.(*TokenListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tokens_ServiceDesc is the grpc.ServiceDesc for Tokens service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tokens_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jaco.v1.Tokens",
	HandlerType: (*TokensServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Issue",
			Handler:    _Tokens_Issue_Handler,
		},
		{
			MethodName: "Revoke",
			Handler:    _Tokens_Revoke_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Tokens_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jaco/v1/services.proto",
}

const (
	RegistryCredentials_Add_FullMethodName    = "/jaco.v1.RegistryCredentials/Add"
	RegistryCredentials_Remove_FullMethodName = "/jaco.v1.RegistryCredentials/Remove"
	RegistryCredentials_List_FullMethodName   = "/jaco.v1.RegistryCredentials/List"
)

// RegistryCredentialsClient is the client API for RegistryCredentials service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RegistryCredentials manages container-registry credentials replicated
// across raft and consumed by every node's image-pull path (issue #101).
// Add/Remove gate on the leader; List reads local state and returns
// summaries — the secret is NEVER on the wire.
type RegistryCredentialsClient interface {
	Add(ctx context.Context, in *RegistryCredentialAddRequest, opts ...grpc.CallOption) (*RegistryCredentialAddResponse, error)
	Remove(ctx context.Context, in *RegistryCredentialRemoveRequest, opts ...grpc.CallOption) (*RegistryCredentialRemoveResponse, error)
	List(ctx context.Context, in *RegistryCredentialListRequest, opts ...grpc.CallOption) (*RegistryCredentialListResponse, error)
}

type registryCredentialsClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistryCredentialsClient(cc grpc.ClientConnInterface) RegistryCredentialsClient {
	return &registryCredentialsClient{cc}
}

func (c *registryCredentialsClient) Add(ctx context.Context, in *RegistryCredentialAddRequest, opts ...grpc.CallOption) (*RegistryCredentialAddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryCredentialAddResponse)
	err := c.cc.Invoke(ctx, RegistryCredentials_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryCredentialsClient) Remove(ctx context.Context, in *RegistryCredentialRemoveRequest, opts ...grpc.CallOption) (*RegistryCredentialRemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryCredentialRemoveResponse)
	err := c.cc.Invoke(ctx, RegistryCredentials_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryCredentialsClient) List(ctx context.Context, in *RegistryCredentialListRequest, opts ...grpc.CallOption) (*RegistryCredentialListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryCredentialListResponse)
	err := c.cc.Invoke(ctx, RegistryCredentials_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryCredentialsServer is the server API for RegistryCredentials service.
// All implementations must embed UnimplementedRegistryCredentialsServer
// for forward compatibility.
//
// RegistryCredentials manages container-registry credentials replicated
// across raft and consumed by every node's image-pull path (issue #101).
// Add/Remove gate on the leader; List reads local state and returns
// summaries — the secret is NEVER on the wire.
type RegistryCredentialsServer interface {
	Add(context.Context, *RegistryCredentialAddRequest) (*RegistryCredentialAddResponse, error)
	Remove(context.Context, *RegistryCredentialRemoveRequest) (*RegistryCredentialRemoveResponse, error)
	List(context.Context, *RegistryCredentialListRequest) (*RegistryCredentialListResponse, error)
	mustEmbedUnimplementedRegistryCredentialsServer()
}

// UnimplementedRegistryCredentialsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistryCredentialsServer struct{}

func (UnimplementedRegistryCredentialsServer) Add(context.Context, *RegistryCredentialAddRequest) (*RegistryCredentialAddResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedRegistryCredentialsServer) Remove(context.Context, *RegistryCredentialRemoveRequest) (*RegistryCredentialRemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedRegistryCredentialsServer) List(context.Context, *RegistryCredentialListRequest) (*RegistryCredentialListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedRegistryCredentialsServer) mustEmbedUnimplementedRegistryCredentialsServer() {}
func (UnimplementedRegistryCredentialsServer) testEmbeddedByValue()                             {}

// UnsafeRegistryCredentialsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistryCredentialsServer will
// result in compilation errors.
type UnsafeRegistryCredentialsServer interface {
	mustEmbedUnimplementedRegistryCredentialsServer()
}

func RegisterRegistryCredentialsServer(s grpc.ServiceRegistrar, srv RegistryCredentialsServer) {
	// If the following call panics, it indicates UnimplementedRegistryCredentialsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegistryCredentials_ServiceDesc, srv)
}

func _RegistryCredentials_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryCredentialAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryCredentialsServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryCredentials_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryCredentialsServer).Add(ctx, req.(*RegistryCredentialAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryCredentials_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryCredentialRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryCredentialsServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryCredentials_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryCredentialsServer).Remove(ctx, req.(*RegistryCredentialRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryCredentials_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryCredentialListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryCredentialsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryCredentials_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryCredentialsServer).List(ctx, req.(*RegistryCredentialListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegistryCredentials_ServiceDesc is the grpc.ServiceDesc for RegistryCredentials service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegistryCredentials_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jaco.v1.RegistryCredentials",
	HandlerType: (*RegistryCredentialsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _RegistryCredentials_Add_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _RegistryCredentials_Remove_Handler,
		},
		{
			MethodName: "List",
			Handler:    _RegistryCredentials_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jaco/v1/services.proto",
}

const (
	Audit_Query_FullMethodName = "/jaco.v1.Audit/Query"
)

// AuditClient is the client API for Audit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuditClient interface {
	Query(ctx context.Context, in *AuditQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuditEvent], error)
}

type auditClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditClient(cc grpc.ClientConnInterface) AuditClient {
	return &auditClient{cc}
}

func (c *auditClient) Query(ctx context.Context, in *AuditQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuditEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Audit_ServiceDesc.Streams[0], Audit_Query_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AuditQueryRequest, AuditEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Audit_QueryClient = grpc.ServerStreamingClient[AuditEvent]

// AuditServer is the server API for Audit service.
// All implementations must embed UnimplementedAuditServer
// for forward compatibility.
type AuditServer interface {
	Query(*AuditQueryRequest, grpc.ServerStreamingServer[AuditEvent]) error
	mustEmbedUnimplementedAuditServer()
}

// UnimplementedAuditServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditServer struct{}

func (UnimplementedAuditServer) Query(*AuditQueryRequest, grpc.ServerStreamingServer[AuditEvent]) error {
	return status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedAuditServer) mustEmbedUnimplementedAuditServer() {}
func (UnimplementedAuditServer) testEmbeddedByValue()               {}

// UnsafeAuditServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditServer will
// result in compilation errors.
type UnsafeAuditServer interface {
	mustEmbedUnimplementedAuditServer()
}

func RegisterAuditServer(s grpc.ServiceRegistrar, srv AuditServer) {
	// If the following call panics, it indicates UnimplementedAuditServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Audit_ServiceDesc, srv)
}

func _Audit_Query_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AuditQueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuditServer).Query(m, &grpc.GenericServerStream[AuditQueryRequest, AuditEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Audit_QueryServer = grpc.ServerStreamingServer[AuditEvent]

// Audit_ServiceDesc is the grpc.ServiceDesc for Audit service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Audit_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jaco.v1.Audit",
	HandlerType: (*AuditServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Query",
			Handler:       _Audit_Query_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "jaco/v1/services.proto",
}

const (
	Watch_Subscribe_FullMethodName = "/jaco.v1.Watch/Subscribe"
)

// WatchClient is the client API for Watch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WatchClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeEvent], error)
}

type watchClient struct {
	cc grpc.ClientConnInterface
}

func NewWatchClient(cc grpc.ClientConnInterface) WatchClient {
	return &watchClient{cc}
}

func (c *watchClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Watch_ServiceDesc.Streams[0], Watch_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SubscribeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Watch_SubscribeClient = grpc.ServerStreamingClient[SubscribeEvent]

// WatchServer is the server API for Watch service.
// All implementations must embed UnimplementedWatchServer
// for forward compatibility.
type WatchServer interface {
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeEvent]) error
	mustEmbedUnimplementedWatchServer()
}

// UnimplementedWatchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWatchServer struct{}

func (UnimplementedWatchServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeEvent]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedWatchServer) mustEmbedUnimplementedWatchServer() {}
func (UnimplementedWatchServer) testEmbeddedByValue()               {}

// UnsafeWatchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WatchServer will
// result in compilation errors.
type UnsafeWatchServer interface {
	mustEmbedUnimplementedWatchServer()
}

func RegisterWatchServer(s grpc.ServiceRegistrar, srv WatchServer) {
	// If the following call panics, it indicates UnimplementedWatchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Watch_ServiceDesc, srv)
}

func _Watch_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WatchServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, SubscribeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Watch_SubscribeServer = grpc.ServerStreamingServer[SubscribeEvent]

// Watch_ServiceDesc is the grpc.ServiceDesc for Watch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Watch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jaco.v1.Watch",
	HandlerType: (*WatchServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Watch_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "jaco/v1/services.proto",
}

const (
	Internal_Submit_FullMethodName       = "/jaco.v1.Internal/Submit"
	Internal_SignNodeCert_FullMethodName = "/jaco.v1.Internal/SignNodeCert"
	Internal_Logs_FullMethodName         = "/jaco.v1.Internal/Logs"
	Internal_EnsureSubnet_FullMethodName = "/jaco.v1.Internal/EnsureSubnet"
)

// InternalClient is the client API for Internal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalClient interface {
	Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error)
	SignNodeCert(ctx context.Context, in *SignNodeCertRequest, opts ...grpc.CallOption) (*SignNodeCertResponse, error)
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error)
	EnsureSubnet(ctx context.Context, in *EnsureSubnetRequest, opts ...grpc.CallOption) (*EnsureSubnetResponse, error)
}

type internalClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalClient(cc grpc.ClientConnInterface) InternalClient {
	return &internalClient{cc}
}

func (c *internalClient) Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, Internal_Submit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) SignNodeCert(ctx context.Context, in *SignNodeCertRequest, opts ...grpc.CallOption) (*SignNodeCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignNodeCertResponse)
	err := c.cc.Invoke(ctx, Internal_SignNodeCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Internal_ServiceDesc.Streams[0], Internal_Logs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogsRequest, LogLine]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Internal_LogsClient = grpc.ServerStreamingClient[LogLine]

func (c *internalClient) EnsureSubnet(ctx context.Context, in *EnsureSubnetRequest, opts ...grpc.CallOption) (*EnsureSubnetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsureSubnetResponse)
	err := c.cc.Invoke(ctx, Internal_EnsureSubnet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalServer is the server API for Internal service.
// All implementations must embed UnimplementedInternalServer
// for forward compatibility.
type InternalServer interface {
	Submit(context.Context, *SubmitRequest) (*SubmitResponse, error)
	SignNodeCert(context.Context, *SignNodeCertRequest) (*SignNodeCertResponse, error)
	Logs(*LogsRequest, grpc.ServerStreamingServer[LogLine]) error
	EnsureSubnet(context.Context, *EnsureSubnetRequest) (*EnsureSubnetResponse, error)
	mustEmbedUnimplementedInternalServer()
}

// UnimplementedInternalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalServer struct{}

func (UnimplementedInternalServer) Submit(context.Context, *SubmitRequest) (*SubmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedInternalServer) SignNodeCert(context.Context, *SignNodeCertRequest) (*SignNodeCertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignNodeCert not implemented")
}
func (UnimplementedInternalServer) Logs(*LogsRequest, grpc.ServerStreamingServer[LogLine]) error {
	return status.Error(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedInternalServer) EnsureSubnet(context.Context, *EnsureSubnetRequest) (*EnsureSubnetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureSubnet not implemented")
}
func (UnimplementedInternalServer) mustEmbedUnimplementedInternalServer() {}
func (UnimplementedInternalServer) testEmbeddedByValue()                  {}

// UnsafeInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalServer will
// result in compilation errors.
type UnsafeInternalServer interface {
	mustEmbedUnimplementedInternalServer()
}

func RegisterInternalServer(s grpc.ServiceRegistrar, srv InternalServer) {
	// If the following call panics, it indicates UnimplementedInternalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Internal_ServiceDesc, srv)
}

func _Internal_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Internal_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).Submit(ctx, req.(*SubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_SignNodeCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignNodeCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).SignNodeCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Internal_SignNodeCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).SignNodeCert(ctx, req.(*SignNodeCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InternalServer).Logs(m, &grpc.GenericServerStream[LogsRequest, LogLine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Internal_LogsServer = grpc.ServerStreamingServer[LogLine]

func _Internal_EnsureSubnet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureSubnetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).EnsureSubnet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Internal_EnsureSubnet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).EnsureSubnet(ctx, req.(*EnsureSubnetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Internal_ServiceDesc is the grpc.ServiceDesc for Internal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Internal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jaco.v1.Internal",
	HandlerType: (*InternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _Internal_Submit_Handler,
		},
		{
			MethodName: "SignNodeCert",
			Handler:    _Internal_SignNodeCert_Handler,
		},
		{
			MethodName: "EnsureSubnet",
			Handler:    _Internal_EnsureSubnet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Logs",
			Handler:       _Internal_Logs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "jaco/v1/services.proto",
}
