// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jaco/v1/services.proto

package jacov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BootstrapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapRequest) Reset() {
	*x = BootstrapRequest{}
	mi := &file_jaco_v1_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapRequest) ProtoMessage() {}

func (x *BootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapRequest.ProtoReflect.Descriptor instead.
func (*BootstrapRequest) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{0}
}

func (x *BootstrapRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BootstrapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	OperatorToken string                 `protobuf:"bytes,2,opt,name=operator_token,json=operatorToken,proto3" json:"operator_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapResponse) Reset() {
	*x = BootstrapResponse{}
	mi := &file_jaco_v1_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapResponse) ProtoMessage() {}

func (x *BootstrapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapResponse.ProtoReflect.Descriptor instead.
func (*BootstrapResponse) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{1}
}

func (x *BootstrapResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *BootstrapResponse) GetOperatorToken() string {
	if x != nil {
		return x.OperatorToken
	}
	return ""
}

type IssueJoinTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueJoinTokenRequest) Reset() {
	*x = IssueJoinTokenRequest{}
	mi := &file_jaco_v1_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueJoinTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueJoinTokenRequest) ProtoMessage() {}

func (x *IssueJoinTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueJoinTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueJoinTokenRequest) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{2}
}

type IssueJoinTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CaCert        []byte                 `protobuf:"bytes,2,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	LeaderAddrs   []string               `protobuf:"bytes,3,rep,name=leader_addrs,json=leaderAddrs,proto3" json:"leader_addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueJoinTokenResponse) Reset() {
	*x = IssueJoinTokenResponse{}
	mi := &file_jaco_v1_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueJoinTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueJoinTokenResponse) ProtoMessage() {}

func (x *IssueJoinTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueJoinTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueJoinTokenResponse) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{3}
}

func (x *IssueJoinTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *IssueJoinTokenResponse) GetCaCert() []byte {
	if x != nil {
		return x.CaCert
	}
	return nil
}

func (x *IssueJoinTokenResponse) GetLeaderAddrs() []string {
	if x != nil {
		return x.LeaderAddrs
	}
	return nil
}

type NodeJoinRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	JoinToken       string                 `protobuf:"bytes,2,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	CsrPem          []byte                 `protobuf:"bytes,3,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	AdvertiseAddr   string                 `protobuf:"bytes,4,opt,name=advertise_addr,json=advertiseAddr,proto3" json:"advertise_addr,omitempty"`
	WireguardPubkey []byte                 `protobuf:"bytes,5,opt,name=wireguard_pubkey,json=wireguardPubkey,proto3" json:"wireguard_pubkey,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeJoinRequest) Reset() {
	*x = NodeJoinRequest{}
	mi := &file_jaco_v1_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeJoinRequest) ProtoMessage() {}

func (x *NodeJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeJoinRequest.ProtoReflect.Descriptor instead.
func (*NodeJoinRequest) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{4}
}

func (x *NodeJoinRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeJoinRequest) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

func (x *NodeJoinRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

func (x *NodeJoinRequest) GetAdvertiseAddr() string {
	if x != nil {
		return x.AdvertiseAddr
	}
	return ""
}

func (x *NodeJoinRequest) GetWireguardPubkey() []byte {
	if x != nil {
		return x.WireguardPubkey
	}
	return nil
}

type NodeJoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	SignedCert    []byte                 `protobuf:"bytes,2,opt,name=signed_cert,json=signedCert,proto3" json:"signed_cert,omitempty"`
	CaCert        []byte                 `protobuf:"bytes,3,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	PeerAddrs     []string               `protobuf:"bytes,4,rep,name=peer_addrs,json=peerAddrs,proto3" json:"peer_addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeJoinResponse) Reset() {
	*x = NodeJoinResponse{}
	mi := &file_jaco_v1_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeJoinResponse) ProtoMessage() {}

func (x *NodeJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeJoinResponse.ProtoReflect.Descriptor instead.
func (*NodeJoinResponse) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{5}
}

func (x *NodeJoinResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *NodeJoinResponse) GetSignedCert() []byte {
	if x != nil {
		return x.SignedCert
	}
	return nil
}

func (x *NodeJoinResponse) GetCaCert() []byte {
	if x != nil {
		return x.CaCert
	}
	return nil
}

func (x *NodeJoinResponse) GetPeerAddrs() []string {
	if x != nil {
		return x.PeerAddrs
	}
	return nil
}

type NodeRemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRemoveRequest) Reset() {
	*x = NodeRemoveRequest{}
	mi := &file_jaco_v1_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRemoveRequest) ProtoMessage() {}

func (x *NodeRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRemoveRequest.ProtoReflect.Descriptor instead.
func (*NodeRemoveRequest) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{6}
}

func (x *NodeRemoveRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeRemoveRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type NodeRemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRemoveResponse) Reset() {
	*x = NodeRemoveResponse{}
	mi := &file_jaco_v1_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRemoveResponse) ProtoMessage() {}

func (x *NodeRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRemoveResponse.ProtoReflect.Descriptor instead.
func (*NodeRemoveResponse) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{7}
}

type NodeListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeListRequest) Reset() {
	*x = NodeListRequest{}
	mi := &file_jaco_v1_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeListRequest) ProtoMessage() {}

func (x *NodeListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeListRequest.ProtoReflect.Descriptor instead.
func (*NodeListRequest) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{8}
}

type NodeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeListResponse) Reset() {
	*x = NodeListResponse{}
	mi := &file_jaco_v1_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeListResponse) ProtoMessage() {}

func (x *NodeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeListResponse.ProtoReflect.Descriptor instead.
func (*NodeListResponse) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{9}
}

func (x *NodeListResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type BackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupRequest) Reset() {
	*x = BackupRequest{}
	mi := &file_jaco_v1_services_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest) ProtoMessage() {}

func (x *BackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRequest.ProtoReflect.Descriptor instead.
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{10}
}

type BackupChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupChunk) Reset() {
	*x = BackupChunk{}
	mi := &file_jaco_v1_services_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupChunk) ProtoMessage() {}

func (x *BackupChunk) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupChunk.ProtoReflect.Descriptor instead.
func (*BackupChunk) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{11}
}

func (x *BackupChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	SnapshotIndex uint64                 `protobuf:"varint,2,opt,name=snapshot_index,json=snapshotIndex,proto3" json:"snapshot_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_jaco_v1_services_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{12}
}

func (x *RestoreResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *RestoreResponse) GetSnapshotIndex() uint64 {
	if x != nil {
		return x.SnapshotIndex
	}
	return 0
}

type ClusterStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterStatusRequest) Reset() {
	*x = ClusterStatusRequest{}
	mi := &file_jaco_v1_services_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatusRequest) ProtoMessage() {}

func (x *ClusterStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatusRequest.ProtoReflect.Descriptor instead.
func (*ClusterStatusRequest) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{13}
}

type ClusterStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Leader        string                 `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	RaftIndex     uint64                 `protobuf:"varint,3,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterStatusResponse) Reset() {
	*x = ClusterStatusResponse{}
	mi := &file_jaco_v1_services_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatusResponse) ProtoMessage() {}

func (x *ClusterStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatusResponse.ProtoReflect.Descriptor instead.
func (*ClusterStatusResponse) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{14}
}

func (x *ClusterStatusResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ClusterStatusResponse) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

func (x *ClusterStatusResponse) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

type ApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JacoYaml      []byte                 `protobuf:"bytes,1,opt,name=jaco_yaml,json=jacoYaml,proto3" json:"jaco_yaml,omitempty"`
	ComposeYaml   []byte                 `protobuf:"bytes,2,opt,name=compose_yaml,json=composeYaml,proto3" json:"compose_yaml,omitempty"`
	DryRun        bool                   `protobuf:"varint,3,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_jaco_v1_services_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{15}
}

func (x *ApplyRequest) GetJacoYaml() []byte {
	if x != nil {
		return x.JacoYaml
	}
	return nil
}

func (x *ApplyRequest) GetComposeYaml() []byte {
	if x != nil {
		return x.ComposeYaml
	}
	return nil
}

func (x *ApplyRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type ApplyResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AppliedRevision uint64                 `protobuf:"varint,1,opt,name=applied_revision,json=appliedRevision,proto3" json:"applied_revision,omitempty"`
	Diff            *Diff                  `protobuf:"bytes,2,opt,name=diff,proto3" json:"diff,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_jaco_v1_services_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{16}
}

func (x *ApplyResponse) GetAppliedRevision() uint64 {
	if x != nil {
		return x.AppliedRevision
	}
	return 0
}

func (x *ApplyResponse) GetDiff() *Diff {
	if x != nil {
		return x.Diff
	}
	return nil
}

type Diff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Adds          []string               `protobuf:"bytes,1,rep,name=adds,proto3" json:"adds,omitempty"`
	Updates       []string               `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty"`
	Removes       []string               `protobuf:"bytes,3,rep,name=removes,proto3" json:"removes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diff) Reset() {
	*x = Diff{}
	mi := &file_jaco_v1_services_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diff) ProtoMessage() {}

func (x *Diff) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diff.ProtoReflect.Descriptor instead.
func (*Diff) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{17}
}

func (x *Diff) GetAdds() []string {
	if x != nil {
		return x.Adds
	}
	return nil
}

func (x *Diff) GetUpdates() []string {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *Diff) GetRemoves() []string {
	if x != nil {
		return x.Removes
	}
	return nil
}

type RollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    string                 `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_jaco_v1_services_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{18}
}

func (x *RollbackRequest) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

type RollbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackResponse) Reset() {
	*x = RollbackResponse{}
	mi := &file_jaco_v1_services_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResponse) ProtoMessage() {}

func (x *RollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResponse.ProtoReflect.Descriptor instead.
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{19}
}

func (x *RollbackResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    string                 `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_jaco_v1_services_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteRequest) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_jaco_v1_services_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{21}
}

type DeployStatusRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeploymentFilter string                 `protobuf:"bytes,1,opt,name=deployment_filter,json=deploymentFilter,proto3" json:"deployment_filter,omitempty"`
	ServiceFilter    string                 `protobuf:"bytes,2,opt,name=service_filter,json=serviceFilter,proto3" json:"service_filter,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeployStatusRequest) Reset() {
	*x = DeployStatusRequest{}
	mi := &file_jaco_v1_services_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployStatusRequest) ProtoMessage() {}

func (x *DeployStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployStatusRequest.ProtoReflect.Descriptor instead.
func (*DeployStatusRequest) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{22}
}

func (x *DeployStatusRequest) GetDeploymentFilter() string {
	if x != nil {
		return x.DeploymentFilter
	}
	return ""
}

func (x *DeployStatusRequest) GetServiceFilter() string {
	if x != nil {
		return x.ServiceFilter
	}
	return ""
}

type DeployStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployments   []*Deployment          `protobuf:"bytes,1,rep,name=deployments,proto3" json:"deployments,omitempty"`
	Replicas      []*ReplicaObserved     `protobuf:"bytes,2,rep,name=replicas,proto3" json:"replicas,omitempty"`
	Routes        []*Route               `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployStatusResponse) Reset() {
	*x = DeployStatusResponse{}
	mi := &file_jaco_v1_services_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployStatusResponse) ProtoMessage() {}

func (x *DeployStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployStatusResponse.ProtoReflect.Descriptor instead.
func (*DeployStatusResponse) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{23}
}

func (x *DeployStatusResponse) GetDeployments() []*Deployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

func (x *DeployStatusResponse) GetReplicas() []*ReplicaObserved {
	if x != nil {
		return x.Replicas
	}
	return nil
}

func (x *DeployStatusResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type LogsRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Deployment   string                 `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Service      string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Follow       bool                   `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`
	SinceSeconds int64                  `protobuf:"varint,4,opt,name=since_seconds,json=sinceSeconds,proto3" json:"since_seconds,omitempty"`
	// Replica-scoped lookup used by Internal.Logs (peer RPC) — Deploy.Logs
	// (CLI entry) leaves this empty and uses deployment + service.
	ReplicaId     string `protobuf:"bytes,5,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_jaco_v1_services_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{24}
}

func (x *LogsRequest) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

func (x *LogsRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogsRequest) GetSinceSeconds() int64 {
	if x != nil {
		return x.SinceSeconds
	}
	return 0
}

func (x *LogsRequest) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicaId     string                 `protobuf:"bytes,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Stream        string                 `protobuf:"bytes,3,opt,name=stream,proto3" json:"stream,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ts,proto3" json:"ts,omitempty"`
	Line          string                 `protobuf:"bytes,5,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_jaco_v1_services_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{25}
}

func (x *LogLine) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *LogLine) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *LogLine) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogLine) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *LogLine) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

type TokenIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenIssueRequest) Reset() {
	*x = TokenIssueRequest{}
	mi := &file_jaco_v1_services_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenIssueRequest) ProtoMessage() {}

func (x *TokenIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenIssueRequest.ProtoReflect.Descriptor instead.
func (*TokenIssueRequest) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{26}
}

func (x *TokenIssueRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type TokenIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenIssueResponse) Reset() {
	*x = TokenIssueResponse{}
	mi := &file_jaco_v1_services_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenIssueResponse) ProtoMessage() {}

func (x *TokenIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenIssueResponse.ProtoReflect.Descriptor instead.
func (*TokenIssueResponse) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{27}
}

func (x *TokenIssueResponse) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *TokenIssueResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenIssueResponse) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

type TokenRevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRevokeRequest) Reset() {
	*x = TokenRevokeRequest{}
	mi := &file_jaco_v1_services_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRevokeRequest) ProtoMessage() {}

func (x *TokenRevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRevokeRequest.ProtoReflect.Descriptor instead.
func (*TokenRevokeRequest) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{28}
}

func (x *TokenRevokeRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type TokenRevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRevokeResponse) Reset() {
	*x = TokenRevokeResponse{}
	mi := &file_jaco_v1_services_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRevokeResponse) ProtoMessage() {}

func (x *TokenRevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRevokeResponse.ProtoReflect.Descriptor instead.
func (*TokenRevokeResponse) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{29}
}

type TokenListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenListRequest) Reset() {
	*x = TokenListRequest{}
	mi := &file_jaco_v1_services_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenListRequest) ProtoMessage() {}

func (x *TokenListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenListRequest.ProtoReflect.Descriptor instead.
func (*TokenListRequest) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{30}
}

type TokenListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*TokenInfo           `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenListResponse) Reset() {
	*x = TokenListResponse{}
	mi := &file_jaco_v1_services_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenListResponse) ProtoMessage() {}

func (x *TokenListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenListResponse.ProtoReflect.Descriptor instead.
func (*TokenListResponse) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{31}
}

func (x *TokenListResponse) GetTokens() []*TokenInfo {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type TokenInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenInfo) Reset() {
	*x = TokenInfo{}
	mi := &file_jaco_v1_services_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenInfo) ProtoMessage() {}

func (x *TokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenInfo.ProtoReflect.Descriptor instead.
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{32}
}

func (x *TokenInfo) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *TokenInfo) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *TokenInfo) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

type AuditQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=since,proto3" json:"since,omitempty"`
	Until         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=until,proto3" json:"until,omitempty"`
	Types         []AuditEventType       `protobuf:"varint,3,rep,packed,name=types,proto3,enum=jaco.v1.AuditEventType" json:"types,omitempty"`
	Follow        bool                   `protobuf:"varint,4,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditQueryRequest) Reset() {
	*x = AuditQueryRequest{}
	mi := &file_jaco_v1_services_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditQueryRequest) ProtoMessage() {}

func (x *AuditQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditQueryRequest.ProtoReflect.Descriptor instead.
func (*AuditQueryRequest) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{33}
}

func (x *AuditQueryRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *AuditQueryRequest) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

func (x *AuditQueryRequest) GetTypes() []AuditEventType {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *AuditQueryRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type SubscribeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EntityTypes      []string               `protobuf:"bytes,1,rep,name=entity_types,json=entityTypes,proto3" json:"entity_types,omitempty"`
	SinceRevision    uint64                 `protobuf:"varint,2,opt,name=since_revision,json=sinceRevision,proto3" json:"since_revision,omitempty"`
	DeploymentFilter string                 `protobuf:"bytes,3,opt,name=deployment_filter,json=deploymentFilter,proto3" json:"deployment_filter,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_jaco_v1_services_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{34}
}

func (x *SubscribeRequest) GetEntityTypes() []string {
	if x != nil {
		return x.EntityTypes
	}
	return nil
}

func (x *SubscribeRequest) GetSinceRevision() uint64 {
	if x != nil {
		return x.SinceRevision
	}
	return 0
}

func (x *SubscribeRequest) GetDeploymentFilter() string {
	if x != nil {
		return x.DeploymentFilter
	}
	return ""
}

type SubscribeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SubscribeEvent_Node
	//	*SubscribeEvent_Deployment
	//	*SubscribeEvent_ReplicaDesired
	//	*SubscribeEvent_ReplicaObserved
	//	*SubscribeEvent_Route
	//	*SubscribeEvent_Cert
	//	*SubscribeEvent_ChallengeToken
	//	*SubscribeEvent_Token
	//	*SubscribeEvent_JoinToken
	//	*SubscribeEvent_Audit
	//	*SubscribeEvent_Subnet
	//	*SubscribeEvent_RolloutPlan
	//	*SubscribeEvent_ReplicaCounter
	//	*SubscribeEvent_RestartCounter
	Payload       isSubscribeEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEvent) Reset() {
	*x = SubscribeEvent{}
	mi := &file_jaco_v1_services_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEvent) ProtoMessage() {}

func (x *SubscribeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEvent.ProtoReflect.Descriptor instead.
func (*SubscribeEvent) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{35}
}

func (x *SubscribeEvent) GetPayload() isSubscribeEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SubscribeEvent) GetNode() *NodeEvent {
	if x != nil {
		if x, ok := x.Payload.(*SubscribeEvent_Node); ok {
			return x.Node
		}
	}
	return nil
}

func (x *SubscribeEvent) GetDeployment() *DeploymentEvent {
	if x != nil {
		if x, ok := x.Payload.(*SubscribeEvent_Deployment); ok {
			return x.Deployment
		}
	}
	return nil
}

func (x *SubscribeEvent) GetReplicaDesired() *ReplicaDesiredEvent {
	if x != nil {
		if x, ok := x.Payload.(*SubscribeEvent_ReplicaDesired); ok {
			return x.ReplicaDesired
		}
	}
	return nil
}

func (x *SubscribeEvent) GetReplicaObserved() *ReplicaObservedEvent {
	if x != nil {
		if x, ok := x.Payload.(*SubscribeEvent_ReplicaObserved); ok {
			return x.ReplicaObserved
		}
	}
	return nil
}

func (x *SubscribeEvent) GetRoute() *RouteEvent {
	if x != nil {
		if x, ok := x.Payload.(*SubscribeEvent_Route); ok {
			return x.Route
		}
	}
	return nil
}

func (x *SubscribeEvent) GetCert() *CertEvent {
	if x != nil {
		if x, ok := x.Payload.(*SubscribeEvent_Cert); ok {
			return x.Cert
		}
	}
	return nil
}

func (x *SubscribeEvent) GetChallengeToken() *ChallengeTokenEvent {
	if x != nil {
		if x, ok := x.Payload.(*SubscribeEvent_ChallengeToken); ok {
			return x.ChallengeToken
		}
	}
	return nil
}

func (x *SubscribeEvent) GetToken() *TokenEvent {
	if x != nil {
		if x, ok := x.Payload.(*SubscribeEvent_Token); ok {
			return x.Token
		}
	}
	return nil
}

func (x *SubscribeEvent) GetJoinToken() *JoinTokenEvent {
	if x != nil {
		if x, ok := x.Payload.(*SubscribeEvent_JoinToken); ok {
			return x.JoinToken
		}
	}
	return nil
}

func (x *SubscribeEvent) GetAudit() *AuditLogEvent {
	if x != nil {
		if x, ok := x.Payload.(*SubscribeEvent_Audit); ok {
			return x.Audit
		}
	}
	return nil
}

func (x *SubscribeEvent) GetSubnet() *SubnetEvent {
	if x != nil {
		if x, ok := x.Payload.(*SubscribeEvent_Subnet); ok {
			return x.Subnet
		}
	}
	return nil
}

func (x *SubscribeEvent) GetRolloutPlan() *RolloutPlanEvent {
	if x != nil {
		if x, ok := x.Payload.(*SubscribeEvent_RolloutPlan); ok {
			return x.RolloutPlan
		}
	}
	return nil
}

func (x *SubscribeEvent) GetReplicaCounter() *ReplicaCounterEvent {
	if x != nil {
		if x, ok := x.Payload.(*SubscribeEvent_ReplicaCounter); ok {
			return x.ReplicaCounter
		}
	}
	return nil
}

func (x *SubscribeEvent) GetRestartCounter() *RestartCounterEvent {
	if x != nil {
		if x, ok := x.Payload.(*SubscribeEvent_RestartCounter); ok {
			return x.RestartCounter
		}
	}
	return nil
}

type isSubscribeEvent_Payload interface {
	isSubscribeEvent_Payload()
}

type SubscribeEvent_Node struct {
	Node *NodeEvent `protobuf:"bytes,1,opt,name=node,proto3,oneof"`
}

type SubscribeEvent_Deployment struct {
	Deployment *DeploymentEvent `protobuf:"bytes,2,opt,name=deployment,proto3,oneof"`
}

type SubscribeEvent_ReplicaDesired struct {
	ReplicaDesired *ReplicaDesiredEvent `protobuf:"bytes,3,opt,name=replica_desired,json=replicaDesired,proto3,oneof"`
}

type SubscribeEvent_ReplicaObserved struct {
	ReplicaObserved *ReplicaObservedEvent `protobuf:"bytes,4,opt,name=replica_observed,json=replicaObserved,proto3,oneof"`
}

type SubscribeEvent_Route struct {
	Route *RouteEvent `protobuf:"bytes,5,opt,name=route,proto3,oneof"`
}

type SubscribeEvent_Cert struct {
	Cert *CertEvent `protobuf:"bytes,6,opt,name=cert,proto3,oneof"`
}

type SubscribeEvent_ChallengeToken struct {
	ChallengeToken *ChallengeTokenEvent `protobuf:"bytes,7,opt,name=challenge_token,json=challengeToken,proto3,oneof"`
}

type SubscribeEvent_Token struct {
	Token *TokenEvent `protobuf:"bytes,8,opt,name=token,proto3,oneof"`
}

type SubscribeEvent_JoinToken struct {
	JoinToken *JoinTokenEvent `protobuf:"bytes,9,opt,name=join_token,json=joinToken,proto3,oneof"`
}

type SubscribeEvent_Audit struct {
	Audit *AuditLogEvent `protobuf:"bytes,10,opt,name=audit,proto3,oneof"`
}

type SubscribeEvent_Subnet struct {
	Subnet *SubnetEvent `protobuf:"bytes,11,opt,name=subnet,proto3,oneof"`
}

type SubscribeEvent_RolloutPlan struct {
	RolloutPlan *RolloutPlanEvent `protobuf:"bytes,12,opt,name=rollout_plan,json=rolloutPlan,proto3,oneof"`
}

type SubscribeEvent_ReplicaCounter struct {
	ReplicaCounter *ReplicaCounterEvent `protobuf:"bytes,13,opt,name=replica_counter,json=replicaCounter,proto3,oneof"`
}

type SubscribeEvent_RestartCounter struct {
	RestartCounter *RestartCounterEvent `protobuf:"bytes,14,opt,name=restart_counter,json=restartCounter,proto3,oneof"`
}

func (*SubscribeEvent_Node) isSubscribeEvent_Payload() {}

func (*SubscribeEvent_Deployment) isSubscribeEvent_Payload() {}

func (*SubscribeEvent_ReplicaDesired) isSubscribeEvent_Payload() {}

func (*SubscribeEvent_ReplicaObserved) isSubscribeEvent_Payload() {}

func (*SubscribeEvent_Route) isSubscribeEvent_Payload() {}

func (*SubscribeEvent_Cert) isSubscribeEvent_Payload() {}

func (*SubscribeEvent_ChallengeToken) isSubscribeEvent_Payload() {}

func (*SubscribeEvent_Token) isSubscribeEvent_Payload() {}

func (*SubscribeEvent_JoinToken) isSubscribeEvent_Payload() {}

func (*SubscribeEvent_Audit) isSubscribeEvent_Payload() {}

func (*SubscribeEvent_Subnet) isSubscribeEvent_Payload() {}

func (*SubscribeEvent_RolloutPlan) isSubscribeEvent_Payload() {}

func (*SubscribeEvent_ReplicaCounter) isSubscribeEvent_Payload() {}

func (*SubscribeEvent_RestartCounter) isSubscribeEvent_Payload() {}

type SubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandBytes  []byte                 `protobuf:"bytes,1,opt,name=command_bytes,json=commandBytes,proto3" json:"command_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_jaco_v1_services_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{36}
}

func (x *SubmitRequest) GetCommandBytes() []byte {
	if x != nil {
		return x.CommandBytes
	}
	return nil
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RaftIndex     uint64                 `protobuf:"varint,1,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_jaco_v1_services_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{37}
}

func (x *SubmitResponse) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

type SignNodeCertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	CsrPem        []byte                 `protobuf:"bytes,2,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignNodeCertRequest) Reset() {
	*x = SignNodeCertRequest{}
	mi := &file_jaco_v1_services_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignNodeCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignNodeCertRequest) ProtoMessage() {}

func (x *SignNodeCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignNodeCertRequest.ProtoReflect.Descriptor instead.
func (*SignNodeCertRequest) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{38}
}

func (x *SignNodeCertRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SignNodeCertRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

type SignNodeCertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignedCert    []byte                 `protobuf:"bytes,1,opt,name=signed_cert,json=signedCert,proto3" json:"signed_cert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignNodeCertResponse) Reset() {
	*x = SignNodeCertResponse{}
	mi := &file_jaco_v1_services_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignNodeCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignNodeCertResponse) ProtoMessage() {}

func (x *SignNodeCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jaco_v1_services_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignNodeCertResponse.ProtoReflect.Descriptor instead.
func (*SignNodeCertResponse) Descriptor() ([]byte, []int) {
	return file_jaco_v1_services_proto_rawDescGZIP(), []int{39}
}

func (x *SignNodeCertResponse) GetSignedCert() []byte {
	if x != nil {
		return x.SignedCert
	}
	return nil
}

var File_jaco_v1_services_proto protoreflect.FileDescriptor

const file_jaco_v1_services_proto_rawDesc = "" +
	"\n" +
	"\x16jaco/v1/services.proto\x12\ajaco.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16jaco/v1/entities.proto\x1a\x14jaco/v1/events.proto\"&\n" +
	"\x10BootstrapRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"Y\n" +
	"\x11BootstrapResponse\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12%\n" +
	"\x0eoperator_token\x18\x02 \x01(\tR\roperatorToken\"\x17\n" +
	"\x15IssueJoinTokenRequest\"j\n" +
	"\x16IssueJoinTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\aca_cert\x18\x02 \x01(\fR\x06caCert\x12!\n" +
	"\fleader_addrs\x18\x03 \x03(\tR\vleaderAddrs\"\xaf\x01\n" +
	"\x0fNodeJoinRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"join_token\x18\x02 \x01(\tR\tjoinToken\x12\x17\n" +
	"\acsr_pem\x18\x03 \x01(\fR\x06csrPem\x12%\n" +
	"\x0eadvertise_addr\x18\x04 \x01(\tR\radvertiseAddr\x12)\n" +
	"\x10wireguard_pubkey\x18\x05 \x01(\fR\x0fwireguardPubkey\"\x8a\x01\n" +
	"\x10NodeJoinResponse\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1f\n" +
	"\vsigned_cert\x18\x02 \x01(\fR\n" +
	"signedCert\x12\x17\n" +
	"\aca_cert\x18\x03 \x01(\fR\x06caCert\x12\x1d\n" +
	"\n" +
	"peer_addrs\x18\x04 \x03(\tR\tpeerAddrs\"E\n" +
	"\x11NodeRemoveRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\x14\n" +
	"\x12NodeRemoveResponse\"\x11\n" +
	"\x0fNodeListRequest\"7\n" +
	"\x10NodeListResponse\x12#\n" +
	"\x05nodes\x18\x01 \x03(\v2\r.jaco.v1.NodeR\x05nodes\"\x0f\n" +
	"\rBackupRequest\"!\n" +
	"\vBackupChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"W\n" +
	"\x0fRestoreResponse\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12%\n" +
	"\x0esnapshot_index\x18\x02 \x01(\x04R\rsnapshotIndex\"\x16\n" +
	"\x14ClusterStatusRequest\"s\n" +
	"\x15ClusterStatusResponse\x12#\n" +
	"\x05nodes\x18\x01 \x03(\v2\r.jaco.v1.NodeR\x05nodes\x12\x16\n" +
	"\x06leader\x18\x02 \x01(\tR\x06leader\x12\x1d\n" +
	"\n" +
	"raft_index\x18\x03 \x01(\x04R\traftIndex\"g\n" +
	"\fApplyRequest\x12\x1b\n" +
	"\tjaco_yaml\x18\x01 \x01(\fR\bjacoYaml\x12!\n" +
	"\fcompose_yaml\x18\x02 \x01(\fR\vcomposeYaml\x12\x17\n" +
	"\adry_run\x18\x03 \x01(\bR\x06dryRun\"]\n" +
	"\rApplyResponse\x12)\n" +
	"\x10applied_revision\x18\x01 \x01(\x04R\x0fappliedRevision\x12!\n" +
	"\x04diff\x18\x02 \x01(\v2\r.jaco.v1.DiffR\x04diff\"N\n" +
	"\x04Diff\x12\x12\n" +
	"\x04adds\x18\x01 \x03(\tR\x04adds\x12\x18\n" +
	"\aupdates\x18\x02 \x03(\tR\aupdates\x12\x18\n" +
	"\aremoves\x18\x03 \x03(\tR\aremoves\"1\n" +
	"\x0fRollbackRequest\x12\x1e\n" +
	"\n" +
	"deployment\x18\x01 \x01(\tR\n" +
	"deployment\".\n" +
	"\x10RollbackResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\"/\n" +
	"\rDeleteRequest\x12\x1e\n" +
	"\n" +
	"deployment\x18\x01 \x01(\tR\n" +
	"deployment\"\x10\n" +
	"\x0eDeleteResponse\"i\n" +
	"\x13DeployStatusRequest\x12+\n" +
	"\x11deployment_filter\x18\x01 \x01(\tR\x10deploymentFilter\x12%\n" +
	"\x0eservice_filter\x18\x02 \x01(\tR\rserviceFilter\"\xab\x01\n" +
	"\x14DeployStatusResponse\x125\n" +
	"\vdeployments\x18\x01 \x03(\v2\x13.jaco.v1.DeploymentR\vdeployments\x124\n" +
	"\breplicas\x18\x02 \x03(\v2\x18.jaco.v1.ReplicaObservedR\breplicas\x12&\n" +
	"\x06routes\x18\x03 \x03(\v2\x0e.jaco.v1.RouteR\x06routes\"\xa3\x01\n" +
	"\vLogsRequest\x12\x1e\n" +
	"\n" +
	"deployment\x18\x01 \x01(\tR\n" +
	"deployment\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\x12#\n" +
	"\rsince_seconds\x18\x04 \x01(\x03R\fsinceSeconds\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x05 \x01(\tR\treplicaId\"\x94\x01\n" +
	"\aLogLine\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\tR\treplicaId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x16\n" +
	"\x06stream\x18\x03 \x01(\tR\x06stream\x12*\n" +
	"\x02ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x12\n" +
	"\x04line\x18\x05 \x01(\tR\x04line\"/\n" +
	"\x11TokenIssueRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\"\x7f\n" +
	"\x12TokenIssueResponse\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x127\n" +
	"\tissued_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\"0\n" +
	"\x12TokenRevokeRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\"\x15\n" +
	"\x13TokenRevokeResponse\"\x12\n" +
	"\x10TokenListRequest\"?\n" +
	"\x11TokenListResponse\x12*\n" +
	"\x06tokens\x18\x01 \x03(\v2\x12.jaco.v1.TokenInfoR\x06tokens\"\x9b\x01\n" +
	"\tTokenInfo\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x127\n" +
	"\tissued_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"revoked_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\"\xbe\x01\n" +
	"\x11AuditQueryRequest\x120\n" +
	"\x05since\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x120\n" +
	"\x05until\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05until\x12-\n" +
	"\x05types\x18\x03 \x03(\x0e2\x17.jaco.v1.AuditEventTypeR\x05types\x12\x16\n" +
	"\x06follow\x18\x04 \x01(\bR\x06follow\"\x89\x01\n" +
	"\x10SubscribeRequest\x12!\n" +
	"\fentity_types\x18\x01 \x03(\tR\ventityTypes\x12%\n" +
	"\x0esince_revision\x18\x02 \x01(\x04R\rsinceRevision\x12+\n" +
	"\x11deployment_filter\x18\x03 \x01(\tR\x10deploymentFilter\"\xcf\x06\n" +
	"\x0eSubscribeEvent\x12(\n" +
	"\x04node\x18\x01 \x01(\v2\x12.jaco.v1.NodeEventH\x00R\x04node\x12:\n" +
	"\n" +
	"deployment\x18\x02 \x01(\v2\x18.jaco.v1.DeploymentEventH\x00R\n" +
	"deployment\x12G\n" +
	"\x0freplica_desired\x18\x03 \x01(\v2\x1c.jaco.v1.ReplicaDesiredEventH\x00R\x0ereplicaDesired\x12J\n" +
	"\x10replica_observed\x18\x04 \x01(\v2\x1d.jaco.v1.ReplicaObservedEventH\x00R\x0freplicaObserved\x12+\n" +
	"\x05route\x18\x05 \x01(\v2\x13.jaco.v1.RouteEventH\x00R\x05route\x12(\n" +
	"\x04cert\x18\x06 \x01(\v2\x12.jaco.v1.CertEventH\x00R\x04cert\x12G\n" +
	"\x0fchallenge_token\x18\a \x01(\v2\x1c.jaco.v1.ChallengeTokenEventH\x00R\x0echallengeToken\x12+\n" +
	"\x05token\x18\b \x01(\v2\x13.jaco.v1.TokenEventH\x00R\x05token\x128\n" +
	"\n" +
	"join_token\x18\t \x01(\v2\x17.jaco.v1.JoinTokenEventH\x00R\tjoinToken\x12.\n" +
	"\x05audit\x18\n" +
	" \x01(\v2\x16.jaco.v1.AuditLogEventH\x00R\x05audit\x12.\n" +
	"\x06subnet\x18\v \x01(\v2\x14.jaco.v1.SubnetEventH\x00R\x06subnet\x12>\n" +
	"\frollout_plan\x18\f \x01(\v2\x19.jaco.v1.RolloutPlanEventH\x00R\vrolloutPlan\x12G\n" +
	"\x0freplica_counter\x18\r \x01(\v2\x1c.jaco.v1.ReplicaCounterEventH\x00R\x0ereplicaCounter\x12G\n" +
	"\x0frestart_counter\x18\x0e \x01(\v2\x1c.jaco.v1.RestartCounterEventH\x00R\x0erestartCounterB\t\n" +
	"\apayload\"4\n" +
	"\rSubmitRequest\x12#\n" +
	"\rcommand_bytes\x18\x01 \x01(\fR\fcommandBytes\"/\n" +
	"\x0eSubmitResponse\x12\x1d\n" +
	"\n" +
	"raft_index\x18\x01 \x01(\x04R\traftIndex\"J\n" +
	"\x13SignNodeCertRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x17\n" +
	"\acsr_pem\x18\x02 \x01(\fR\x06csrPem\"7\n" +
	"\x14SignNodeCertResponse\x12\x1f\n" +
	"\vsigned_cert\x18\x01 \x01(\fR\n" +
	"signedCert2\xa9\x04\n" +
	"\aCluster\x12B\n" +
	"\tBootstrap\x12\x19.jaco.v1.BootstrapRequest\x1a\x1a.jaco.v1.BootstrapResponse\x12Q\n" +
	"\x0eIssueJoinToken\x12\x1e.jaco.v1.IssueJoinTokenRequest\x1a\x1f.jaco.v1.IssueJoinTokenResponse\x12?\n" +
	"\bNodeJoin\x12\x18.jaco.v1.NodeJoinRequest\x1a\x19.jaco.v1.NodeJoinResponse\x12E\n" +
	"\n" +
	"NodeRemove\x12\x1a.jaco.v1.NodeRemoveRequest\x1a\x1b.jaco.v1.NodeRemoveResponse\x12?\n" +
	"\bNodeList\x12\x18.jaco.v1.NodeListRequest\x1a\x19.jaco.v1.NodeListResponse\x128\n" +
	"\x06Backup\x12\x16.jaco.v1.BackupRequest\x1a\x14.jaco.v1.BackupChunk0\x01\x12;\n" +
	"\aRestore\x12\x14.jaco.v1.BackupChunk\x1a\x18.jaco.v1.RestoreResponse(\x01\x12G\n" +
	"\x06Status\x12\x1d.jaco.v1.ClusterStatusRequest\x1a\x1e.jaco.v1.ClusterStatusResponse2\xb5\x02\n" +
	"\x06Deploy\x126\n" +
	"\x05Apply\x12\x15.jaco.v1.ApplyRequest\x1a\x16.jaco.v1.ApplyResponse\x12?\n" +
	"\bRollback\x12\x18.jaco.v1.RollbackRequest\x1a\x19.jaco.v1.RollbackResponse\x129\n" +
	"\x06Delete\x12\x16.jaco.v1.DeleteRequest\x1a\x17.jaco.v1.DeleteResponse\x12E\n" +
	"\x06Status\x12\x1c.jaco.v1.DeployStatusRequest\x1a\x1d.jaco.v1.DeployStatusResponse\x120\n" +
	"\x04Logs\x12\x14.jaco.v1.LogsRequest\x1a\x10.jaco.v1.LogLine0\x012\xce\x01\n" +
	"\x06Tokens\x12@\n" +
	"\x05Issue\x12\x1a.jaco.v1.TokenIssueRequest\x1a\x1b.jaco.v1.TokenIssueResponse\x12C\n" +
	"\x06Revoke\x12\x1b.jaco.v1.TokenRevokeRequest\x1a\x1c.jaco.v1.TokenRevokeResponse\x12=\n" +
	"\x04List\x12\x19.jaco.v1.TokenListRequest\x1a\x1a.jaco.v1.TokenListResponse2C\n" +
	"\x05Audit\x12:\n" +
	"\x05Query\x12\x1a.jaco.v1.AuditQueryRequest\x1a\x13.jaco.v1.AuditEvent0\x012J\n" +
	"\x05Watch\x12A\n" +
	"\tSubscribe\x12\x19.jaco.v1.SubscribeRequest\x1a\x17.jaco.v1.SubscribeEvent0\x012\xc4\x01\n" +
	"\bInternal\x129\n" +
	"\x06Submit\x12\x16.jaco.v1.SubmitRequest\x1a\x17.jaco.v1.SubmitResponse\x12K\n" +
	"\fSignNodeCert\x12\x1c.jaco.v1.SignNodeCertRequest\x1a\x1d.jaco.v1.SignNodeCertResponse\x120\n" +
	"\x04Logs\x12\x14.jaco.v1.LogsRequest\x1a\x10.jaco.v1.LogLine0\x01B:Z8github.com/PatrickRuddiman/jaco/pkg/proto/jaco/v1;jacov1b\x06proto3"

var (
	file_jaco_v1_services_proto_rawDescOnce sync.Once
	file_jaco_v1_services_proto_rawDescData []byte
)

func file_jaco_v1_services_proto_rawDescGZIP() []byte {
	file_jaco_v1_services_proto_rawDescOnce.Do(func() {
		file_jaco_v1_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jaco_v1_services_proto_rawDesc), len(file_jaco_v1_services_proto_rawDesc)))
	})
	return file_jaco_v1_services_proto_rawDescData
}

var file_jaco_v1_services_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_jaco_v1_services_proto_goTypes = []any{
	(*BootstrapRequest)(nil),       // 0: jaco.v1.BootstrapRequest
	(*BootstrapResponse)(nil),      // 1: jaco.v1.BootstrapResponse
	(*IssueJoinTokenRequest)(nil),  // 2: jaco.v1.IssueJoinTokenRequest
	(*IssueJoinTokenResponse)(nil), // 3: jaco.v1.IssueJoinTokenResponse
	(*NodeJoinRequest)(nil),        // 4: jaco.v1.NodeJoinRequest
	(*NodeJoinResponse)(nil),       // 5: jaco.v1.NodeJoinResponse
	(*NodeRemoveRequest)(nil),      // 6: jaco.v1.NodeRemoveRequest
	(*NodeRemoveResponse)(nil),     // 7: jaco.v1.NodeRemoveResponse
	(*NodeListRequest)(nil),        // 8: jaco.v1.NodeListRequest
	(*NodeListResponse)(nil),       // 9: jaco.v1.NodeListResponse
	(*BackupRequest)(nil),          // 10: jaco.v1.BackupRequest
	(*BackupChunk)(nil),            // 11: jaco.v1.BackupChunk
	(*RestoreResponse)(nil),        // 12: jaco.v1.RestoreResponse
	(*ClusterStatusRequest)(nil),   // 13: jaco.v1.ClusterStatusRequest
	(*ClusterStatusResponse)(nil),  // 14: jaco.v1.ClusterStatusResponse
	(*ApplyRequest)(nil),           // 15: jaco.v1.ApplyRequest
	(*ApplyResponse)(nil),          // 16: jaco.v1.ApplyResponse
	(*Diff)(nil),                   // 17: jaco.v1.Diff
	(*RollbackRequest)(nil),        // 18: jaco.v1.RollbackRequest
	(*RollbackResponse)(nil),       // 19: jaco.v1.RollbackResponse
	(*DeleteRequest)(nil),          // 20: jaco.v1.DeleteRequest
	(*DeleteResponse)(nil),         // 21: jaco.v1.DeleteResponse
	(*DeployStatusRequest)(nil),    // 22: jaco.v1.DeployStatusRequest
	(*DeployStatusResponse)(nil),   // 23: jaco.v1.DeployStatusResponse
	(*LogsRequest)(nil),            // 24: jaco.v1.LogsRequest
	(*LogLine)(nil),                // 25: jaco.v1.LogLine
	(*TokenIssueRequest)(nil),      // 26: jaco.v1.TokenIssueRequest
	(*TokenIssueResponse)(nil),     // 27: jaco.v1.TokenIssueResponse
	(*TokenRevokeRequest)(nil),     // 28: jaco.v1.TokenRevokeRequest
	(*TokenRevokeResponse)(nil),    // 29: jaco.v1.TokenRevokeResponse
	(*TokenListRequest)(nil),       // 30: jaco.v1.TokenListRequest
	(*TokenListResponse)(nil),      // 31: jaco.v1.TokenListResponse
	(*TokenInfo)(nil),              // 32: jaco.v1.TokenInfo
	(*AuditQueryRequest)(nil),      // 33: jaco.v1.AuditQueryRequest
	(*SubscribeRequest)(nil),       // 34: jaco.v1.SubscribeRequest
	(*SubscribeEvent)(nil),         // 35: jaco.v1.SubscribeEvent
	(*SubmitRequest)(nil),          // 36: jaco.v1.SubmitRequest
	(*SubmitResponse)(nil),         // 37: jaco.v1.SubmitResponse
	(*SignNodeCertRequest)(nil),    // 38: jaco.v1.SignNodeCertRequest
	(*SignNodeCertResponse)(nil),   // 39: jaco.v1.SignNodeCertResponse
	(*Node)(nil),                   // 40: jaco.v1.Node
	(*Deployment)(nil),             // 41: jaco.v1.Deployment
	(*ReplicaObserved)(nil),        // 42: jaco.v1.ReplicaObserved
	(*Route)(nil),                  // 43: jaco.v1.Route
	(*timestamppb.Timestamp)(nil),  // 44: google.protobuf.Timestamp
	(AuditEventType)(0),            // 45: jaco.v1.AuditEventType
	(*NodeEvent)(nil),              // 46: jaco.v1.NodeEvent
	(*DeploymentEvent)(nil),        // 47: jaco.v1.DeploymentEvent
	(*ReplicaDesiredEvent)(nil),    // 48: jaco.v1.ReplicaDesiredEvent
	(*ReplicaObservedEvent)(nil),   // 49: jaco.v1.ReplicaObservedEvent
	(*RouteEvent)(nil),             // 50: jaco.v1.RouteEvent
	(*CertEvent)(nil),              // 51: jaco.v1.CertEvent
	(*ChallengeTokenEvent)(nil),    // 52: jaco.v1.ChallengeTokenEvent
	(*TokenEvent)(nil),             // 53: jaco.v1.TokenEvent
	(*JoinTokenEvent)(nil),         // 54: jaco.v1.JoinTokenEvent
	(*AuditLogEvent)(nil),          // 55: jaco.v1.AuditLogEvent
	(*SubnetEvent)(nil),            // 56: jaco.v1.SubnetEvent
	(*RolloutPlanEvent)(nil),       // 57: jaco.v1.RolloutPlanEvent
	(*ReplicaCounterEvent)(nil),    // 58: jaco.v1.ReplicaCounterEvent
	(*RestartCounterEvent)(nil),    // 59: jaco.v1.RestartCounterEvent
	(*AuditEvent)(nil),             // 60: jaco.v1.AuditEvent
}
var file_jaco_v1_services_proto_depIdxs = []int32{
	40, // 0: jaco.v1.NodeListResponse.nodes:type_name -> jaco.v1.Node
	40, // 1: jaco.v1.ClusterStatusResponse.nodes:type_name -> jaco.v1.Node
	17, // 2: jaco.v1.ApplyResponse.diff:type_name -> jaco.v1.Diff
	41, // 3: jaco.v1.DeployStatusResponse.deployments:type_name -> jaco.v1.Deployment
	42, // 4: jaco.v1.DeployStatusResponse.replicas:type_name -> jaco.v1.ReplicaObserved
	43, // 5: jaco.v1.DeployStatusResponse.routes:type_name -> jaco.v1.Route
	44, // 6: jaco.v1.LogLine.ts:type_name -> google.protobuf.Timestamp
	44, // 7: jaco.v1.TokenIssueResponse.issued_at:type_name -> google.protobuf.Timestamp
	32, // 8: jaco.v1.TokenListResponse.tokens:type_name -> jaco.v1.TokenInfo
	44, // 9: jaco.v1.TokenInfo.issued_at:type_name -> google.protobuf.Timestamp
	44, // 10: jaco.v1.TokenInfo.revoked_at:type_name -> google.protobuf.Timestamp
	44, // 11: jaco.v1.AuditQueryRequest.since:type_name -> google.protobuf.Timestamp
	44, // 12: jaco.v1.AuditQueryRequest.until:type_name -> google.protobuf.Timestamp
	45, // 13: jaco.v1.AuditQueryRequest.types:type_name -> jaco.v1.AuditEventType
	46, // 14: jaco.v1.SubscribeEvent.node:type_name -> jaco.v1.NodeEvent
	47, // 15: jaco.v1.SubscribeEvent.deployment:type_name -> jaco.v1.DeploymentEvent
	48, // 16: jaco.v1.SubscribeEvent.replica_desired:type_name -> jaco.v1.ReplicaDesiredEvent
	49, // 17: jaco.v1.SubscribeEvent.replica_observed:type_name -> jaco.v1.ReplicaObservedEvent
	50, // 18: jaco.v1.SubscribeEvent.route:type_name -> jaco.v1.RouteEvent
	51, // 19: jaco.v1.SubscribeEvent.cert:type_name -> jaco.v1.CertEvent
	52, // 20: jaco.v1.SubscribeEvent.challenge_token:type_name -> jaco.v1.ChallengeTokenEvent
	53, // 21: jaco.v1.SubscribeEvent.token:type_name -> jaco.v1.TokenEvent
	54, // 22: jaco.v1.SubscribeEvent.join_token:type_name -> jaco.v1.JoinTokenEvent
	55, // 23: jaco.v1.SubscribeEvent.audit:type_name -> jaco.v1.AuditLogEvent
	56, // 24: jaco.v1.SubscribeEvent.subnet:type_name -> jaco.v1.SubnetEvent
	57, // 25: jaco.v1.SubscribeEvent.rollout_plan:type_name -> jaco.v1.RolloutPlanEvent
	58, // 26: jaco.v1.SubscribeEvent.replica_counter:type_name -> jaco.v1.ReplicaCounterEvent
	59, // 27: jaco.v1.SubscribeEvent.restart_counter:type_name -> jaco.v1.RestartCounterEvent
	0,  // 28: jaco.v1.Cluster.Bootstrap:input_type -> jaco.v1.BootstrapRequest
	2,  // 29: jaco.v1.Cluster.IssueJoinToken:input_type -> jaco.v1.IssueJoinTokenRequest
	4,  // 30: jaco.v1.Cluster.NodeJoin:input_type -> jaco.v1.NodeJoinRequest
	6,  // 31: jaco.v1.Cluster.NodeRemove:input_type -> jaco.v1.NodeRemoveRequest
	8,  // 32: jaco.v1.Cluster.NodeList:input_type -> jaco.v1.NodeListRequest
	10, // 33: jaco.v1.Cluster.Backup:input_type -> jaco.v1.BackupRequest
	11, // 34: jaco.v1.Cluster.Restore:input_type -> jaco.v1.BackupChunk
	13, // 35: jaco.v1.Cluster.Status:input_type -> jaco.v1.ClusterStatusRequest
	15, // 36: jaco.v1.Deploy.Apply:input_type -> jaco.v1.ApplyRequest
	18, // 37: jaco.v1.Deploy.Rollback:input_type -> jaco.v1.RollbackRequest
	20, // 38: jaco.v1.Deploy.Delete:input_type -> jaco.v1.DeleteRequest
	22, // 39: jaco.v1.Deploy.Status:input_type -> jaco.v1.DeployStatusRequest
	24, // 40: jaco.v1.Deploy.Logs:input_type -> jaco.v1.LogsRequest
	26, // 41: jaco.v1.Tokens.Issue:input_type -> jaco.v1.TokenIssueRequest
	28, // 42: jaco.v1.Tokens.Revoke:input_type -> jaco.v1.TokenRevokeRequest
	30, // 43: jaco.v1.Tokens.List:input_type -> jaco.v1.TokenListRequest
	33, // 44: jaco.v1.Audit.Query:input_type -> jaco.v1.AuditQueryRequest
	34, // 45: jaco.v1.Watch.Subscribe:input_type -> jaco.v1.SubscribeRequest
	36, // 46: jaco.v1.Internal.Submit:input_type -> jaco.v1.SubmitRequest
	38, // 47: jaco.v1.Internal.SignNodeCert:input_type -> jaco.v1.SignNodeCertRequest
	24, // 48: jaco.v1.Internal.Logs:input_type -> jaco.v1.LogsRequest
	1,  // 49: jaco.v1.Cluster.Bootstrap:output_type -> jaco.v1.BootstrapResponse
	3,  // 50: jaco.v1.Cluster.IssueJoinToken:output_type -> jaco.v1.IssueJoinTokenResponse
	5,  // 51: jaco.v1.Cluster.NodeJoin:output_type -> jaco.v1.NodeJoinResponse
	7,  // 52: jaco.v1.Cluster.NodeRemove:output_type -> jaco.v1.NodeRemoveResponse
	9,  // 53: jaco.v1.Cluster.NodeList:output_type -> jaco.v1.NodeListResponse
	11, // 54: jaco.v1.Cluster.Backup:output_type -> jaco.v1.BackupChunk
	12, // 55: jaco.v1.Cluster.Restore:output_type -> jaco.v1.RestoreResponse
	14, // 56: jaco.v1.Cluster.Status:output_type -> jaco.v1.ClusterStatusResponse
	16, // 57: jaco.v1.Deploy.Apply:output_type -> jaco.v1.ApplyResponse
	19, // 58: jaco.v1.Deploy.Rollback:output_type -> jaco.v1.RollbackResponse
	21, // 59: jaco.v1.Deploy.Delete:output_type -> jaco.v1.DeleteResponse
	23, // 60: jaco.v1.Deploy.Status:output_type -> jaco.v1.DeployStatusResponse
	25, // 61: jaco.v1.Deploy.Logs:output_type -> jaco.v1.LogLine
	27, // 62: jaco.v1.Tokens.Issue:output_type -> jaco.v1.TokenIssueResponse
	29, // 63: jaco.v1.Tokens.Revoke:output_type -> jaco.v1.TokenRevokeResponse
	31, // 64: jaco.v1.Tokens.List:output_type -> jaco.v1.TokenListResponse
	60, // 65: jaco.v1.Audit.Query:output_type -> jaco.v1.AuditEvent
	35, // 66: jaco.v1.Watch.Subscribe:output_type -> jaco.v1.SubscribeEvent
	37, // 67: jaco.v1.Internal.Submit:output_type -> jaco.v1.SubmitResponse
	39, // 68: jaco.v1.Internal.SignNodeCert:output_type -> jaco.v1.SignNodeCertResponse
	25, // 69: jaco.v1.Internal.Logs:output_type -> jaco.v1.LogLine
	49, // [49:70] is the sub-list for method output_type
	28, // [28:49] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_jaco_v1_services_proto_init() }
func file_jaco_v1_services_proto_init() {
	if File_jaco_v1_services_proto != nil {
		return
	}
	file_jaco_v1_entities_proto_init()
	file_jaco_v1_events_proto_init()
	file_jaco_v1_services_proto_msgTypes[35].OneofWrappers = []any{
		(*SubscribeEvent_Node)(nil),
		(*SubscribeEvent_Deployment)(nil),
		(*SubscribeEvent_ReplicaDesired)(nil),
		(*SubscribeEvent_ReplicaObserved)(nil),
		(*SubscribeEvent_Route)(nil),
		(*SubscribeEvent_Cert)(nil),
		(*SubscribeEvent_ChallengeToken)(nil),
		(*SubscribeEvent_Token)(nil),
		(*SubscribeEvent_JoinToken)(nil),
		(*SubscribeEvent_Audit)(nil),
		(*SubscribeEvent_Subnet)(nil),
		(*SubscribeEvent_RolloutPlan)(nil),
		(*SubscribeEvent_ReplicaCounter)(nil),
		(*SubscribeEvent_RestartCounter)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jaco_v1_services_proto_rawDesc), len(file_jaco_v1_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_jaco_v1_services_proto_goTypes,
		DependencyIndexes: file_jaco_v1_services_proto_depIdxs,
		MessageInfos:      file_jaco_v1_services_proto_msgTypes,
	}.Build()
	File_jaco_v1_services_proto = out.File
	file_jaco_v1_services_proto_goTypes = nil
	file_jaco_v1_services_proto_depIdxs = nil
}
